return {
	mod_name = {
		en = "Machine God's Beacon",
		["zh-cn"] = "万机之神灯火管制",
		ru = "Маяк Бога-Машины",
		de = "Leuchtfeuer des Maschinengottes",
		fr = "Balise du Dieu-Machine",
		es = "Baliza del Dios Máquina",
	},
	mod_description = {
		en = "By invocation of the Machine God, the lumen-spirits of the habitat are awakened.",
		["zh-cn"] = "藉由万机神的召唤，栖息地的光魂已然苏醒。",
		ru = "По призыву Бога-Машины пробуждаются люмен-духи обители.",
		de = "Durch die Anrufung des Maschinengottes erwachen die Lumen-Geister der Behausung.",
		fr = "Par l’invocation du Dieu-Machine, les esprits-lumen de l’habitat s’éveillent.",
		es = "Por invocación del Dios Máquina, los espíritus-lumen del hábitat despiertan.",
	},

	general_group = {
		en = "General Settings",
		["zh-cn"] = "常规设置",
		ru = "Общие настройки",
		de = "Allgemeine Einstellungen",
		fr = "Paramètres généraux",
		es = "Ajustes generales",
	},
	enable_light_control_title = {
		en = "Enable Light Control",
		["zh-cn"] = "启用灯光控制",
		ru = "Включить контроль света",
		de = "Lichtkontrolle aktivieren",
		fr = "Activer le contrôle des lumières",
		es = "Activar control de luces",
	},
	enable_light_control_tooltip = {
		en = "Take control of mission lighting.",
		["zh-cn"] = "接管任务中的照明控制权。",
		ru = "Взять освещение миссии под свой надзор.",
		de = "Übernimm die Herrschaft über die Beleuchtung der Mission.",
		fr = "Prendre la maîtrise de l’éclairage en mission.",
		es = "Tomar el control de la iluminación de la misión.",
	},

	opt_in_special_missions_title = {
		en = "Include Special Missions",
		["zh-cn"] = "涵盖特殊任务",
		ru = "Включить особые миссии",
		de = "Spezialmissionen einbeziehen",
		fr = "Inclure les missions spéciales",
		es = "Incluir misiones especiales",
	},
	opt_in_special_missions_tooltip = {
		en = "Also apply to Lights Out and Ventilation Purge missions.",
		["zh-cn"] = "亦应用于熄灯与通风净化任务。",
		ru = "Также действует в миссиях «Lights Out» и «Ventilation Purge».",
		de = "Gilt auch für „Lights Out“- und „Ventilation Purge“-Missionen.",
		fr = "S’applique aussi aux missions « Lights Out » et « Ventilation Purge ».",
		es = "También se aplica a misiones «Lights Out» y «Ventilation Purge».",
	},

	light_percentage_title = {
		en = "Lights On",
		["zh-cn"] = "亮灯比例",
		ru = "Свет включён",
		de = "Lichter an",
		fr = "Lumières allumées",
		es = "Luces encendidas",
	},
	light_percentage_tooltip = {
		en = "Percent of lights to keep on per group.",
		["zh-cn"] = "每组中保持亮起的灯光百分比。",
		ru = "Процент огней, что останутся гореть в каждой группе.",
		de = "Anteil der Lichter, die pro Gruppe an bleiben.",
		fr = "Pourcentage de lumières maintenues allumées par groupe.",
		es = "Porcentaje de luces que se mantienen encendidas por grupo.",
	},

	light_selection_title = {
		en = "Selection Mode",
		["zh-cn"] = "选择模式",
		ru = "Способ выбора",
		de = "Auswahlmodus",
		fr = "Mode de sélection",
		es = "Modo de selección",
	},
	light_selection_tooltip = {
		en = "How to choose which lights stay on.",
		["zh-cn"] = "选择哪些灯保持亮起的方式。",
		ru = "Как выбираются огни, что останутся гореть.",
		de = "Wie gewählt wird, welche Lichter an bleiben.",
		fr = "Comment sont choisies les lumières qui restent allumées.",
		es = "Cómo se eligen las luces que permanecen encendidas.",
	},
	light_selection_incremental = {
		en = "Incremental",
		["zh-cn"] = "递增",
		ru = "По порядку",
		de = "Fortlaufend",
		fr = "Progressif",
		es = "Progresivo",
	},
	light_selection_alternating = {
		en = "Alternating",
		["zh-cn"] = "交替",
		ru = "Через одну",
		de = "Abwechselnd",
		fr = "Alterné",
		es = "Alterno",
	},
	light_selection_spread = {
		en = "Spread",
		["zh-cn"] = "分散",
		ru = "Равномерно",
		de = "Verteilt",
		fr = "Réparti",
		es = "Repartido",
	},
	light_selection_random = {
		en = "Random",
		["zh-cn"] = "随机",
		ru = "Случайно",
		de = "Zufällig",
		fr = "Aléatoire",
		es = "Aleatorio",
	},

	flicker_group = {
		en = "Flicker Settings",
		["zh-cn"] = "闪烁设置",
		ru = "Настройки мерцания",
		de = "Flacker-Einstellungen",
		fr = "Paramètres de scintillement",
		es = "Ajustes de parpadeo",
	},
	light_state_title = {
		en = "Light Behavior",
		["zh-cn"] = "灯光行为",
		ru = "Поведение света",
		de = "Lichtverhalten",
		fr = "Comportement des lumières",
		es = "Comportamiento de luz",
	},
	light_state_tooltip = {
		en = "Static: fixed. All: together. Cascade: a wave. Random: a chosen few each cycle.",
		["zh-cn"] = "静态：固定。全部：同闪。层叠：波浪闪烁。随机：每周期择其一隅。",
		ru = "Статично: неизменно. Все: вместе. Каскад: волной. Случайно: избранные каждый цикл.",
		de = "Statisch: fest. Alle: gemeinsam. Kaskade: als Welle. Zufällig: einige pro Zyklus.",
		fr = "Statique : fixe. Tous : ensemble. Cascade : en vague. Aléatoire : quelques élus par cycle.",
		es = "Estático: fijo. Todo: a la vez. Cascada: en oleada. Aleatorio: unos pocos por ciclo.",
	},
	light_state_static = {
		en = "Static",
		["zh-cn"] = "静态",
		ru = "Статично",
		de = "Statisch",
		fr = "Statique",
		es = "Estático",
	},
	light_state_flicker = {
		en = "Flicker (All)",
		["zh-cn"] = "闪烁（全部）",
		ru = "Мерцать (все)",
		de = "Flackern (alle)",
		fr = "Scintiller (tous)",
		es = "Parpadear (todas)",
	},
	light_state_flicker_cascade = {
		en = "Flicker (Cascade)",
		["zh-cn"] = "闪烁（层叠）",
		ru = "Мерцать (каскад)",
		de = "Flackern (Kaskade)",
		fr = "Scintiller (cascade)",
		es = "Parpadear (cascada)",
	},
	light_state_flicker_random = {
		en = "Flicker (Random)",
		["zh-cn"] = "闪烁（随机）",
		ru = "Мерцать (случайно)",
		de = "Flackern (zufällig)",
		fr = "Scintiller (aléatoire)",
		es = "Parpadear (aleatorio)",
	},

	flicker_default_title = {
		en = "Flicker Target",
		["zh-cn"] = "闪烁目标",
		ru = "Цель мерцания",
		de = "Flackerziel",
		fr = "Cible du scintillement",
		es = "Objetivo de parpadeo",
	},
	flicker_default_tooltip = {
		en = "Choose the faithful or the fallen: lights set on briefly dim; lights set off briefly ignite.",
		["zh-cn"] = "择其所试：设为亮者短暂熄灭；设为灭者短暂亮起。",
		ru = "Выбери, кого испытать: включённые огни кратко гаснут; выключенные — вспыхивают.",
		de = "Wähle, wen die Prüfung trifft: An-Lichter dimmen kurz; Aus-Lichter entflammen kurz.",
		fr = "Choisis qui sera éprouvé : les allumées s’éteignent brièvement ; les éteintes s’embrasent.",
		es = "Elige a quién se prueba: las encendidas se apagan un instante; las apagadas prenden un instante.",
	},
	flicker_default_on = {
		en = "Enabled Lights",
		["zh-cn"] = "启用的灯",
		ru = "Включённые огни",
		de = "Aktive Lichter",
		fr = "Lumières activées",
		es = "Luces activadas",
	},
	flicker_default_off = {
		en = "Disabled Lights",
		["zh-cn"] = "禁用的灯",
		ru = "Выключенные огни",
		de = "Deaktivierte Lichter",
		fr = "Lumières désactivées",
		es = "Luces desactivadas",
	},

	flicker_interval_title = {
		en = "Interval (s)",
		["zh-cn"] = "间隔（秒）",
		ru = "Интервал (с)",
		de = "Intervall (s)",
		fr = "Intervalle (s)",
		es = "Intervalo (s)",
	},
	flicker_interval_tooltip = {
		en = "Seconds between flicker cycles.",
		["zh-cn"] = "闪烁周期之间的秒数。",
		ru = "Секунды между циклами мерцания.",
		de = "Sekunden zwischen Flackerzyklen.",
		fr = "Secondes entre les cycles de scintillement.",
		es = "Segundos entre ciclos de parpadeo.",
	},
	flicker_percentage_title = {
		en = "Flicker Amount",
		["zh-cn"] = "闪烁比例",
		ru = "Доля мерцания",
		de = "Flackeranteil",
		fr = "Quantité de scintillement",
		es = "Cantidad de parpadeo",
	},
	flicker_percentage_tooltip = {
		en = "Percent of eligible lights to flicker each cycle.",
		["zh-cn"] = "每周期闪烁符合条件灯光的百分比。",
		ru = "Процент подходящих огней, что мерцают в каждом цикле.",
		de = "Anteil geeigneter Lichter, die pro Zyklus flackern.",
		fr = "Pourcentage de lumières éligibles qui scintillent à chaque cycle.",
		es = "Porcentaje de luces elegibles que parpadean en cada ciclo.",
	},
	flicker_duration_title = {
		en = "Duration (s)",
		["zh-cn"] = "持续时长（秒）",
		ru = "Длительность (с)",
		de = "Dauer (s)",
		fr = "Durée (s)",
		es = "Duración (s)",
	},
	flicker_duration_tooltip = {
		en = "Seconds a light stays in flicker state.",
		["zh-cn"] = "灯光保持闪烁状态的秒数。",
		ru = "Сколько секунд свет держится в состоянии мерцания.",
		de = "Wie viele Sekunden ein Licht im Flackerzustand bleibt.",
		fr = "Nombre de secondes qu’une lumière reste en état de scintillement.",
		es = "Segundos que una luz permanece en estado de parpadeo.",
	},
	flicker_cooldown_title = {
		en = "Cooldown (s)",
		["zh-cn"] = "冷却时间（秒）",
		ru = "Откат (с)",
		de = "Abklingzeit (s)",
		fr = "Recharge (s)",
		es = "Reutilización (s)",
	},
	flicker_cooldown_tooltip = {
		en = "Seconds before a light can flicker again.",
		["zh-cn"] = "同一盏灯再次闪烁前需要等待的秒数。",
		ru = "Сколько секунд должно пройти, прежде чем свет сможет мерцать снова.",
		de = "Sekunden, bevor ein Licht erneut flackern darf.",
		fr = "Secondes avant qu’une lumière puisse scintiller à nouveau.",
		es = "Segundos antes de que una luz pueda parpadear de nuevo.",
	},

	enable_stutter_title = {
		en = "Enable Stutter",
		["zh-cn"] = "启用卡顿效果",
		ru = "Включить дрожание",
		de = "Stottern aktivieren",
		fr = "Activer le bégaiement",
		es = "Activar tartamudeo",
	},
	enable_stutter_tooltip = {
		en = "Rapid on/off cycling instead of a single toggle.",
		["zh-cn"] = "使用快速的开关循环，而非单一的切换。",
		ru = "Быстрые циклы вкл/выкл вместо одного переключения.",
		de = "Schnelles An/Aus statt eines einzelnen Umschaltens.",
		fr = "Cycles rapides on/off au lieu d’un seul basculement.",
		es = "Ciclos rápidos de encendido/apagado en vez de un solo cambio.",
	},
	stutter_count_title = {
		en = "Stutter Count",
		["zh-cn"] = "卡顿次数",
		ru = "Число циклов",
		de = "Stotter-Zyklen",
		fr = "Nombre de cycles",
		es = "Repeticiones",
	},
	stutter_count_tooltip = {
		en = "Base cycles per stutter (with variation).",
		["zh-cn"] = "每次卡顿的基础循环次数（含随机变化）。",
		ru = "Базовое число циклов на дрожание (с вариацией).",
		de = "Grundzyklen pro Stottern (mit Abweichung).",
		fr = "Cycles de base par bégaiement (avec variation).",
		es = "Ciclos base por tartamudeo (con variación).",
	},

	debug_group = {
		en = "Debug Settings",
		["zh-cn"] = "调试设置",
		ru = "Отладка",
		de = "Debug-Einstellungen",
		fr = "Paramètres de débogage",
		es = "Ajustes de depuración",
	},
	disable_darkness_title = {
		en = "Disable Darkness",
		["zh-cn"] = "禁用黑暗效果",
		ru = "Отключить тьму",
		de = "Dunkelheit deaktivieren",
		fr = "Désactiver l’obscurité",
		es = "Desactivar oscuridad",
	},
	disable_darkness_tooltip = {
		en = "Remove darkness visual effect in Lights Out missions.",
		["zh-cn"] = "移除熄灯任务中的黑暗视觉效果。",
		ru = "Убрать визуальный эффект тьмы в миссиях «Lights Out».",
		de = "Entfernt den Dunkelheits-Effekt in „Lights Out“-Missionen.",
		fr = "Supprime l’effet visuel d’obscurité dans les missions « Lights Out ».",
		es = "Quita el efecto visual de oscuridad en misiones «Lights Out».",
	},
	disable_fog_title = {
		en = "Disable Fog",
		["zh-cn"] = "禁用迷雾效果",
		ru = "Отключить туман",
		de = "Nebel deaktivieren",
		fr = "Désactiver le brouillard",
		es = "Desactivar niebla",
	},
	disable_fog_tooltip = {
		en = "Remove fog visual effect in Ventilation Purge missions.",
		["zh-cn"] = "移除通风净化任务中的迷雾视觉效果。",
		ru = "Убрать визуальный эффект тумана в миссиях «Ventilation Purge».",
		de = "Entfernt den Nebel-Effekt in „Ventilation Purge“-Missionen.",
		fr = "Supprime l’effet visuel de brouillard dans les missions « Ventilation Purge ».",
		es = "Quita el efecto visual de niebla en misiones «Ventilation Purge».",
	},
	debug_mode_title = {
		en = "Debug Mode",
		["zh-cn"] = "调试模式",
		ru = "Режим отладки",
		de = "Debug-Modus",
		fr = "Mode débogage",
		es = "Modo depuración",
	},
	debug_mode_tooltip = {
		en = "Show debug messages in chat.",
		["zh-cn"] = "在聊天中显示调试信息。",
		ru = "Показывать отладочные сообщения в чате.",
		de = "Debug-Meldungen im Chat anzeigen.",
		fr = "Afficher les messages de débogage dans le chat.",
		es = "Mostrar mensajes de depuración en el chat.",
	},
}
