return {
	mod_name = {
		en = "Machine God's Beacon",
		["zh-cn"] = "万机之神的灯塔",
		ru = "Маяк Бога-Машины",
		de = "Leuchtfeuer des Maschinengottes",
		fr = "Balise du Dieu-Machine",
		es = "Faro del Dios Máquina",
	},
	mod_description = {
		en = "By invocation of the Machine God, the lumen-spirits of the habitat are awakened.",
		["zh-cn"] = "藉万机之神的召唤，栖息地的光魂已然苏醒。",
		ru = "По призыву Бога-Машины пробуждаются люмен-духи обители.",
		de = "Durch Anrufung des Maschinengottes erwachen die Lumen-Geister der Behausung.",
		fr = "Par l'invocation du Dieu-Machine, les esprits-lumen de l'habitat s'éveillent.",
		es = "Por invocación del Dios Máquina, los espíritus-lumen del hábitat despiertan.",
	},
	light_group = {
		en = "Light Control",
		["zh-cn"] = "灯光控制",
		ru = "Управление светом",
		de = "Lichtsteuerung",
		fr = "Contrôle des lumières",
		es = "Control de luces",
	},
	flicker_group = {
		en = "Flicker Settings",
		["zh-cn"] = "闪烁设置",
		ru = "Настройки мерцания",
		de = "Flacker-Einstellungen",
		fr = "Paramètres de scintillement",
		es = "Ajustes de parpadeo",
	},
	environment_group = {
		en = "Environment Control",
		["zh-cn"] = "环境控制",
		ru = "Управление окружением",
		de = "Umgebungssteuerung",
		fr = "Contrôle de l'environnement",
		es = "Control del entorno",
	},
	debug_group = {en = "Debug", ["zh-cn"] = "调试", ru = "Отладка", de = "Debug", fr = "Débogage", es = "Depuración"},
	mode_none = {en = "Off", ["zh-cn"] = "关闭", ru = "Выкл", de = "Aus", fr = "Désactivé", es = "Desactivado"},
	mode_all = {
		en = "All Missions",
		["zh-cn"] = "所有任务",
		ru = "Все миссии",
		de = "Alle Missionen",
		fr = "Toutes les missions",
		es = "Todas las misiones",
	},
	mode_normal = {
		en = "Normal Missions Only",
		["zh-cn"] = "仅普通任务",
		ru = "Только обычные",
		de = "Nur normale Missionen",
		fr = "Missions normales uniquement",
		es = "Solo misiones normales",
	},
	mode_modified = {
		en = "Special Missions Only",
		["zh-cn"] = "仅特殊任务",
		ru = "Только особые",
		de = "Nur Spezialmissionen",
		fr = "Missions spéciales uniquement",
		es = "Solo misiones especiales",
	},
	light_control_mode_title = {
		en = "Light Control",
		["zh-cn"] = "灯光控制",
		ru = "Управление светом",
		de = "Lichtsteuerung",
		fr = "Contrôle des lumières",
		es = "Control de luces",
	},
	environment_control_mode_title = {
		en = "Block Darkness/Fog",
		["zh-cn"] = "阻挡黑暗/迷雾",
		ru = "Блокировка тьмы/тумана",
		de = "Dunkelheit/Nebel blockieren",
		fr = "Bloquer obscurité/brouillard",
		es = "Bloquear oscuridad/niebla",
	},
	environment_control_mode_tooltip = {
		en = "{#color(255, 35, 5)}Requires map/instance reload{#reset()}",
		["zh-cn"] = "{#color(255, 35, 5)}需要重载地图/实例{#reset()}",
		ru = "{#color(255, 35, 5)}Требуется перезагрузка карты{#reset()}",
		de = "{#color(255, 35, 5)}Karten-/Instanz-Neuladen erforderlich{#reset()}",
		fr = "{#color(255, 35, 5)}Rechargement de carte/instance requis{#reset()}",
		es = "{#color(255, 35, 5)}Requiere recarga de mapa/instancia{#reset()}",
	},
	light_percentage_title = {
		en = "Light Percentage",
		["zh-cn"] = "灯光百分比",
		ru = "Процент освещения",
		de = "Lichtanteil",
		fr = "Pourcentage de lumières",
		es = "Porcentaje de luces",
	},
	light_selection_title = {
		en = "Light Selection Mode",
		["zh-cn"] = "灯光选择模式",
		ru = "Режим выбора",
		de = "Auswahlmodus",
		fr = "Mode de sélection",
		es = "Modo de selección",
	},
	light_selection_incremental = {
		en = "Incremental",
		["zh-cn"] = "递增",
		ru = "Последовательно",
		de = "Fortlaufend",
		fr = "Progressif",
		es = "Progresivo",
	},
	light_selection_alternating = {
		en = "Alternating",
		["zh-cn"] = "交替",
		ru = "Чередование",
		de = "Abwechselnd",
		fr = "Alterné",
		es = "Alterno",
	},
	light_selection_spread = {
		en = "Spread",
		["zh-cn"] = "分散",
		ru = "Равномерно",
		de = "Verteilt",
		fr = "Réparti",
		es = "Distribuido",
	},
	light_selection_random = {
		en = "Random",
		["zh-cn"] = "随机",
		ru = "Случайно",
		de = "Zufällig",
		fr = "Aléatoire",
		es = "Aleatorio",
	},
	light_state_title = {
		en = "Light Mode",
		["zh-cn"] = "灯光模式",
		ru = "Режим света",
		de = "Lichtmodus",
		fr = "Mode d'éclairage",
		es = "Modo de luz",
	},
	light_state_static = {
		en = "Static",
		["zh-cn"] = "静态",
		ru = "Статично",
		de = "Statisch",
		fr = "Statique",
		es = "Estático",
	},
	light_state_flicker = {
		en = "Flicker",
		["zh-cn"] = "闪烁",
		ru = "Мерцание",
		de = "Flackern",
		fr = "Scintillement",
		es = "Parpadeo",
	},
	light_state_flicker_cascade = {
		en = "Cascade Flicker",
		["zh-cn"] = "级联闪烁",
		ru = "Каскадное мерцание",
		de = "Kaskaden-Flackern",
		fr = "Scintillement en cascade",
		es = "Parpadeo en cascada",
	},
	light_state_flicker_random = {
		en = "Random Flicker",
		["zh-cn"] = "随机闪烁",
		ru = "Случайное мерцание",
		de = "Zufälliges Flackern",
		fr = "Scintillement aléatoire",
		es = "Parpadeo aleatorio",
	},
	flicker_default_title = {
		en = "Flicker Default State",
		["zh-cn"] = "闪烁默认状态",
		ru = "Состояние по умолчанию",
		de = "Standard-Flickerzustand",
		fr = "État par défaut",
		es = "Estado por defecto",
	},
	flicker_default_on = {en = "On", ["zh-cn"] = "开", ru = "Вкл", de = "An", fr = "Allumé", es = "Encendido"},
	flicker_default_off = {en = "Off", ["zh-cn"] = "关", ru = "Выкл", de = "Aus", fr = "Éteint", es = "Apagado"},
	flicker_interval_title = {
		en = "Flicker Interval (seconds)",
		["zh-cn"] = "闪烁间隔（秒）",
		ru = "Интервал мерцания (сек)",
		de = "Flacker-Intervall (Sekunden)",
		fr = "Intervalle de scintillement (secondes)",
		es = "Intervalo de parpadeo (segundos)",
	},
	flicker_percentage_title = {
		en = "Flicker Percentage",
		["zh-cn"] = "闪烁百分比",
		ru = "Процент мерцания",
		de = "Flacker-Prozentsatz",
		fr = "Pourcentage de scintillement",
		es = "Porcentaje de parpadeo",
	},
	flicker_duration_title = {
		en = "Flicker Duration (seconds)",
		["zh-cn"] = "闪烁持续时间（秒）",
		ru = "Длительность мерцания (сек)",
		de = "Flacker-Dauer (Sekunden)",
		fr = "Durée du scintillement (secondes)",
		es = "Duración del parpadeo (segundos)",
	},
	flicker_cooldown_title = {
		en = "Flicker Cooldown (seconds)",
		["zh-cn"] = "闪烁冷却（秒）",
		ru = "Перезарядка мерцания (сек)",
		de = "Flacker-Abklingzeit (Sekunden)",
		fr = "Recharge du scintillement (secondes)",
		es = "Reutilización del parpadeo (segundos)",
	},
	enable_stutter_title = {
		en = "Enable Stutter",
		["zh-cn"] = "启用频闪",
		ru = "Включить дребезг",
		de = "Stottern aktivieren",
		fr = "Activer le clignotement",
		es = "Activar titubeo",
	},
	stutter_count_title = {
		en = "Stutter Count",
		["zh-cn"] = "频闪次数",
		ru = "Число циклов",
		de = "Stotter-Anzahl",
		fr = "Nombre de clignotements",
		es = "Cantidad de titubeos",
	},
	debug_mode_title = {
		en = "Debug Mode",
		["zh-cn"] = "调试模式",
		ru = "Режим отладки",
		de = "Debug-Modus",
		fr = "Mode débogage",
		es = "Modo depuración",
	},
}
