local mod = get_mod("machine_gods_beacon")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "general_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "enable_light_control",
						type = "checkbox",
						default_value = true,
						title = "enable_light_control_title",
						tooltip = "enable_light_control_tooltip",
					},
					{
						setting_id = "opt_in_special_missions",
						type = "checkbox",
						default_value = false,
						title = "opt_in_special_missions_title",
						tooltip = "opt_in_special_missions_tooltip",
					},
					{
						setting_id = "light_percentage",
						type = "numeric",
						default_value = 33,
						range = {0, 100},
						title = "light_percentage_title",
						tooltip = "light_percentage_tooltip",
					},
					{
						setting_id = "light_selection",
						type = "dropdown",
						default_value = "alternating",
						options = {
							{text = "light_selection_incremental", value = "incremental"},
							{text = "light_selection_alternating", value = "alternating"},
							{text = "light_selection_spread", value = "spread"},
							{text = "light_selection_random", value = "random"},
						},
						title = "light_selection_title",
						tooltip = "light_selection_tooltip",
					},
				},
			},
			{
				setting_id = "flicker_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "light_state",
						type = "dropdown",
						default_value = "flicker_random",
						options = {
							{text = "light_state_static", value = "static"},
							{text = "light_state_flicker", value = "flicker"},
							{text = "light_state_flicker_cascade", value = "flicker_cascade"},
							{text = "light_state_flicker_random", value = "flicker_random"},
						},
						title = "light_state_title",
						tooltip = "light_state_tooltip",
					},
					{
						setting_id = "flicker_default",
						type = "dropdown",
						default_value = "on",
						options = {{text = "flicker_default_on", value = "on"}, {text = "flicker_default_off", value = "off"}},
						title = "flicker_default_title",
						tooltip = "flicker_default_tooltip",
					},
					{
						setting_id = "flicker_interval",
						type = "numeric",
						default_value = 5.0,
						range = {0.5, 30.0},
						decimals_number = 1,
						title = "flicker_interval_title",
						tooltip = "flicker_interval_tooltip",
					},
					{
						setting_id = "flicker_percentage",
						type = "numeric",
						default_value = 33,
						range = {1, 100},
						title = "flicker_percentage_title",
						tooltip = "flicker_percentage_tooltip",
					},
					{
						setting_id = "flicker_duration",
						type = "numeric",
						default_value = 0.5,
						range = {0.5, 3.0},
						decimals_number = 2,
						title = "flicker_duration_title",
						tooltip = "flicker_duration_tooltip",
					},
					{
						setting_id = "flicker_cooldown",
						type = "numeric",
						default_value = 3.0,
						range = {0.5, 30.0},
						decimals_number = 1,
						title = "flicker_cooldown_title",
						tooltip = "flicker_cooldown_tooltip",
					},
					{
						setting_id = "enable_stutter",
						type = "checkbox",
						default_value = false,
						title = "enable_stutter_title",
						tooltip = "enable_stutter_tooltip",
					},
					{
						setting_id = "stutter_count",
						type = "numeric",
						default_value = 3,
						range = {2, 10},
						title = "stutter_count_title",
						tooltip = "stutter_count_tooltip",
					},
				},
			},
			{
				setting_id = "debug_group",
				type = "group",
				sub_widgets = {
					{
						setting_id = "disable_darkness",
						type = "checkbox",
						default_value = false,
						title = "disable_darkness_title",
						tooltip = "disable_darkness_tooltip",
					},
					{
						setting_id = "disable_fog",
						type = "checkbox",
						default_value = false,
						title = "disable_fog_title",
						tooltip = "disable_fog_tooltip",
					},
					{
						setting_id = "debug_mode",
						type = "checkbox",
						default_value = false,
						title = "debug_mode_title",
						tooltip = "debug_mode_tooltip",
					},
				},
			},
		},
	},
}
