-- SMOG_localization.lua
return {
mod_name = {
en = "{#color(93,101,50)}SMOG Cleaner{#reset()}",
de = "{#color(93,101,50)}SMOG-Reiniger{#reset()}",
fr = "{#color(93,101,50)}Nettoyeur SMOG{#reset()}",
ru = "{#color(93,101,50)}Очиститель SMOG{#reset()}",
["zh-cn"] = "{#color(93,101,50)}SMOG 清理器{#reset()}",
es = "{#color(93,101,50)}Limpiador SMOG{#reset()}",
ja = "{#color(93,101,50)}SMOGクリーナー{#reset()}",
},
mod_description_heap = {
en = "Simple Mod Object Garbage Cleaner for your %s sized Lua heap",
de = "Einfacher Bereiniger für Mod-Objektmüll für deinen %s großen Lua-Heap",
fr = "Nettoyeur simple des objets inutilisés des mods pour votre tas Lua de %s",
ru = "Простой очиститель мусора объектов модов для кучи Lua размером %s",
["zh-cn"] = "适用于 %s Lua 堆的简单模组对象垃圾清理器",
es = "Limpiador sencillo de objetos basura de mods para tu heap de Lua de %s",
ja = "%sのLuaヒープ向けModオブジェクト不要データ簡易クリーナー",
},
mod_description_manual = {
en = "Type {#color(255,191,0)}/smog{#reset()} or use the keybind to perform manually",
de = "Gib {#color(255,191,0)}/smog{#reset()} ein oder verwende die Tastenbelegung, um die Bereinigung manuell auszuführen",
fr = "Saisissez {#color(255,191,0)}/smog{#reset()} ou utilisez le raccourci pour effectuer le nettoyage manuellement",
ru = "Введите {#color(255,191,0)}/smog{#reset()} или используйте назначенную клавишу, чтобы выполнить очистку вручную",
["zh-cn"] = "输入 {#color(255,191,0)}/smog{#reset()} 或使用按键绑定手动执行清理",
es = "Escribe {#color(255,191,0)}/smog{#reset()} o usa la tecla asignada para realizar la limpieza manualmente",
ja = "{#color(255,191,0)}/smog{#reset()} と入力するか、キー割り当てを使用して手動でクリーンアップします",
},
cleaning_permitted = {
en = "Cleaning permitted",
de = "Bereinigung zulassen",
fr = "Autoriser le nettoyage",
ru = "Разрешить очистку",
["zh-cn"] = "允许清理",
es = "Permitir limpieza",
ja = "クリーンアップを許可",
},
cleaning_permitted_desc = {
en = "{#color(93,101,50)}Turn off to prevent cleaning; HUD will still work.{#reset()}",
de = "{#color(93,101,50)}Deaktivieren, um die Bereinigung zu verhindern; das HUD funktioniert weiterhin.{#reset()}",
fr = "{#color(93,101,50)}Désactivez cette option pour empêcher le nettoyage ; le HUD continuera de fonctionner.{#reset()}",
ru = "{#color(93,101,50)}Отключите, чтобы запретить очистку; HUD продолжит работать.{#reset()}",
["zh-cn"] = "{#color(93,101,50)}关闭后将停止清理；HUD 仍会正常工作。{#reset()}",
es = "{#color(93,101,50)}Desactívalo para impedir la limpieza; el HUD seguirá funcionando.{#reset()}",
ja = "{#color(93,101,50)}オフにするとクリーンアップを停止します。HUDは引き続き動作します。{#reset()}",
},
auto_clean_on_start = {
en = "Clean at convenient moments",
de = "Zu geeigneten Zeitpunkten bereinigen",
fr = "Nettoyer aux moments opportuns",
ru = "Очищать в подходящие моменты",
["zh-cn"] = "在合适时机清理",
es = "Limpiar en momentos oportunos",
ja = "適切なタイミングでクリーンアップ",
},
auto_clean_every_ten_minutes = {
en = "Auto clean every 10 minutes",
de = "Alle 10 Minuten automatisch bereinigen",
fr = "Nettoyage automatique toutes les 10 minutes",
ru = "Автоочистка каждые 10 минут",
["zh-cn"] = "每 10 分钟自动清理",
es = "Limpieza automática cada 10 minutos",
ja = "10分ごとに自動クリーンアップ",
},
notifications = {
en = "Notifications",
de = "Benachrichtigungen",
fr = "Notifications",
ru = "Уведомления",
["zh-cn"] = "通知",
es = "Notificaciones",
ja = "通知",
},
notifications_desc = {
en = "{#color(93,101,50)}Shows automatic notices. Manual notices still show.{#reset()}",
de = "{#color(93,101,50)}Zeigt automatische Hinweise an. Manuelle Hinweise werden weiterhin angezeigt.{#reset()}",
fr = "{#color(93,101,50)}Affiche les notifications automatiques. Les notifications manuelles restent affichées.{#reset()}",
ru = "{#color(93,101,50)}Показывает автоматические уведомления. Ручные уведомления по-прежнему отображаются.{#reset()}",
["zh-cn"] = "{#color(93,101,50)}显示自动通知。手动通知仍会显示。{#reset()}",
es = "{#color(93,101,50)}Muestra avisos automáticos. Los avisos manuales seguirán apareciendo.{#reset()}",
ja = "{#color(93,101,50)}自動通知を表示します。手動通知は引き続き表示されます。{#reset()}",
},
notifications_header = {
en = "{#size(32);color(93,101,50)}Notifications{#reset()}",
de = "{#size(32);color(93,101,50)}Benachrichtigungen{#reset()}",
fr = "{#size(32);color(93,101,50)}Notifications{#reset()}",
ru = "{#size(32);color(93,101,50)}Уведомления{#reset()}",
["zh-cn"] = "{#size(32);color(93,101,50)}通知{#reset()}",
es = "{#size(32);color(93,101,50)}Notificaciones{#reset()}",
ja = "{#size(32);color(93,101,50)}通知{#reset()}",
},
huds_header = {
en = "{#size(32);color(93,101,50)}HUDs{#reset()}",
de = "{#size(32);color(93,101,50)}HUDs{#reset()}",
fr = "{#size(32);color(93,101,50)}HUD{#reset()}",
ru = "{#size(32);color(93,101,50)}HUD{#reset()}",
["zh-cn"] = "{#size(32);color(93,101,50)}HUD{#reset()}",
es = "{#size(32);color(93,101,50)}HUD{#reset()}",
ja = "{#size(32);color(93,101,50)}HUD{#reset()}",
},
hud_format = {
en = "HUD Format",
de = "HUD-Format",
fr = "Format du HUD",
ru = "Формат HUD",
["zh-cn"] = "HUD 格式",
es = "Formato del HUD",
ja = "HUD形式",
},
hud_format_analogue = {
en = "Analogue",
de = "Analog",
fr = "Analogique",
ru = "Аналоговый",
["zh-cn"] = "模拟",
es = "Analógico",
ja = "アナログ",
},
hud_format_digital = {
en = "Digital",
de = "Digital",
fr = "Numérique",
ru = "Цифровой",
["zh-cn"] = "数字",
es = "Digital",
ja = "デジタル",
},
show_hud_key = {
en = "Choose key to show HUD",
de = "Taste zum Anzeigen des HUD wählen",
fr = "Choisir une touche pour afficher le HUD",
ru = "Выберите клавишу для показа HUD",
["zh-cn"] = "选择显示 HUD 的按键",
es = "Elige una tecla para mostrar el HUD",
ja = "HUDを表示するキーを選択",
},
hud_x_axis = {
en = "HUD X Axis",
de = "HUD-X-Achse",
fr = "Axe X du HUD",
ru = "Ось X HUD",
["zh-cn"] = "HUD X 轴",
es = "Eje X del HUD",
ja = "HUD X軸",
},
hud_y_axis = {
en = "HUD Y Axis",
de = "HUD-Y-Achse",
fr = "Axe Y du HUD",
ru = "Ось Y HUD",
["zh-cn"] = "HUD Y 轴",
es = "Eje Y del HUD",
ja = "HUD Y軸",
},
manual_clear_key = {
en = "Choose key to clean Lua heap",
de = "Taste zum Bereinigen des Lua-Heaps wählen",
fr = "Choisir une touche pour nettoyer le tas Lua",
ru = "Выберите клавишу для очистки кучи Lua",
["zh-cn"] = "选择清理 Lua 堆的按键",
es = "Elige una tecla para limpiar el heap de Lua",
ja = "Luaヒープをクリーンアップするキーを選択",
},
manual_clear_key_desc = {
en = "{#color(93,101,50)}Manually trigger a full garbage clean.{#reset()}",
de = "{#color(93,101,50)}Eine vollständige Speicherbereinigung manuell auslösen.{#reset()}",
fr = "{#color(93,101,50)}Déclenche manuellement un nettoyage complet de la mémoire.{#reset()}",
ru = "{#color(93,101,50)}Вручную запускает полную очистку мусора.{#reset()}",
["zh-cn"] = "{#color(93,101,50)}手动触发一次完整的垃圾清理。{#reset()}",
es = "{#color(93,101,50)}Activa manualmente una limpieza completa de basura.{#reset()}",
ja = "{#color(93,101,50)}完全なガベージクリーンアップを手動で実行します。{#reset()}",
},
notification_y_axis = {
en = "Notifications - Y Axis",
de = "Benachrichtigungen - Y-Achse",
fr = "Notifications - Axe Y",
ru = "Уведомления - Ось Y",
["zh-cn"] = "通知 - Y 轴",
es = "Notificaciones - Eje Y",
ja = "通知 - Y軸",
},
command_clear_desc = {
en = "Clean Lua heap",
de = "Lua-Heap bereinigen",
fr = "Nettoyer le tas Lua",
ru = "Очистить кучу Lua",
["zh-cn"] = "清理 Lua 堆",
es = "Limpiar el heap de Lua",
ja = "Luaヒープをクリーンアップ",
},
unclean_shutdown = {
en = "Darktide did not close cleanly last time. Lua heap was below SMOG’s warning level.",
de = "Darktide wurde beim letzten Mal nicht ordnungsgemäß beendet. Der Lua-Heap lag unter der Warnstufe von SMOG.",
fr = "Darktide ne s’est pas fermé correctement la dernière fois. Le tas Lua était inférieur au seuil d’alerte de SMOG.",
ru = "В прошлый раз Darktide завершилась некорректно. Куча Lua была ниже уровня предупреждения SMOG.",
["zh-cn"] = "Darktide 上次未正常关闭。Lua 堆低于 SMOG 的警告级别。",
es = "Darktide no se cerró correctamente la última vez. El heap de Lua estaba por debajo del nivel de advertencia de SMOG.",
ja = "前回、Darktideは正常に終了しませんでした。LuaヒープはSMOGの警告レベル未満でした。",
},
cleaning_not_permitted = {
en = "Cleaning not permitted; change in options menu.",
de = "Bereinigung nicht erlaubt; ändere dies im Optionsmenü.",
fr = "Nettoyage non autorisé ; modifiez ce réglage dans le menu des options.",
ru = "Очистка запрещена; измените настройку в меню параметров.",
["zh-cn"] = "不允许清理；请在选项菜单中更改设置。",
es = "La limpieza no está permitida; cambia la opción en el menú.",
ja = "クリーンアップは許可されていません。オプションメニューで変更してください。",
},
cleaned_percent = {
en = "Cleaned %.1f%%",
de = "Bereinigt: %.1f%%",
fr = "Nettoyé : %.1f%%",
ru = "Очищено: %.1f%%",
["zh-cn"] = "已清理 %.1f%%",
es = "Limpiado: %.1f%%",
ja = "%.1f%%クリーンアップ",
},
post_clean_heap_rising = {
en = "Post-clean Lua heap is still rising while full cleaning reclaims very little. Routine full cleans paused.",
de = "Der Lua-Heap steigt nach der Bereinigung weiter an, obwohl eine vollständige Bereinigung nur sehr wenig freigibt. Routinemäßige vollständige Bereinigungen wurden pausiert.",
fr = "Le tas Lua continue d’augmenter après le nettoyage alors qu’un nettoyage complet libère très peu de mémoire. Les nettoyages complets de routine sont suspendus.",
ru = "Куча Lua продолжает расти после очистки, а полная очистка освобождает очень мало памяти. Плановые полные очистки приостановлены.",
["zh-cn"] = "清理后的 Lua 堆仍在增长，而完整清理只能释放很少的内存。已暂停例行完整清理。",
es = "El heap de Lua sigue aumentando después de la limpieza mientras que una limpieza completa recupera muy poca memoria. Las limpiezas completas rutinarias se han pausado.",
ja = "クリーンアップ後もLuaヒープが増え続け、完全クリーンアップで解放される量もごくわずかです。定期的な完全クリーンアップを一時停止しました。",
},
routine_cleaning = {
en = "Routine cleaning...",
de = "Routinemäßige Bereinigung...",
fr = "Nettoyage de routine...",
ru = "Плановая очистка...",
["zh-cn"] = "正在进行例行清理...",
es = "Limpieza rutinaria...",
ja = "定期クリーンアップ中...",
},
heap_remained_above_eighty = {
en = "Heap remained above 80%%. Incremental cleaning...",
de = "Der Lua-Heap blieb über 80%%. Inkrementelle Bereinigung...",
fr = "Le tas Lua est resté au-dessus de 80%%. Nettoyage incrémentiel...",
ru = "Куча Lua осталась выше 80%%. Пошаговая очистка...",
["zh-cn"] = "Lua 堆仍高于 80%%。正在进行增量清理...",
es = "El heap de Lua se mantuvo por encima del 80%%. Limpieza incremental...",
ja = "Luaヒープが80%%を超えたままです。段階的にクリーンアップ中...",
},
heap_increasing_incremental_cleaning = {
en = "Heap remained above 80%%. Increasing incremental cleaning.",
de = "Der Lua-Heap blieb über 80%%. Die inkrementelle Bereinigung wird verstärkt.",
fr = "Le tas Lua est resté au-dessus de 80%%. Intensification du nettoyage incrémentiel.",
ru = "Куча Lua осталась выше 80%%. Пошаговая очистка усилена.",
["zh-cn"] = "Lua 堆仍高于 80%%。正在加强增量清理。",
es = "El heap de Lua se mantuvo por encima del 80%%. Se aumenta la limpieza incremental.",
ja = "Luaヒープが80%%を超えたままです。段階的クリーンアップを強化します。",
},
heap_now_under_eighty = {
en = "Now under 80%%.",
de = "Jetzt unter 80%%.",
fr = "Désormais sous 80%%.",
ru = "Теперь ниже 80%%.",
["zh-cn"] = "现已低于 80%%。",
es = "Ahora por debajo del 80%%.",
ja = "現在は80%%未満です。",
},
heap_growth_spike = {
en = "Heap jumped over 15%% in 30 seconds. Cleaning...",
de = "Der Lua-Heap stieg in 30 Sekunden um mehr als 15%%. Bereinigung...",
fr = "Le tas Lua a augmenté de plus de 15%% en 30 secondes. Nettoyage...",
ru = "Куча Lua выросла более чем на 15%% за 30 секунд. Очистка...",
["zh-cn"] = "Lua 堆在 30 秒内增长超过 15%%。正在清理...",
es = "El heap de Lua aumentó más de un 15%% en 30 segundos. Limpiando...",
ja = "Luaヒープが30秒間で15%%を超えて増加しました。クリーンアップ中...",
},
heap_reached_ninety = {
en = "Heap reached 90%%. Cleaning automatically...",
de = "Der Lua-Heap hat 90%% erreicht. Automatische Bereinigung...",
fr = "Le tas Lua a atteint 90%%. Nettoyage automatique...",
ru = "Куча Lua достигла 90%%. Автоматическая очистка...",
["zh-cn"] = "Lua 堆已达到 90%%。正在自动清理...",
es = "El heap de Lua alcanzó el 90%%. Limpieza automática...",
ja = "Luaヒープが90%%に達しました。自動クリーンアップ中...",
},
warning_eightyfive_key = {
en = "Heap above 85%%: press [%s] urgently.",
de = "Lua-Heap über 85%%: Drücke dringend [%s].",
fr = "Tas Lua supérieur à 85%% : appuyez rapidement sur [%s].",
ru = "Куча Lua выше 85%%: срочно нажмите [%s].",
["zh-cn"] = "Lua 堆高于 85%%：请立即按下 [%s]。",
es = "Heap de Lua por encima del 85%%: pulsa [%s] urgentemente.",
ja = "Luaヒープが85%%を超えています。すぐに[%s]を押してください。",
},
warning_eightyfive_command = {
en = "Heap above 85%%: type /smog urgently.",
de = "Lua-Heap über 85%%: Gib dringend /smog ein.",
fr = "Tas Lua supérieur à 85%% : saisissez rapidement /smog.",
ru = "Куча Lua выше 85%%: срочно введите /smog.",
["zh-cn"] = "Lua 堆高于 85%%：请立即输入 /smog。",
es = "Heap de Lua por encima del 85%%: escribe /smog urgentemente.",
ja = "Luaヒープが85%%を超えています。すぐに/smogを入力してください。",
},
warning_post_ninety_key = {
en = "Automatic cleaning did not lower the heap below 80%%: press [%s] urgently.",
de = "Die automatische Bereinigung hat den Lua-Heap nicht unter 80%% gesenkt: Drücke dringend [%s].",
fr = "Le nettoyage automatique n’a pas ramené le tas Lua sous 80%% : appuyez rapidement sur [%s].",
ru = "Автоматическая очистка не снизила кучу Lua ниже 80%%: срочно нажмите [%s].",
["zh-cn"] = "自动清理未将 Lua 堆降至 80%% 以下：请立即按下 [%s]。",
es = "La limpieza automática no redujo el heap de Lua por debajo del 80%%: pulsa [%s] urgentemente.",
ja = "自動クリーンアップでLuaヒープが80%%未満まで下がりませんでした。すぐに[%s]を押してください。",
},
warning_post_ninety_command = {
en = "Automatic cleaning did not lower the heap below 80%%: type /smog urgently.",
de = "Die automatische Bereinigung hat den Lua-Heap nicht unter 80%% gesenkt: Gib dringend /smog ein.",
fr = "Le nettoyage automatique n’a pas ramené le tas Lua sous 80%% : saisissez rapidement /smog.",
ru = "Автоматическая очистка не снизила кучу Lua ниже 80%%: срочно введите /smog.",
["zh-cn"] = "自动清理未将 Lua 堆降至 80%% 以下：请立即输入 /smog。",
es = "La limpieza automática no redujo el heap de Lua por debajo del 80%%: escribe /smog urgentemente.",
ja = "自動クリーンアップでLuaヒープが80%%未満まで下がりませんでした。すぐに/smogを入力してください。",
},
warning_ninetyfive_hub_key = {
en = "You are likely to crash unless you press [%s] or leave the game.",
de = "Ein Absturz ist wahrscheinlich, wenn du nicht [%s] drückst oder das Spiel verlässt.",
fr = "Un plantage est probable si vous n’appuyez pas sur [%s] ou ne quittez pas le jeu.",
ru = "Вероятен сбой, если вы не нажмёте [%s] или не выйдете из игры.",
["zh-cn"] = "除非按下 [%s] 或退出游戏，否则很可能会崩溃。",
es = "Es probable que el juego se bloquee si no pulsas [%s] o sales del juego.",
ja = "[%s]を押すかゲームを終了しないと、クラッシュする可能性があります。",
},
warning_ninetyfive_hub_command = {
en = "You are likely to crash unless you type /smog or leave the game.",
de = "Ein Absturz ist wahrscheinlich, wenn du nicht /smog eingibst oder das Spiel verlässt.",
fr = "Un plantage est probable si vous ne saisissez pas /smog ou ne quittez pas le jeu.",
ru = "Вероятен сбой, если вы не введёте /smog или не выйдете из игры.",
["zh-cn"] = "除非输入 /smog 或退出游戏，否则很可能会崩溃。",
es = "Es probable que el juego se bloquee si no escribes /smog o sales del juego.",
ja = "/smogを入力するかゲームを終了しないと、クラッシュする可能性があります。",
},
warning_ninetyfive_mission_key = {
en = "You are likely to crash unless you press [%s] or leave the mission.",
de = "Ein Absturz ist wahrscheinlich, wenn du nicht [%s] drückst oder die Mission verlässt.",
fr = "Un plantage est probable si vous n’appuyez pas sur [%s] ou ne quittez pas la mission.",
ru = "Вероятен сбой, если вы не нажмёте [%s] или не покинете миссию.",
["zh-cn"] = "除非按下 [%s] 或离开任务，否则很可能会崩溃。",
es = "Es probable que el juego se bloquee si no pulsas [%s] o abandonas la misión.",
ja = "[%s]を押すかミッションを離脱しないと、クラッシュする可能性があります。",
},
warning_ninetyfive_mission_command = {
en = "You are likely to crash unless you type /smog or leave the mission.",
de = "Ein Absturz ist wahrscheinlich, wenn du nicht /smog eingibst oder die Mission verlässt.",
fr = "Un plantage est probable si vous ne saisissez pas /smog ou ne quittez pas la mission.",
ru = "Вероятен сбой, если вы не введёте /smog или не покинете миссию.",
["zh-cn"] = "除非输入 /smog 或离开任务，否则很可能会崩溃。",
es = "Es probable que el juego se bloquee si no escribes /smog o abandonas la misión.",
ja = "/smogを入力するかミッションを離脱しないと、クラッシュする可能性があります。",
},
}