return {
	mod_description = {
		en = "A single native-widget identity layer: character/account names, total level, launchable and weekly Havoc, and your shared mission record.",
	},
	unknown_player = { en = "Unknown Operative" },
	conflict_warning = { en = "Conflicting identity mod(s) enabled: %s. Disable them and restart Darktide; overlapping hooks can overwrite names and progression." },
	inspection_group = { en = "Inspect Operatives" },
	enable_inspection = { en = "Enable Operative Inspection" },
	enable_inspection_tooltip = { en = "Open Darktide's native read-only character screen for other operatives, including equipped weapons, curios, perks, blessings, cosmetics, talents, and specialization skills." },
	inspect_party_finder = { en = "Inspect in Party Finder" },
	inspect_party_finder_tooltip = { en = "Inspect applicants, listed party members, and members in a group preview. If Inspect From Party Finder is enabled, that mod keeps ownership of this surface to prevent duplicate buttons." },
	inspect_social = { en = "Inspect in Social Menu" },
	inspect_social_tooltip = { en = "Add Inspect Loadout to the player action popup. Offline players without a public character profile remain unavailable." },
	inspect_lobby = { en = "Inspect in Mission Lobby" },
	inspect_lobby_tooltip = { en = "Click an operative card during the pre-mission countdown to inspect that player's complete read-only character screen." },
	inspect_operative = { en = "INSPECT OPERATIVE" },
	inspect_loadout = { en = "Inspect Loadout" },
	inspection_loading = { en = "Retrieving operative profile..." },
	inspection_unavailable = { en = "This operative's loadout is unavailable." },
	inspection_unavailable_reason = { en = "No active character profile is available for this player." },
	inspection_already_open = { en = "Close the current inventory screen before inspecting another operative." },
	identity_group = { en = "Appearance and Identity" },
	progression_group = { en = "Level and Havoc" },
	history_group = { en = "Service History" },
	kit_group = { en = "Class and Kit" },
	surfaces_group = { en = "Display Locations" },
	surface_inherit = { en = "Use the global setting" },
	surface_on = { en = "Always show here" },
	surface_off = { en = "Never show here" },
	team_hud_name_style = { en = "Name Format Here" },
	team_hud_name_style_tooltip = { en = "Which names appear on the team HUD. Use the global setting to follow Name Format." },
	team_hud_platform_icon = { en = "Platform Icon Here" },
	team_hud_platform_icon_tooltip = { en = "Whether the platform icon appears on the team HUD." },
	team_hud_level = { en = "Level Here" },
	team_hud_level_tooltip = { en = "Whether total level (and prestige) appear on the team HUD." },
	team_hud_havoc = { en = "Havoc Here" },
	team_hud_havoc_tooltip = { en = "Whether Havoc ranks appear on the team HUD." },
	team_hud_record = { en = "Service Record Here" },
	team_hud_record_tooltip = { en = "Whether your shared win/loss record appears on the team HUD." },
	team_hud_kit = { en = "Operative Kit Here" },
	team_hud_kit_tooltip = { en = "Whether the class ability appears on the team HUD. Requires Show Operative Kit." },
	nameplates_hub_name_style = { en = "Name Format Here" },
	nameplates_hub_name_style_tooltip = { en = "Which names appear on Mourningstar nameplates. Use the global setting to follow Name Format." },
	nameplates_hub_platform_icon = { en = "Platform Icon Here" },
	nameplates_hub_platform_icon_tooltip = { en = "Whether the platform icon appears on Mourningstar nameplates." },
	nameplates_hub_level = { en = "Level Here" },
	nameplates_hub_level_tooltip = { en = "Whether total level (and prestige) appear on Mourningstar nameplates." },
	nameplates_hub_havoc = { en = "Havoc Here" },
	nameplates_hub_havoc_tooltip = { en = "Whether Havoc ranks appear on Mourningstar nameplates." },
	nameplates_hub_record = { en = "Service Record Here" },
	nameplates_hub_record_tooltip = { en = "Whether your shared win/loss record appears on Mourningstar nameplates." },
	nameplates_hub_kit = { en = "Operative Kit Here" },
	nameplates_hub_kit_tooltip = { en = "Whether the class ability appears on Mourningstar nameplates. Requires Show Operative Kit." },
	nameplates_mission_name_style = { en = "Name Format Here" },
	nameplates_mission_name_style_tooltip = { en = "Which names appear on mission nameplates. Use the global setting to follow Name Format." },
	nameplates_mission_platform_icon = { en = "Platform Icon Here" },
	nameplates_mission_platform_icon_tooltip = { en = "Whether the platform icon appears on mission nameplates." },
	nameplates_mission_level = { en = "Level Here" },
	nameplates_mission_level_tooltip = { en = "Whether total level (and prestige) appear on mission nameplates." },
	nameplates_mission_havoc = { en = "Havoc Here" },
	nameplates_mission_havoc_tooltip = { en = "Whether Havoc ranks appear on mission nameplates." },
	nameplates_mission_record = { en = "Service Record Here" },
	nameplates_mission_record_tooltip = { en = "Whether your shared win/loss record appears on mission nameplates." },
	nameplates_mission_kit = { en = "Operative Kit Here" },
	nameplates_mission_kit_tooltip = { en = "Whether the class ability appears on mission nameplates. Requires Show Operative Kit." },
	lobby_name_style = { en = "Name Format Here" },
	lobby_name_style_tooltip = { en = "Which names appear on the mission lobby. Use the global setting to follow Name Format." },
	lobby_platform_icon = { en = "Platform Icon Here" },
	lobby_platform_icon_tooltip = { en = "Whether the platform icon appears on the mission lobby." },
	lobby_level = { en = "Level Here" },
	lobby_level_tooltip = { en = "Whether total level (and prestige) appear on the mission lobby." },
	lobby_havoc = { en = "Havoc Here" },
	lobby_havoc_tooltip = { en = "Whether Havoc ranks appear on the mission lobby." },
	lobby_record = { en = "Service Record Here" },
	lobby_record_tooltip = { en = "Whether your shared win/loss record appears on the mission lobby." },
	lobby_kit = { en = "Operative Kit Here" },
	lobby_kit_tooltip = { en = "Whether the class ability appears on the mission lobby. Requires Show Operative Kit." },
	party_finder_name_style = { en = "Name Format Here" },
	party_finder_name_style_tooltip = { en = "Which names appear on Party Finder. Use the global setting to follow Name Format." },
	party_finder_platform_icon = { en = "Platform Icon Here" },
	party_finder_platform_icon_tooltip = { en = "Whether the platform icon appears on Party Finder." },
	party_finder_level = { en = "Level Here" },
	party_finder_level_tooltip = { en = "Whether total level (and prestige) appear on Party Finder." },
	party_finder_havoc = { en = "Havoc Here" },
	party_finder_havoc_tooltip = { en = "Whether Havoc ranks appear on Party Finder." },
	party_finder_record = { en = "Service Record Here" },
	party_finder_record_tooltip = { en = "Whether your shared win/loss record appears on Party Finder." },
	party_finder_kit = { en = "Operative Kit Here" },
	party_finder_kit_tooltip = { en = "Whether the class ability appears on Party Finder. Requires Show Operative Kit." },
	chat_name_style = { en = "Name Format Here" },
	chat_name_style_tooltip = { en = "Which names appear on chat. Use the global setting to follow Name Format." },
	chat_platform_icon = { en = "Platform Icon Here" },
	chat_platform_icon_tooltip = { en = "Whether the platform icon appears on chat." },
	chat_level = { en = "Level Here" },
	chat_level_tooltip = { en = "Whether total level (and prestige) appear on chat." },
	chat_havoc = { en = "Havoc Here" },
	chat_havoc_tooltip = { en = "Whether Havoc ranks appear on chat." },
	chat_record = { en = "Service Record Here" },
	chat_record_tooltip = { en = "Whether your shared win/loss record appears on chat." },
	chat_kit = { en = "Operative Kit Here" },
	chat_kit_tooltip = { en = "Whether the class ability appears on chat. Requires Show Operative Kit." },
	combat_feed_name_style = { en = "Name Format Here" },
	combat_feed_name_style_tooltip = { en = "Which names appear on the combat feed. Use the global setting to follow Name Format." },
	combat_feed_platform_icon = { en = "Platform Icon Here" },
	combat_feed_platform_icon_tooltip = { en = "Whether the platform icon appears on the combat feed." },
	combat_feed_level = { en = "Level Here" },
	combat_feed_level_tooltip = { en = "Whether total level (and prestige) appear on the combat feed." },
	combat_feed_havoc = { en = "Havoc Here" },
	combat_feed_havoc_tooltip = { en = "Whether Havoc ranks appear on the combat feed." },
	combat_feed_record = { en = "Service Record Here" },
	combat_feed_record_tooltip = { en = "Whether your shared win/loss record appears on the combat feed." },
	combat_feed_kit = { en = "Operative Kit Here" },
	combat_feed_kit_tooltip = { en = "Whether the class ability appears on the combat feed. Requires Show Operative Kit." },
	menus_name_style = { en = "Name Format Here" },
	menus_name_style_tooltip = { en = "Which names appear on character select and the post-mission lineup. Use the global setting to follow Name Format." },
	menus_platform_icon = { en = "Platform Icon Here" },
	menus_platform_icon_tooltip = { en = "Whether the platform icon appears on character select and the post-mission lineup." },
	menus_level = { en = "Level Here" },
	menus_level_tooltip = { en = "Whether total level (and prestige) appear on character select and the post-mission lineup." },
	menus_havoc = { en = "Havoc Here" },
	menus_havoc_tooltip = { en = "Whether Havoc ranks appear on character select and the post-mission lineup." },
	menus_record = { en = "Service Record Here" },
	menus_record_tooltip = { en = "Whether your shared win/loss record appears on character select and the post-mission lineup." },
	menus_kit = { en = "Operative Kit Here" },
	menus_kit_tooltip = { en = "Whether the class ability appears on character select and the post-mission lineup. Requires Show Operative Kit." },
	social_name_style = { en = "Name Format Here" },
	social_name_style_tooltip = { en = "Which names appear on the social menu. Use the global setting to follow Name Format." },
	social_platform_icon = { en = "Platform Icon Here" },
	social_platform_icon_tooltip = { en = "Whether the platform icon appears on the social menu." },
	social_level = { en = "Level Here" },
	social_level_tooltip = { en = "Whether total level (and prestige) appear on the social menu." },
	social_havoc = { en = "Havoc Here" },
	social_havoc_tooltip = { en = "Whether Havoc ranks appear on the social menu." },
	social_record = { en = "Service Record Here" },
	social_record_tooltip = { en = "Whether your shared win/loss record appears on the social menu." },
	social_kit = { en = "Operative Kit Here" },
	social_kit_tooltip = { en = "Whether the class ability appears on the social menu. Requires Show Operative Kit." },
	spectator_name_style = { en = "Name Format Here" },
	spectator_name_style_tooltip = { en = "Which names appear on the spectator banner. Use the global setting to follow Name Format." },
	spectator_platform_icon = { en = "Platform Icon Here" },
	spectator_platform_icon_tooltip = { en = "Whether the platform icon appears on the spectator banner." },
	spectator_level = { en = "Level Here" },
	spectator_level_tooltip = { en = "Whether total level (and prestige) appear on the spectator banner." },
	spectator_havoc = { en = "Havoc Here" },
	spectator_havoc_tooltip = { en = "Whether Havoc ranks appear on the spectator banner." },
	spectator_record = { en = "Service Record Here" },
	spectator_record_tooltip = { en = "Whether your shared win/loss record appears on the spectator banner." },
	spectator_kit = { en = "Operative Kit Here" },
	spectator_kit_tooltip = { en = "Whether the class ability appears on the spectator banner. Requires Show Operative Kit." },
	show_kit = { en = "Show Operative Kit" },
	show_kit_tooltip = { en = "Show which class ability each operative is running, read from their live talent selection. Where a surface already prints the class on its own row (mission lobby, post-mission lineup, character select) the kit joins that row instead of adding a new one." },
	kit_detail = { en = "Kit Detail" },
	kit_detail_tooltip = { en = "How much of the kit to show. Holding the Expand Identity key always reveals the full kit regardless of this setting." },
	kit_detail_ability = { en = "Class ability only (e.g. Executioner's Stance)" },
	kit_detail_ability_blitz = { en = "Class ability and Blitz" },
	kit_detail_full = { en = "Class ability, Blitz, and Aura" },
	kit_class_name = { en = "Class Label" },
	kit_class_name_tooltip = { en = "How the class itself is labelled where no archetype row already names it. Insignia only is the compact default; Insignia and name matches the game's own archetype format." },
	kit_class_auto = { en = "Insignia only, where not already shown" },
	kit_class_always = { en = "Insignia and name, always" },
	kit_class_never = { en = "No class label" },
	kit_surfaces = { en = "Kit Locations" },
	kit_surfaces_tooltip = { en = "Restrict the kit to in-mission surfaces (team HUD, nameplates, combat feed, chat, spectator) or to out-of-mission surfaces (lobby, post-mission, character select, Party Finder, social)." },
	kit_surfaces_all = { en = "Everywhere" },
	kit_surfaces_mission = { en = "In-mission only" },
	kit_surfaces_menus = { en = "Menus and lobbies only" },
	kit_color_override = { en = "Custom Kit Color" },
	kit_color_override_tooltip = { en = "Use this fixed RGB color for class and kit text instead of the default steel tone." },
	kit_color_r = { en = "Class and Kit Color - Red" },
	kit_color_g = { en = "Class and Kit Color - Green" },
	kit_color_b = { en = "Class and Kit Color - Blue" },
	presentation_style = { en = "Presentation" },
	presentation_style_tooltip = { en = "Choose the complete grammar. Aquila example: Kharvach — oagoz · 535 · 30>34 · 67%%·12." },
	presentation_aquila = { en = "Aquila — tiered and dimmed (new default)" },
	presentation_cogitator = { en = "Cogitator — servo-skull dataslate" },
	presentation_litany = { en = "Litany — gothic devotional" },
	presentation_registry = { en = "Registry — Name // Account [LV | H]" },
	presentation_dossier = { en = "Dossier — LVL // HAVOC" },
	presentation_rail = { en = "Rail — Name | LV | H" },
	presentation_classic = { en = "Classic — L · H" },
	name_style = { en = "Name Format" },
	name_style_tooltip = { en = "Choose character, platform/account, or both. Aquila's combined form is Character — account." },
	style_character_account = { en = "Character and Account" },
	style_account_character = { en = "Account and Character" },
	style_character = { en = "Character only" },
	style_account = { en = "Account only" },
	font_size = { en = "Identity Font Size" },
	font_size_tooltip = { en = "Set the size of identity text in native widgets that expose their font style. 0 keeps each widget's original size. Chat and combat-feed lines retain their native shared text size." },
	colors_group = { en = "Identity Colors" },
	accent_theme = { en = "Accent Theme" },
	accent_theme_tooltip = { en = "Drives separators, labels, platform icons, and first-drop markers. Imperial Gold produces the Aquila example shown in the presentation tooltip." },
	accent_imperial_gold = { en = "Imperial Gold" },
	accent_servo_green = { en = "Servo Green" },
	accent_arterial_red = { en = "Arterial Red" },
	accent_bone_white = { en = "Bone White" },
	accent_player_slot = { en = "Player Slot Color" },
	accent_custom = { en = "Custom RGB" },
	accent_custom_r = { en = "Custom Accent — Red" },
	accent_custom_g = { en = "Custom Accent — Green" },
	accent_custom_b = { en = "Custom Accent — Blue" },
	accent_custom_r_tooltip = { en = "Custom accent red channel, 0–255." },
	accent_custom_g_tooltip = { en = "Custom accent green channel, 0–255." },
	accent_custom_b_tooltip = { en = "Custom accent blue channel, 0–255." },
	dim_account_name = { en = "Dim Account Name" },
	dim_account_name_tooltip = { en = "Fold the account identity behind the brighter character name. The expanded hold always undims it." },
	progression_position = { en = "Progression Placement" },
	progression_position_tooltip = { en = "After name is the default. Before name reverses the order. Second line applies on nameplates and mission-lobby cards." },
	position_after = { en = "After name" },
	position_before = { en = "Before name" },
	position_second_line = { en = "Second line on nameplates and lobby" },
	separator_glyph = { en = "Separator Override" },
	separator_glyph_tooltip = { en = "Auto uses each presentation's own grammar. Fancy glyphs are checked against the live UI font and fall back to ASCII." },
	separator_auto = { en = "Auto (per presentation)" },
	separator_star = { en = "Ornament (fancy dot when the font proves one)" },
	separator_diamond = { en = "Diamond (when the font proves one)" },
	separator_dot = { en = "Middle dot ·" },
	separator_pipe = { en = "Pipe |" },
	separator_dash = { en = "Em dash —" },
	show_platform_icon = { en = "Show Platform Icon" },
	show_platform_icon_tooltip = { en = "Show Darktide's Steam, Xbox, PlayStation, or privacy-safe cross-network glyph." },
	hide_discriminator = { en = "Hide #1234 Discriminator" },
	hide_discriminator_tooltip = { en = "Remove a trailing four-digit account discriminator." },
	deduplicate_names = { en = "Remove Duplicate Names" },
	deduplicate_names_tooltip = { en = "Show a name once when the character and account identities match." },
	max_name_length = { en = "Maximum Name Length" },
	max_name_length_tooltip = { en = "Shorten each individual character/account name with an ellipsis after this many characters." },
	show_self = { en = "Apply to Your Own Operative" },
	show_self_tooltip = { en = "Also format your own name in personal HUD and menu locations." },
	show_own_account_name = { en = "Show Your Own Account Name" },
	show_own_account_name_tooltip = { en = "Off hides your platform/account name and platform icon everywhere while keeping your character name, level, Havoc, and other enabled details visible." },
	expand_identity_key = { en = "Hold to Show Full Identity" },
	expand_identity_key_tooltip = { en = "Temporarily show undimmed account, all enabled Havoc values, and the full W·L·Q service record." },
	cycle_name_style_key = { en = "Cycle Name Format" },
	cycle_name_style_key_tooltip = { en = "Step the Name Format setting through character/account, account/character, character only, and account only." },
	character_color_override = { en = "Custom Character Color" },
	character_color_override_tooltip = { en = "Use this RGB color for character names. When enabled, it takes priority over the normal character color and Color Selection's slot/class color." },
	character_color_r = { en = "Character Color - Red" },
	character_color_g = { en = "Character Color - Green" },
	character_color_b = { en = "Character Color - Blue" },
	account_color_override = { en = "Custom Account Color" },
	account_color_override_tooltip = { en = "Use this RGB color for platform/account names instead of the normal bright or dim account color." },
	account_color_r = { en = "Account Color - Red" },
	account_color_g = { en = "Account Color - Green" },
	account_color_b = { en = "Account Color - Blue" },
	level_color_override = { en = "Custom Total-Level Color" },
	level_color_override_tooltip = { en = "Use this fixed RGB color for total levels instead of Level Tier Colors or the accent color." },
	level_color_r = { en = "Total-Level Color - Red" },
	level_color_g = { en = "Total-Level Color - Green" },
	level_color_b = { en = "Total-Level Color - Blue" },
	havoc_color_override = { en = "Custom Havoc Color" },
	havoc_color_override_tooltip = { en = "Use this fixed RGB color for Havoc values instead of Havoc Heat Colors or the accent color." },
	havoc_color_r = { en = "Havoc Color - Red" },
	havoc_color_g = { en = "Havoc Color - Green" },
	havoc_color_b = { en = "Havoc Color - Blue" },
	history_color_override = { en = "Custom Service-Record Color" },
	history_color_override_tooltip = { en = "Use this fixed RGB color for shared mission records instead of Winrate Tint or the accent color." },
	history_color_r = { en = "Service-Record Color - Red" },
	history_color_g = { en = "Service-Record Color - Green" },
	history_color_b = { en = "Service-Record Color - Blue" },
	steam_color_override = { en = "Custom Steam Icon Color" },
	steam_color_override_tooltip = { en = "Tint the Steam platform icon with this fixed RGB color instead of the accent color." },
	steam_color_r = { en = "Steam Icon Color - Red" },
	steam_color_g = { en = "Steam Icon Color - Green" },
	steam_color_b = { en = "Steam Icon Color - Blue" },
	xbox_color_override = { en = "Custom Xbox Icon Color" },
	xbox_color_override_tooltip = { en = "Tint the Xbox platform icon with this fixed RGB color instead of the accent color." },
	xbox_color_r = { en = "Xbox Icon Color - Red" },
	xbox_color_g = { en = "Xbox Icon Color - Green" },
	xbox_color_b = { en = "Xbox Icon Color - Blue" },
	psn_color_override = { en = "Custom PlayStation Icon Color" },
	psn_color_override_tooltip = { en = "Tint the PlayStation platform icon with this fixed RGB color instead of the accent color." },
	psn_color_r = { en = "PlayStation Icon Color - Red" },
	psn_color_g = { en = "PlayStation Icon Color - Green" },
	psn_color_b = { en = "PlayStation Icon Color - Blue" },
	level_format = { en = "Level Number Format" },
	level_format_tooltip = { en = "How levels past 30 read. Total shows the running level (535); Over-Cap shows it as 30(+505), the way True Level does. Levels at or below 30 read as a plain number in both." },
	level_format_total = { en = "Total (535)" },
	level_format_over_cap = { en = "Over cap (30(+505))" },
	show_prestige = { en = "Show Prestige" },
	show_prestige_tooltip = { en = "Add a prestige tracker: how many complete Level 1-to-30 XP amounts the character has earned (Pr. 12 = reached the cap twelve times over). Its own tracker, so it never replaces the level number." },
	char_select_all_trackers = { en = "All Trackers on Character Select" },
	char_select_all_trackers_tooltip = { en = "Show Havoc (and Prestige, when enabled) on the character-selection cards, not only the level. Off keeps those cards decluttered to character and level." },
	tracker_icons_group = { en = "Tracker Icons" },
	level_icon = { en = "Level Icon" },
	level_icon_tooltip = { en = "Which in-game insignia labels the level tracker. Default is Darktide's level insignia. Only applies with In-Game Insignia on, in the Aquila and Litany presentations." },
	prestige_icon = { en = "Prestige Icon" },
	prestige_icon_tooltip = { en = "Which in-game insignia labels the prestige tracker. Default borrows the level insignia." },
	havoc_icon = { en = "Havoc Icon" },
	havoc_icon_tooltip = { en = "Which in-game insignia labels the Havoc tracker. Default is Darktide's Havoc rank insignia." },
	tracker_icon_default = { en = "Default insignia" },
	tracker_icon_none = { en = "No icon" },
	tracker_icon_level = { en = "Level insignia" },
	tracker_icon_havoc = { en = "Havoc insignia" },
	tracker_icon_veteran = { en = "Veteran class icon" },
	tracker_icon_zealot = { en = "Zealot class icon" },
	tracker_icon_psyker = { en = "Psyker class icon" },
	tracker_icon_ogryn = { en = "Ogryn class icon" },
	tracker_icon_adamant = { en = "Arbitrator class icon" },
	tracker_icon_broker = { en = "Broker class icon" },
	tracker_icon_cryptic = { en = "Cryptic class icon" },
	tracker_icon_operative = { en = "Operative insignia" },
	tracker_icon_companion = { en = "Companion insignia" },
	tracker_icon_penance = { en = "Penance insignia" },
	tracker_icon_credits = { en = "Credits insignia" },
	tracker_icon_marks = { en = "Marks insignia" },
	tracker_icon_aquila = { en = "Aquila insignia" },
	tracker_icon_plasteel = { en = "Plasteel insignia" },
	tracker_icon_diamantine = { en = "Diamantine insignia" },
	tracker_icon_salvage = { en = "Salvage insignia" },
	tracker_icon_loot = { en = "Expedition loot insignia" },
	color_selection_scope = { en = "Color Selection Reach" },
	color_selection_scope_tooltip = { en = "How far a color chosen in the Color Selection mod reaches across one operative. Character name only keeps the current behavior; adding the account name, or the whole line, makes that operative read as a single color on nameplates and the team HUD. Requires the Color Selection mod; without it this setting does nothing." },
	color_selection_scope_character = { en = "Character name only" },
	color_selection_scope_character_account = { en = "Character and account names" },
	color_selection_scope_line = { en = "Whole line (names, separators, icons)" },
	prestige_color_override = { en = "Custom Prestige Color" },
	prestige_color_override_tooltip = { en = "Use this fixed RGB color for the prestige tracker. Off, prestige keeps borrowing the total-level color, including any custom level color." },
	prestige_color_r = { en = "Prestige Color - Red" },
	prestige_color_g = { en = "Prestige Color - Green" },
	prestige_color_b = { en = "Prestige Color - Blue" },
	use_game_icons = { en = "Use In-Game Insignia" },
	use_game_icons_tooltip = { en = "Label level and Havoc values with Darktide's own level and Havoc rank glyphs — the same insignia vanilla nameplates use — instead of text labels. Applies to the Aquila and Litany presentations." },
	show_true_level = { en = "Show Total Level" },
	show_true_level_tooltip = { en = "Calculate levels beyond 30 from cumulative XP and Darktide's live character XP curve." },
	show_level_label = { en = "Show Level Label / Insignia" },
	show_level_label_tooltip = { en = "Off leaves only the colored level number, removing LV, LVL, L, and the level insignia in every presentation. The optional 1000+ flair remains separate." },
	true_level_xp_bar = { en = "True End-of-Mission XP Bar" },
	true_level_xp_bar_tooltip = { en = "The end screen's own XP bar keeps filling and leveling past 30 — 143 to 144 with per-level XP counts — instead of sitting full at the cap. Includes the native level-up sting on rollover." },
	level_tier_colors = { en = "Level Tier Colors" },
	level_tier_colors_tooltip = { en = "1–29 grey, 30–99 bone, 100–249 green, 250–499 blue, 500–749 purple, 750–999 orange, 1000+ red." },
	milestone_flair = { en = "1000+ Milestone Flair" },
	milestone_flair_tooltip = { en = "Append a star marker at total level 1000+. Uses the fancy star only when the live font proves it renders; otherwise *." },
	show_havoc_assignments = { en = "Launchable Havoc Rank" },
	show_havoc_assignments_tooltip = { en = "Exact per-player rank from the Havoc summary route. A ~ prefix marks the temporary presence estimate while loading or backing off." },
	show_havoc_weekly = { en = "Weekly Havoc High" },
	show_havoc_weekly_tooltip = { en = "The second value after the connector. Equal launchable and weekly values collapse to one." },
	show_havoc_all_time = { en = "All-Time Havoc High" },
	show_havoc_all_time_tooltip = { en = "Opt-in third value for historians. Off by default." },
	havoc_heat_colors = { en = "Havoc Heat Colors" },
	havoc_heat_colors_tooltip = { en = "1–15 steel, 16–25 gold, 26–34 orange, 35–39 red, and 40 bright red." },
	collapse_equal_havoc = { en = "Collapse Equal Havoc Values" },
	collapse_equal_havoc_tooltip = { en = "Display H40 instead of H40›40 when adjacent enabled values match." },
	track_history = { en = "Track Missions" },
	track_history_tooltip = { en = "Local only. Reads teammate_tracker_history once at load and keeps appending the same compatible text format." },
	record_style = { en = "Record Style" },
	record_style_tooltip = { en = "Winrate · games produces 67%%·12G. Wins · losses produces 8W·4L. Games only produces ×12." },
	record_winrate_games = { en = "Winrate · games (67%%·12G)" },
	record_wins_losses = { en = "Wins · losses (8W·4L)" },
	record_games = { en = "Games only (×12)" },
	record_min_games = { en = "Minimum Shared Games" },
	record_min_games_tooltip = { en = "Hide the service record until you have completed this many win/loss missions together." },
	show_quits = { en = "Quit Tracking in Expanded View" },
	show_quits_tooltip = { en = "Add ·1Q to the full hold-key record when that player abandoned a recorded mission." },
	first_drop_marker = { en = "First-Drop Marker" },
	first_drop_marker_tooltip = { en = "Tag accounts absent from your imported history with a first drop marker in the mission lobby. Lobby only." },
	winrate_tint = { en = "Winrate Tint" },
	winrate_tint_tooltip = { en = "Below 45%% red, 45–59%% bone, and 60%%+ green. Off uses the accent color." },
	first_drop_short = { en = "first drop" },
	record_command_usage = { en = "Usage: /syn_record <character name>" },
	record_not_found = { en = "No service record found for %s." },
	record_unknown_date = { en = "unknown" },
	team_hud_group = { en = "Team HUD" },
	nameplates_hub_group = { en = "Overhead Nameplates - Mourningstar" },
	nameplates_mission_group = { en = "Overhead Nameplates - Missions" },
	lobby_group = { en = "Mission Lobby" },
	party_finder_group = { en = "Party Finder" },
	chat_group = { en = "Chat" },
	combat_feed_group = { en = "Combat Feed" },
	menus_group = { en = "Character Select and End Screen" },
	social_group = { en = "Social Menu" },
	spectator_group = { en = "Spectator Banner" },
	enable_team_hud = { en = "Enable in Team HUD" },
	enable_team_hud_tooltip = { en = "Format native personal and teammate HUD panels. Service records appear here." },
	team_hud_progression = { en = "Show Progression in Team HUD" },
	team_hud_progression_tooltip = { en = "Show total level, Havoc, and shared service record." },
	enable_nameplates_hub = { en = "Enable on Nameplates" },
	enable_nameplates_hub_tooltip = { en = "Format native overhead names in the Mourningstar." },
	nameplates_hub_progression = { en = "Show Progression on Nameplates" },
	nameplates_hub_progression_tooltip = { en = "Show level and Havoc over players in the Mourningstar." },
	enable_nameplates_mission = { en = "Enable on Nameplates" },
	enable_nameplates_mission_tooltip = { en = "Format native overhead names during missions. Darktide's own Interface option (character nameplates: none / name / name and title) still decides whether overhead names appear at all." },
	nameplates_mission_progression = { en = "Show Progression on Nameplates" },
	nameplates_mission_progression_tooltip = { en = "Show level and Havoc over teammates during a mission. Turn this off for clean names in a fight while the team HUD keeps the full detail." },
	enable_lobby = { en = "Enable in Mission Lobby" },
	enable_lobby_tooltip = { en = "Format native pre-mission operative cards and optional first-drop markers." },
	lobby_progression = { en = "Show Progression in Mission Lobby" },
	lobby_progression_tooltip = { en = "Show level, Havoc, service record, and first-drop status." },
	enable_party_finder = { en = "Enable in Party Finder" },
	enable_party_finder_tooltip = { en = "Format your listed group and incoming Party Finder requests." },
	party_finder_progression = { en = "Show Progression in Party Finder" },
	party_finder_progression_tooltip = { en = "Show level, Havoc, and shared service record." },
	enable_chat = { en = "Enable in Chat" },
	enable_chat_tooltip = { en = "Format sender identity while keeping chat compact." },
	chat_progression = { en = "Show Progression in Chat" },
	chat_progression_tooltip = { en = "Append progression to chat sender names. Off by default." },
	enable_combat_feed = { en = "Enable in Combat Feed" },
	enable_combat_feed_tooltip = { en = "Format player identity while retaining Darktide's native slot color." },
	combat_feed_progression = { en = "Show Progression in Combat Feed" },
	combat_feed_progression_tooltip = { en = "Append progression in combat feed messages. Off by default." },
	enable_menus = { en = "Enable in Character Select and End Screen" },
	enable_menus_tooltip = { en = "Format operative cards and the end-of-mission lineup." },
	menus_progression = { en = "Show Progression in Menus" },
	menus_progression_tooltip = { en = "Show the full-density level, Havoc, and service record." },
	enable_social = { en = "Enable in Social Menu" },
	enable_social_tooltip = { en = "Format the roster's character lines — friends, recent players, and invites. The account row stays vanilla." },
	social_progression = { en = "Show Progression in Social Menu" },
	social_progression_tooltip = { en = "Show total level, Havoc, and your shared service record next to roster entries." },
	enable_spectator = { en = "Enable in Spectator Banner" },
	enable_spectator_tooltip = { en = "Format the native Spectating player label." },
	spectator_progression = { en = "Show Progression in Spectator Banner" },
	spectator_progression_tooltip = { en = "Append level and Havoc while spectating." },
}
