local colours = {
    title = "200,140,20",
    subtitle = "226,199,126",
    text = "169,191,153",
    key = "140,180,220",
}

return {
    custom_hud = {
        en = "Custom HUD",
        ["zh-cn"] = "自定义 HUD",
        ru = "Настраиваемый интерфейс",
    },
    -- Keybind legend lives in the in-editor info panel now, so the settings-page
    -- description is just the author credit.
    custom_hud_description = {
        en = "{#color(" .. colours.subtitle .. ")}Author: Sungrief{#reset()}",
        ["zh-cn"] = "作者：Sungrief",
        ru = "Автор: Sungrief",
    },
    settings_header = {
        en = "{#color(" .. colours.title .. ")}Settings{#reset()}",
        ["zh-cn"] = "设置",
        ru = "Настройки",
    },
    toggle_hud_customization_key = {
        en = "Toggle HUD Customization",
        ["zh-cn"] = "开关 HUD 自定义",
        ru = "Переключение настройки интерфейса",
    },
    toggle_hud_customization_key_description = {
        en = "{#color(" .. colours.text .. ")}Toggles HUD customization on/off.{#reset()}\n\n"
            .. "{#color(" .. colours.title .. ")}Controls (in edit mode):{#reset()}\n"
            .. "{#color(" .. colours.key .. ")}  Click{#color(" .. colours.text .. ")} = Select element\n"
            .. "{#color(" .. colours.key .. ")}  Ctrl+Click{#color(" .. colours.text .. ")} = Multi-select\n"
            .. "{#color(" .. colours.key .. ")}  Shift+Drag{#color(" .. colours.text .. ")} = Move element\n"
            .. "{#color(" .. colours.key .. ")}  Scroll{#color(" .. colours.text .. ")} = Scale element\n"
            .. "{#color(" .. colours.key .. ")}  Alt+Drag edge/corner{#color(" .. colours.text .. ")} = Resize\n"
            .. "{#color(" .. colours.key .. ")}  Alt+Arrows{#color(" .. colours.text .. ")} = Resize ±1px\n"
            .. "{#color(" .. colours.key .. ")}  Arrows{#color(" .. colours.text .. ")} = Move ±1px\n"
            .. "{#color(" .. colours.key .. ")}  Shift+Up/Down{#color(" .. colours.text .. ")} = Z-order\n"
            .. "{#color(" .. colours.key .. ")}  Right-click{#color(" .. colours.text .. ")} = Toggle hidden\n"
            .. "{#color(" .. colours.key .. ")}  Double-click{#color(" .. colours.text .. ")} = Reset to default\n"
            .. "{#color(" .. colours.key .. ")}  Tab{#color(" .. colours.text .. ")} = Reset selected\n"
            .. "{#color(" .. colours.key .. ")}  Ctrl+Shift+C{#color(" .. colours.text .. ")} = Center on screen\n"
            .. "{#color(" .. colours.key .. ")}  Double-click panel row{#color(" .. colours.text .. ")} = Ignore element\n"
            .. "{#color(" .. colours.key .. ")}  Ignore button{#color(" .. colours.text .. ")} = Open ignore list (double-click to restore){#reset()}",
        ["zh-cn"] = "切换 HUD 自定义功能的开关。",
        ru = "Включение/отключение оверлея настройки интерфейса.",
    },
    toggle_hud_hidden_key = {
        en = "Toggle HUD",
        ["zh-cn"] = "开关 HUD",
        ru = "Переключение интерфейса",
    },
    toggle_hud_hidden_key_description = {
        en = "Toggles the HUD on/off.",
        ["zh-cn"] = "切换 HUD 的开关。",
        ru = "Включение/отключение игрового интерфейса.",
    },
    show_info_panel = {
        en = "Show Info Panel",
        ["zh-cn"] = "显示信息面板",
        ru = "Показать информационную панель",
    },
    show_info_panel_description = {
        en = "Show the floating info panel in edit mode. You can also toggle it with the /panel command.",
        ["zh-cn"] = "在编辑模式下显示所有 HUD 元素的位置、大小和状态面板。",
        ru = "Показывает панель со списком всех элементов интерфейса в режиме редактирования.",
    },
    panel_font = {
        en = "Panel Font",
        ["zh-cn"] = "面板字体",
        ru = "Шрифт панели",
    },
    panel_font_description = {
        en = "Choose the font used in the info panel overlay.",
        ["zh-cn"] = "选择信息面板中使用的字体。",
        ru = "Выберите шрифт для информационной панели.",
    },
    font_proxima_nova_bold = {
        en = "Proxima Nova Bold",
    },
    font_proxima_nova_light = {
        en = "Proxima Nova Light",
    },
    font_proxima_nova_medium = {
        en = "Proxima Nova Medium",
    },
    font_machine_medium = {
        en = "Machine Medium",
    },
    font_itc_novarese = {
        en = "ITC Novarese",
    },
    font_friz_quadrata = {
        en = "Friz Quadrata",
    },
    font_rexlia = {
        en = "Rexlia",
    },
    panel_font_size = {
        en = "Panel Font Size",
        ["zh-cn"] = "面板字体大小",
        ru = "Размер шрифта панели",
    },
    panel_font_size_description = {
        en = "Adjust the font size used in the info panel. Detail text is 3pt smaller.",
        ["zh-cn"] = "调整信息面板中使用的字体大小。",
        ru = "Настройте размер шрифта информационной панели.",
    },
    panel_scale = {
        en = "Panel Scale",
    },
    panel_scale_description = {
        en = "Scale the floating info panel, including row spacing and detail area sizing.",
    },
    panel_list_rows = {
        en = "Panel List Rows",
    },
    panel_list_rows_description = {
        en = "Limit how many list entries are shown before the panel starts scrolling.",
    },
    panel_width = {
        en = "Panel Width",
    },
    panel_width_description = {
        en = "Width of the floating info panel in pixels.",
    },
    box_fill_mode = {
        en = "Element Box Fill",
    },
    box_fill_mode_description = {
        en = "How the editor box of each HUD element is filled in edit mode.",
    },
    box_fill_fill = {
        en = "Fill",
    },
    box_fill_none = {
        en = "No Fill (outlines)",
    },

    -- Legend (controls reference) panel
    legend_title = {
        en = "Controls",
        ["zh-cn"] = "操作说明",
        ru = "Управление",
    },
    legend_sec_select = {
        en = "Select",
        ["zh-cn"] = "选择",
        ru = "Выбор",
    },
    legend_sec_move = {
        en = "Move",
        ["zh-cn"] = "移动",
        ru = "Перемещение",
    },
    legend_sec_size = {
        en = "Size / Depth / Scale",
        ["zh-cn"] = "大小 / 深度 / 缩放",
        ru = "Размер / Глубина / Масштаб",
    },
    legend_sec_visibility = {
        en = "Visibility",
        ["zh-cn"] = "可见性",
        ru = "Видимость",
    },
    legend_sec_panel = {
        en = "Panel",
        ["zh-cn"] = "面板",
        ru = "Панель",
    },
    legend_a_select = {
        en = "Select element",
        ["zh-cn"] = "选择元素",
        ru = "Выбрать элемент",
    },
    legend_a_addremove = {
        en = "Add/remove from sel",
        ["zh-cn"] = "添加/移出选择",
        ru = "Добавить/убрать из выбора",
    },
    legend_a_ignore = {
        en = "Ignore element",
        ["zh-cn"] = "忽略元素",
        ru = "Игнорировать элемент",
    },
    legend_a_move = {
        en = "Move selected",
        ["zh-cn"] = "移动所选",
        ru = "Переместить выбранное",
    },
    legend_a_nudge = {
        en = "Nudge (1px or step)",
        ["zh-cn"] = "微调（1px 或步长）",
        ru = "Сдвиг (1px или шаг)",
    },
    legend_a_invertsnap = {
        en = "Invert snapping",
        ["zh-cn"] = "反转吸附",
        ru = "Инвертировать привязку",
    },
    legend_a_center = {
        en = "Center on screen",
        ["zh-cn"] = "屏幕居中",
        ru = "Центрировать на экране",
    },
    legend_a_reset = {
        en = "Reset selected node",
        ["zh-cn"] = "重置所选节点",
        ru = "Сбросить выбранный узел",
    },
    legend_a_resize = {
        en = "Resize",
        ["zh-cn"] = "调整大小",
        ru = "Изменить размер",
    },
    legend_a_resizestep = {
        en = "Resize (1px or step)",
        ["zh-cn"] = "调整大小（1px 或步长）",
        ru = "Размер (1px или шаг)",
    },
    legend_a_zorder = {
        en = "Z-order (1px or step)",
        ["zh-cn"] = "Z 顺序（1px 或步长）",
        ru = "Z-порядок (1px или шаг)",
    },
    legend_a_scale = {
        en = "Scale",
        ["zh-cn"] = "缩放",
        ru = "Масштаб",
    },
    legend_a_hide = {
        en = "Hide from HUD [H]",
        ["zh-cn"] = "从 HUD 隐藏 [H]",
        ru = "Скрыть из HUD [H]",
    },
    legend_a_stash = {
        en = "Stash from edit [S]",
        ["zh-cn"] = "从编辑器收纳 [S]",
        ru = "Убрать из редактора [S]",
    },
    legend_a_movepanel = {
        en = "Move panel",
        ["zh-cn"] = "移动面板",
        ru = "Переместить панель",
    },
    legend_a_scrollrows = {
        en = "Scroll rows",
        ["zh-cn"] = "滚动列表",
        ru = "Прокрутка строк",
    },
    legend_a_edit = {
        en = "Edit, type, Enter",
        ["zh-cn"] = "编辑：输入，回车",
        ru = "Правка: ввод, Enter",
    },
    reset_hud = {
        en = "Reset HUD",
        ["zh-cn"] = "重置 HUD",
        ru = "Сброс интерфейса",
    },
    reset_hud_description = {
        en = "Restore the HUD to Fatshark defaults.",
        ["zh-cn"] = "恢复 HUD 为肥鲨默认值。",
        ru = "Вернуть интерфейс к стандартным настройкам Fatshark.",
    },
    opacity = {
        en = "Opacity Multiplier",
        ["zh-cn"] = "不透明度倍数",
        ru = "Множитель прозрачности",
    },
    opacity_description = {
        en = "Adjust the overall HUD opacity multiplier.",
        ["zh-cn"] = "调整元素不透明度。",
        ru = "Настройте прозрачность элементов.",
    },
    fixed_arrow_move = {
        en = "Fixed Arrow Movement",
        ["zh-cn"] = "固定方向键移动",
        ru = "Фиксированный шаг стрелками",
    },
    fixed_arrow_move_description = {
        en = "When enabled, each arrow-key tap moves the selected element by a fixed number of pixels instead of the default continuous ±1px while held.",
        ["zh-cn"] = "启用后，每次按下方向键将所选元素移动固定的像素数，而不是按住时连续 ±1像素。",
        ru = "Если включено, каждое нажатие стрелки сдвигает выбранный элемент на фиксированное число пикселей вместо непрерывного ±1px при удержании.",
    },
    arrow_move_step = {
        en = "Arrow Step (px)",
        ["zh-cn"] = "方向键步长 (像素)",
        ru = "Шаг стрелки (px)",
    },
    arrow_move_step_description = {
        en = "Number of pixels the element moves per arrow-key tap when Fixed Arrow Movement is enabled.",
        ["zh-cn"] = "启用固定方向键移动时，每次按下方向键元素移动的像素数。",
        ru = "На сколько пикселей сдвигается элемент за одно нажатие стрелки при включённом фиксированном шаге.",
    },
    resize_step = {
        en = "Resize Step (px)",
    },
    resize_step_description = {
        en = "Pixels added/removed per Alt+Arrow tap when Fixed Arrow Movement is enabled.",
    },
    z_step = {
        en = "Z-order Step",
    },
    z_step_description = {
        en = "Depth change per Shift+Up/Down tap when Fixed Arrow Movement is enabled.",
    },
    display_grid = {
        en = "Display Grid",
        ["zh-cn"] = "显示网格",
        ru = "Показать сетку",
    },
    display_grid_description = {
        en = "Toggles display of a customizable grid to aid in repositioning elements.",
        ["zh-cn"] = "开关用于辅助元素定位的可自定义网格。",
        ru = "Переключение отображения настроечной сетки для облегчения изменения положения элементов.",
    },
    snap_to_grid = {
        en = "Snap to Grid",
        ["zh-cn"] = "吸附到网格",
        ru = "Привязка к сетке",
    },
    snap_to_grid_description = {
        en = "Toggles snapping of elements to visible grid lines.",
        ["zh-cn"] = "开关是否将元素吸附到网格线上。",
        ru = "Переключение привязки элементов к видимым линиям сетки.",
    },
    snap_to_elements = {
        en = "Snap to Elements",
    },
    snap_to_elements_description = {
        en = "Toggles snapping to nearby HUD element edges and centers while dragging a single element.",
    },
    grid_cols = {
        en = "Columns",
        ["zh-cn"] = "列",
        ru = "Столбцы",
    },
    grid_rows = {
        en = "Rows",
        ["zh-cn"] = "行",
        ru = "Ряды",
    },
    -- === Editor Colors (grafted 2.1.5) ===
    editor_colors_group = {
        en = "Editor Colors",
        ru = "Цвета редактора",
        ["zh-cn"] = "编辑器颜色",
    },
    editor_colors_fill_group = {
        en = "Box Fill",
    },
    editor_colors_border_top_group = {
        en = "Top Border",
    },
    editor_colors_border_bottom_group = {
        en = "Bottom Border",
    },
    editor_colors_border_left_group = {
        en = "Left Border",
    },
    editor_colors_border_right_group = {
        en = "Right Border",
    },
    editor_color_rect_default = {
        en = "Default",
        ru = "Обычный",
        ["zh-cn"] = "默认",
        ["zh-tw"] = "預設",
        de = "Standard",
        fr = "Par défaut",
        ja = "デフォルト",
        ko = "기본",
        it = "Predefinito",
        pl = "Domyślny",
        es = "Predeterminado",
        ["pt-br"] = "Padrão",
    },
    editor_color_rect_default_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_rect_hovered = {
        en = "Hovered",
        ru = "При наведении",
        ["zh-cn"] = "悬停",
        ["zh-tw"] = "懸停",
        de = "Überfahren",
        fr = "Survolé",
        ja = "ホバー",
        ko = "호버",
        it = "Passaggio del mouse",
        pl = "Najechanie",
        es = "Al pasar el ratón",
        ["pt-br"] = "Ao passar o mouse",
    },
    editor_color_rect_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_rect_hidden = {
        en = "Hidden",
        ru = "Скрытый",
        ["zh-cn"] = "隐藏",
        ["zh-tw"] = "隱藏",
        de = "Ausgeblendet",
        fr = "Masqué",
        ja = "非表示",
        ko = "숨김",
        it = "Nascosto",
        pl = "Ukryty",
        es = "Oculto",
        ["pt-br"] = "Oculto",
    },
    editor_color_rect_hidden_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_rect_hidden_hovered = {
        en = "Hidden hovered",
        ru = "Скрытый при наведении",
        ["zh-cn"] = "隐藏时悬停",
        ["zh-tw"] = "隱藏時懸停",
        de = "Ausgeblendet überfahren",
        fr = "Masqué survolé",
        ja = "非表示ホバー",
        ko = "숨김 호버",
        it = "Nascosto al passaggio",
        pl = "Ukryty po najechaniu",
        es = "Oculto al pasar el ratón",
        ["pt-br"] = "Oculto ao passar o mouse",
    },
    editor_color_rect_hidden_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_top_default = {
        en = "Default",
        ru = "Обычный",
        ["zh-cn"] = "默认",
        ["zh-tw"] = "預設",
        de = "Standard",
        fr = "Par défaut",
        ja = "デフォルト",
        ko = "기본",
        it = "Predefinito",
        pl = "Domyślny",
        es = "Predeterminado",
        ["pt-br"] = "Padrão",
    },
    editor_color_border_top_default_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_top_hovered = {
        en = "Hovered",
        ru = "При наведении",
        ["zh-cn"] = "悬停",
        ["zh-tw"] = "懸停",
        de = "Überfahren",
        fr = "Survolé",
        ja = "ホバー",
        ko = "호버",
        it = "Passaggio del mouse",
        pl = "Najechanie",
        es = "Al pasar el ratón",
        ["pt-br"] = "Ao passar o mouse",
    },
    editor_color_border_top_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_top_hidden = {
        en = "Hidden",
        ru = "Скрытый",
        ["zh-cn"] = "隐藏",
        ["zh-tw"] = "隱藏",
        de = "Ausgeblendet",
        fr = "Masqué",
        ja = "非表示",
        ko = "숨김",
        it = "Nascosto",
        pl = "Ukryty",
        es = "Oculto",
        ["pt-br"] = "Oculto",
    },
    editor_color_border_top_hidden_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_top_hidden_hovered = {
        en = "Hidden hovered",
        ru = "Скрытый при наведении",
        ["zh-cn"] = "隐藏时悬停",
        ["zh-tw"] = "隱藏時懸停",
        de = "Ausgeblendet überfahren",
        fr = "Masqué survolé",
        ja = "非表示ホバー",
        ko = "숨김 호버",
        it = "Nascosto al passaggio",
        pl = "Ukryty po najechaniu",
        es = "Oculto al pasar el ratón",
        ["pt-br"] = "Oculto ao passar o mouse",
    },
    editor_color_border_top_hidden_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_bottom_default = {
        en = "Default",
        ru = "Обычный",
        ["zh-cn"] = "默认",
        ["zh-tw"] = "預設",
        de = "Standard",
        fr = "Par défaut",
        ja = "デフォルト",
        ko = "기본",
        it = "Predefinito",
        pl = "Domyślny",
        es = "Predeterminado",
        ["pt-br"] = "Padrão",
    },
    editor_color_border_bottom_default_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_bottom_hovered = {
        en = "Hovered",
        ru = "При наведении",
        ["zh-cn"] = "悬停",
        ["zh-tw"] = "懸停",
        de = "Überfahren",
        fr = "Survolé",
        ja = "ホバー",
        ko = "호버",
        it = "Passaggio del mouse",
        pl = "Najechanie",
        es = "Al pasar el ratón",
        ["pt-br"] = "Ao passar o mouse",
    },
    editor_color_border_bottom_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_bottom_hidden = {
        en = "Hidden",
        ru = "Скрытый",
        ["zh-cn"] = "隐藏",
        ["zh-tw"] = "隱藏",
        de = "Ausgeblendet",
        fr = "Masqué",
        ja = "非表示",
        ko = "숨김",
        it = "Nascosto",
        pl = "Ukryty",
        es = "Oculto",
        ["pt-br"] = "Oculto",
    },
    editor_color_border_bottom_hidden_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_bottom_hidden_hovered = {
        en = "Hidden hovered",
        ru = "Скрытый при наведении",
        ["zh-cn"] = "隐藏时悬停",
        ["zh-tw"] = "隱藏時懸停",
        de = "Ausgeblendet überfahren",
        fr = "Masqué survolé",
        ja = "非表示ホバー",
        ko = "숨김 호버",
        it = "Nascosto al passaggio",
        pl = "Ukryty po najechaniu",
        es = "Oculto al pasar el ratón",
        ["pt-br"] = "Oculto ao passar o mouse",
    },
    editor_color_border_bottom_hidden_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_left_default = {
        en = "Default",
        ru = "Обычный",
        ["zh-cn"] = "默认",
        ["zh-tw"] = "預設",
        de = "Standard",
        fr = "Par défaut",
        ja = "デフォルト",
        ko = "기본",
        it = "Predefinito",
        pl = "Domyślny",
        es = "Predeterminado",
        ["pt-br"] = "Padrão",
    },
    editor_color_border_left_default_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_left_hovered = {
        en = "Hovered",
        ru = "При наведении",
        ["zh-cn"] = "悬停",
        ["zh-tw"] = "懸停",
        de = "Überfahren",
        fr = "Survolé",
        ja = "ホバー",
        ko = "호버",
        it = "Passaggio del mouse",
        pl = "Najechanie",
        es = "Al pasar el ratón",
        ["pt-br"] = "Ao passar o mouse",
    },
    editor_color_border_left_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_left_hidden = {
        en = "Hidden",
        ru = "Скрытый",
        ["zh-cn"] = "隐藏",
        ["zh-tw"] = "隱藏",
        de = "Ausgeblendet",
        fr = "Masqué",
        ja = "非表示",
        ko = "숨김",
        it = "Nascosto",
        pl = "Ukryty",
        es = "Oculto",
        ["pt-br"] = "Oculto",
    },
    editor_color_border_left_hidden_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_left_hidden_hovered = {
        en = "Hidden hovered",
        ru = "Скрытый при наведении",
        ["zh-cn"] = "隐藏时悬停",
        ["zh-tw"] = "隱藏時懸停",
        de = "Ausgeblendet überfahren",
        fr = "Masqué survolé",
        ja = "非表示ホバー",
        ko = "숨김 호버",
        it = "Nascosto al passaggio",
        pl = "Ukryty po najechaniu",
        es = "Oculto al pasar el ratón",
        ["pt-br"] = "Oculto ao passar o mouse",
    },
    editor_color_border_left_hidden_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_right_default = {
        en = "Default",
        ru = "Обычный",
        ["zh-cn"] = "默认",
        ["zh-tw"] = "預設",
        de = "Standard",
        fr = "Par défaut",
        ja = "デフォルト",
        ko = "기본",
        it = "Predefinito",
        pl = "Domyślny",
        es = "Predeterminado",
        ["pt-br"] = "Padrão",
    },
    editor_color_border_right_default_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_right_hovered = {
        en = "Hovered",
        ru = "При наведении",
        ["zh-cn"] = "悬停",
        ["zh-tw"] = "懸停",
        de = "Überfahren",
        fr = "Survolé",
        ja = "ホバー",
        ko = "호버",
        it = "Passaggio del mouse",
        pl = "Najechanie",
        es = "Al pasar el ratón",
        ["pt-br"] = "Ao passar o mouse",
    },
    editor_color_border_right_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_right_hidden = {
        en = "Hidden",
        ru = "Скрытый",
        ["zh-cn"] = "隐藏",
        ["zh-tw"] = "隱藏",
        de = "Ausgeblendet",
        fr = "Masqué",
        ja = "非表示",
        ko = "숨김",
        it = "Nascosto",
        pl = "Ukryty",
        es = "Oculto",
        ["pt-br"] = "Oculto",
    },
    editor_color_border_right_hidden_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
    editor_color_border_right_hidden_hovered = {
        en = "Hidden hovered",
        ru = "Скрытый при наведении",
        ["zh-cn"] = "隐藏时悬停",
        ["zh-tw"] = "隱藏時懸停",
        de = "Ausgeblendet überfahren",
        fr = "Masqué survolé",
        ja = "非表示ホバー",
        ko = "숨김 호버",
        it = "Nascosto al passaggio",
        pl = "Ukryty po najechaniu",
        es = "Oculto al pasar el ratón",
        ["pt-br"] = "Oculto ao passar o mouse",
    },
    editor_color_border_right_hidden_hovered_alpha = {
        en = "\tTransparency",
        ru = "\tПрозрачность",
        ["zh-cn"] = "\t透明度",
        ["zh-tw"] = "\t透明度",
        de = "\tTransparenz",
        fr = "\tTransparence",
        ja = "\t透明度",
        ko = "\t투명도",
        it = "\tTrasparenza",
        pl = "\tPrzezroczystość",
        es = "\tTransparencia",
        ["pt-br"] = "\tTransparência",
    },
}
