---@diagnostic disable: undefined-global
-- Version 4.7b
-- Thanks to kuli and his Steam guides: https://steamcommunity.com/id/kulii/myworkshopfiles/?section=guides&appid=1361210

local mod = get_mod("Enhanced_descriptions")

--[+ Loading colors of Keywords and Numbers +]--
local COLORS_Numbers = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_Numbers")
local COLORS_KWords = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords")

	--[+ French +]--
local COLORS_KWords_fr = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_fr")
	--[+ Russian +]--
local COLORS_KWords_ru = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_ru")
	--[+ Traditional Chinese +]--
local COLORS_KWords_tw = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_tw")
	--[+ Simplified Chinese +]--
local COLORS_KWords_zh_cn = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_zh_cn")
	--[+ German +]--
-- local COLORS_KWords_de = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_de")
	--[+ Italian +]--
-- local COLORS_KWords_it = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_it")
	--[+ Japanese +]--
-- local COLORS_KWords_ja = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_ja")
	--[+ Korean +]--
-- local COLORS_KWords_ko = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_ko")
	--[+ Polish +]--
-- local COLORS_KWords_pl = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_pl")
	--[+ Portuguese +]--
-- local COLORS_KWords_pt_br = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_pt_br")
	--[+ Spanish +]--
-- local COLORS_KWords_es = mod:io_dofile("Enhanced_descriptions/Colors_Keywords_Numbers/COLORS_KWords_es")


local Dot_red = "{#color(255, 35, 5)}•{#reset()}"
local Dot_nc = "•"
local Dot_green = "{#color(35, 255, 5)}•{#reset()}"

--[+ +FREQUENTLY REPEATED PHRASES+ +]--
local PHRS = {
	-- Doesnt_Stack_Psy_Aura = ""..Dot_red.." This effect does not Stack with the same Aura from another "..COLORS_KWords.cls_psy_rgb..".",
	-- Doesnt_Stack_Psy_eff = ""..Dot_red.." This effect does not Stack with the same debuff from another "..COLORS_KWords.cls_psy_rgb..".",
	-- Can_appl_thr_shlds = ""..Dot_green.." Can be applied through shields.",
	-- Can_be_refr = ""..Dot_green.." Can be refreshed during active duration. ",
	-- Can_be_refr_drop_1 = ""..Dot_green.." Stacks can be refreshed during active duration, and are dropped one by one.",
	-- Can_proc_mult = ""..Dot_green.." Can proc multiple times per swing when "..COLORS_KWords.Cleaving_rgb..".\n",
	-- Cant_appl_thr_shlds = ""..Dot_red.." Can't apply through shields.",
	-- Cant_Crit = ""..Dot_red.." Cannot "..COLORS_KWords.Crit_rgb..".\n",
	-- Carap_cant_cleave = ""..Dot_red.." Carapace armor cannot be "..COLORS_KWords.Cleaved_rgb.." by default.",
	-- Dont_intw_coher_toughn = ""..Dot_nc.." Does not interact with "..COLORS_KWords.Coherency_rgb.." "..COLORS_KWords.Toughness_rgb..".",
	-- Gen_mult_stacks_n_refr = ""..Dot_green.." Can generate multiple Stacks per swing and refresh during active duration. ",
	-- Refr_dur_stappl = ""..Dot_green.." Refreshes duration on Stack application. ",

--[+ +Russian - ЧАСТО ПОВТОРЯЕМЫЕ ФРАЗЫ+ +]--
	-- Doesnt_Stack_Psy_Aura_ru = ""..Dot_red.." Не суммируется с эффектом такой же ауры другого "..COLORS_KWords_ru.cls_psya_rgb_ru..".",
	-- Doesnt_Stack_Psy_eff_ru = ""..Dot_red.." Не суммируется с таким же ослаблением от другого псайкера.",
	-- Can_appl_thr_shlds_ru = ""..Dot_green.." Накладывается через щиты.",
	-- Can_be_refr_ru = ""..Dot_green.." Обновляется во время действия. ",
	-- Can_be_refr_drop_1_ru = ""..Dot_green.." Заряды обновляются во время действия и сбрасываются по одному. ",
	-- Can_proc_mult_ru = ""..Dot_green.." Может срабатывать несколько раз за удар при "..COLORS_KWords_ru.Cleavi_rgb_ru.." нескольких врагов.\n",
	-- Cant_appl_thr_shlds_ru = ""..Dot_red.." Не накладывается через щиты.",
	-- Cant_Crit_ru = ""..Dot_red.." Не наносит "..COLORS_KWords_ru.Crit0_rgb_ru..".\n",
	-- Carap_cant_clv_ru = ""..Dot_red.." Панцирная броня не "..COLORS_KWords_ru.Cleavaetsa_rgb_ru..".",
	-- Carap_cant_cleave_ru = ""..Dot_red.." Панцирная броня не "..COLORS_KWords_ru.Cleaving_etsa_rgb_ru..".",
	-- Dont_intw_coher_toughn_ru = ""..Dot_nc.." Не влияет на "..COLORS_KWords_ru.Tghnss_rgb_ru.." от "..COLORS_KWords_ru.Coherency_rgb_ru..".",
	-- Gen_mult_stacks_n_refr_ru = ""..Dot_green.." Может дать несколько зарядов за удар и обновиться во время действия. ",
	-- Refr_dur_stappl_ru = ""..Dot_green.." Длительность обновляется при наложении заряда. ",
}

--[+ +NOTES+ +]--
local NTS = {
	-- Brtl_note_rgb = ""..Dot_green.." "..COLORS_KWords.Brittleness_rgb.." increases the team's "..COLORS_KWords.Damage_rgb.." to the enemy.",
	-- Fns_note_rgb = ""..Dot_green.." "..COLORS_KWords.Finesse_rgb.." increases "..COLORS_KWords.Weakspot_rgb.." and "..COLORS_KWords.Critical_rgb.." "..COLORS_KWords.Damage_rgb..".",
	-- Impact_note_rgb = ""..Dot_green.." "..COLORS_KWords.Impact_rgb.." increases the effectiveness of "..COLORS_KWords.Stagger_rgb.." on enemies.",
	-- Pwr_note_rgb = ""..Dot_green.." "..COLORS_KWords.Strength_rgb.." increases "..COLORS_KWords.Damage_rgb..", "..COLORS_KWords.Stagger_rgb.." and "..COLORS_KWords.Cleave_rgb..".",
	-- Rend_note_rgb = ""..Dot_green.." "..COLORS_KWords.Rending_rgb.." increases your own "..COLORS_KWords.Damage_rgb..".",
--[+ +Russian - ПРИМЕЧАНИЯ+ +]--
	-- Brtl_note_rgb_ru = ""..Dot_green.." "..COLORS_KWords_ru.Brttlns_rgb_ru.." повышает "..COLORS_KWords_ru.Dmg_rgb_ru.." команды по врагу.",
	-- Fns_note_rgb_ru = ""..Dot_green.." "..COLORS_KWords_ru.Fnss_rgb_ru.." повышает "..COLORS_KWords_ru.Crit_dmg_r_rgb_ru.." и "..COLORS_KWords_ru.Weakspotv_dmg_rgb_ru..".",
	-- Impact_note_rgb_ru = ""..Dot_green.." "..COLORS_KWords_ru.Impact0_rgb_ru.." увеличивает эффективность "..COLORS_KWords_ru.Staggering_rgb_ru.." врагов.",
	-- Pwr_note_rgb_ru = ""..Dot_green.." "..COLORS_KWords_ru.Pwr_rgb_ru.." повышает "..COLORS_KWords_ru.Dmg_rgb_ru..", "..COLORS_KWords_ru.Stagger_rgb_ru.." и "..COLORS_KWords_ru.Cleaving_rgb_ru..".",
	-- Rend_note_rgb_ru = ""..Dot_green.." "..COLORS_KWords_ru.Rndg_rgb_ru.." брони повышает ваш личный "..COLORS_KWords_ru.Dmg_rgb_ru..".",
}


local scum_talent_localizations = {
-- TEMPLATE
	-- ["loc_code"] = {
		-- en = "",
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },


--[+ ++HIVE SCUM - ОТБРОС УЛЬЯ++ +]--
--[+ +BLITZ - БЛИЦ+ +]--
	--[+ BLITZ 0 -  +]--
	-- ["loc___description"] = { -- &->and, +colors
		-- en = "",
		--[+ БЛИЦ 0 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ BLITZ 1 - Blinder +]--
	-- ["loc_talent_veteran_grenade_apply_bleed_desc"] = { -- talent_old: , : , &->and, +colors
		-- en = "An extremely Quick to throw blinding grenade, which "..COLORS_KWords.Staggers_rgb.." enemies.\n"
			-- .."\n"
			-- ..Dot_green.." You can recover Blinder grenades by killing enemies.",
		--[+ БЛИЦ 1 - Ослепитель +]--
		-- ru = "Вы молниеносно бросаете ослепляющую гранату, которая "..COLORS_KWords_ru.Staggers_e_rgb_ru.." врагов.\n"
			-- .."\n"
			-- ..Dot_green.." Вы восстанавливаете "..COLORS_KWords_ru.Blind_greny_rgb_ru.." убивая врагов.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_grenade_apply_bleed"] = { -- talent_old: , : , &->and, +colors
		-- en = "Blinder",
		--[+ БЛИЦ 1 - Ослепитель +]--
		-- ru = "Ослепитель",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ BLITZ 1-1 -  +]--
	-- ["loc_talent__desc"] = { -- talent_name: , : , : , : , s->seconds, +colors
		-- en = "",
		--[+ БЛИЦ 1-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ BLITZ 2 - Boom Bringer +]--
	-- ["loc_talent_ability_krak_grenade_desc"] = { -- +colors
		-- en = "A high powered missile launcher. What else is there to say? For when you really want something dead!",
		--[+ БЛИЦ 2 - Бабахер +]--
		-- ru = "Мощная ракетница. Что ещё тут скажешь, когда очень хочется кого-нибудь умертвить?!",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_ability_krak_grenade"] = { -- +colors
		-- en = "Boom Bringer",
		--[+ БЛИЦ 2 - Бабахер +]--
		-- ru = "Бабахер",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ BLITZ 2-1 -  +]--
	-- ["loc_talent__desc"] = { -- +colors
		-- en = "",
		--[+ БЛИЦ 2-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ BLITZ 3 - Chem Grenade +]--
	-- ["loc_ability_smoke_grenade_description"] = { -- +colors
		-- en = "Throw a canister containing "..COLORS_KWords.Chem_Tox_rgb..", which breaks open and spills its contents across an area when it explodes. Any enemy that enters the lingering toxic cloud will be affected with Stacks of "..COLORS_KWords.Chem_Tox_rgb..".",
		--[+ БЛИЦ 3 - Хим-граната +]--
		-- ru = "Вы бросаете канистру с "..COLORS_KWords_ru.Chem_Toxom_rgb_ru..", которая при взрыве разлетится на куски и разольёт вокруг своё содержимое, распространяя токсичные пары. Любой враг, вошедший в токсичное облако, будет набирать заряды "..COLORS_KWords_ru.Chem_Toxa_rgb_ru..".",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_ability_smoke_grenade"] = { -- +colors
		-- en = "Chem Grenade",
		--[+ БЛИЦ 3 - Хим-граната +]--
		-- ru = "Хим-граната",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ BLITZ 3-1 -  +]--
	-- ["loc_talent__description"] = { -- talent_name: , +colors
		-- en = "",
		--[+ БЛИЦ 3-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
--[+ +AURA - АУРЫ+ +]--
	--[+ AURA 0 -  +]--
	-- ["loc_talent__description"] = { -- : , +colors
		-- en = "",
		--[+ АУРА 0 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ AURA 1 - Gunslinger +]--
	-- ["loc_talent_veteran_elite_kills_grant_ammo_coop_improved_cd_desc"] = { -- : , +colors
		-- en = Dot_green.." When an Ammo pickup is collected by you or your Allies in "..COLORS_KWords.Coherency_rgb..", everyone else in "..COLORS_KWords.Coherency_rgb.." also replenishes a small amount of Ammo.",
		--[+ АУРА 1 - Стрелок +]--
		-- ru = Dot_green.." Когда вы или ваши союзники в "..COLORS_KWords_ru.Coherency_rgb_ru.." подбираете боеприпасы, все остальные союзники в "..COLORS_KWords_ru.Coherency_rgb_ru.." также пополняют небольшое количество боеприпасов.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ AURA 1 - Gunslinger +]--
	-- ["loc_talent_veteran_elite_kills_grant_ammo_coop_improved"] = { -- : , +colors
		-- en = "Gunslinger",
		--[+ АУРА 1 - Стрелок +]--
		-- ru =" Стрелок",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ AURA 2 - Ruffian +]--
	-- ["loc_talent_veteran_damage_coherency_desc"] = { -- : +, talent_name: , +colors
		-- en = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_10_rgb.." Melee "..COLORS_KWords.Damage_rgb.." for you and Allies in "..COLORS_KWords.Coherency_rgb..".",
		--[+ АУРА 2 - Хулиган +]--
		-- ru = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_10_rgb.." к "..COLORS_KWords_ru.Damage_rgb_ru.." в ближнем бою для вас и союзников в "..COLORS_KWords_ru.Coherency_rgb_ru..".",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ AURA 2 - Ruffian +]--
	-- ["loc_talent_veteran_damage_coherency"] = { -- : +, talent_name: , +colors
		-- en = "Ruffian",
		--[+ АУРА 2 - Хулиган +]--
		-- ru = "Хулиган",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ AURA 3 - Anarchist +]--
	-- ["loc_talent_veteran_movement_speed_coherency_desc"] = { -- : , +colors
		-- en = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_5_rgb.." "..COLORS_KWords.Crit_chance_rgb.." for you and Allies in "..COLORS_KWords.Coherency_rgb..".",
		--[+ АУРА 3 - Анархист +]--
		-- ru = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_5_rgb.." к "..COLORS_KWords_ru.Crit_chance_rgb_ru.." для вас и союзников в "..COLORS_KWords_ru.Coherency_rgb_ru..".",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_movement_speed_coherency"] = { -- : , +colors
		-- en = "Anarchist",
		--[+ АУРА 3 - Анархист +]--
		-- ru = "Анархист",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
--[+ +ABILITIES - СПОСОБНОСТИ+ +]--
	--[+ ABILITY 0 -  +]--
	-- ["loc_talent__description"] = { -- : , : , s->seconds, +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 0 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 1 - Desperado +]--
	-- ["loc_talent_veteran_ranged_stance_toughness_description"] = { -- : , : , talent_name: , s->seconds, +colors
		-- en = "Immediately swap to and reload your Ranged Weapon, entering "..COLORS_KWords.Desperado_rgb.." for "..COLORS_Numbers.n_5_rgb.." seconds.\n"
			-- .."\n"
			-- .."During "..COLORS_KWords.Desperado_rgb..", you gain:\n"
			-- ..Dot_green.." Immunity to Ranged Attacks,\n"
			-- ..Dot_green.." Sprinting costs no "..COLORS_KWords.Stamina_rgb..", and\n"
			-- ..Dot_green.." Reloading does not reduce your Ammo Reserve.\n"
			-- .."\n"
			-- ..Dot_green.." Close Ranged Kills extends the duration of "..COLORS_KWords.Desperado_rgb..".",
		--[+ СПОСОБНОСТЬ 1 - Отчаянная атака +]--
		-- ru = "Вы мгновенно экипируете своё оружие дальнего боя, перезаряжаете его и входите в режим "..COLORS_KWords_ru.Desperadki_rgb_ru.." на "..COLORS_Numbers.n_5_rgb.." секунд.\n"
			-- .."\n"
			-- .."Во время режима "..COLORS_KWords_ru.Desperadki_rgb_ru..", вы получаете:\n"
			-- ..Dot_green.." Иммунитет к атакам дальнего боя,\n"
			-- ..Dot_green.." На бег не тратится "..COLORS_KWords_ru.Stamin_rgb_ru..", а\n"
			-- ..Dot_green.." Перезарядка не тратит боеприпасы из резерва.\n"
			-- .."\n"
			-- ..Dot_green.." Убийства в ближнем бою продлевают время действия "..COLORS_KWords_ru.Desperadki_rgb_ru..".",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_combat_ability_elite_and_special_outlines"] = { -- : , : , talent_name: , s->seconds, +colors
		-- en = "Desperado",
		--[+ СПОСОБНОСТЬ 1 -  +]--
		-- ru = "Отчаянная атака",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 1-1 -  +]--
	-- ["loc_talent__description"] = { -- talent_name: , : , : , : , +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 1-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 1-2 -  +]--
	-- ["loc_talent__description"] = { -- talent_name: , : , : , : , s->seconds, +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 1-2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 1-3 -  +]--
	-- ["loc_talent__desc"] = { -- talent_name: , : , : , Stack(s)->Stacks, +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 1-3 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 2 - Rampage! +]--
	-- ["loc_talent_veteran_combat_ability_stagger_nearby_enemies_description"] = { -- : , : , s->seconds
		-- en = "Enter "..COLORS_KWords.Rampage_rgb.." gain for "..COLORS_Numbers.n_5_rgb.." seconds:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_25_rgb.." Melee Attack "..COLORS_KWords.Power_rgb..",\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_25_rgb.." Attack Speed,\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_minus_rgb..COLORS_Numbers.pc_10_rgb.." "..COLORS_KWords.Damage_rgb.." Taken,\n"
			-- ..Dot_green.." Immunity to "..COLORS_KWords.Stuns_rgb..", and\n"
			-- ..Dot_green.." Immunity to Suppression.\n"
			-- .."\n"
			-- ..Dot_green.." Melee attacks extend the duration of "..COLORS_KWords.Rampage_rgb..", although this effect is diminished after "..COLORS_Numbers.n_30_rgb.." seconds.\n"
			-- .."\n"
			-- ..Dot_red.." Exiting "..COLORS_KWords.Rampage_rgb.." leaves you exhausted and vulnerable for a "..COLORS_Numbers.n_10_rgb.." seconds.",
		--[+ СПОСОБНОСТЬ 2 -  +]--
		-- ru = "Вы впадаете в "..COLORS_KWords_ru.Rampage_rgb_ru.." и получаете на "..COLORS_Numbers.n_5_rgb.." секунд:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_25_rgb.." к "..COLORS_KWords_ru.Strength_rgb_ru.." атак ближнего боя,\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_25_rgb.." к скорости атаки,\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_minus_rgb..COLORS_Numbers.pc_10_rgb.." к получаемому "..COLORS_KWords_ru.Damage_rgb_ru..",\n"
			-- ..Dot_green.." Иммунитет к "..COLORS_KWords_ru.Stagger2_rgb_ru..", и\n"
			-- ..Dot_green.." Иммунитет к подавлению.\n"
			-- .."\n"
			-- ..Dot_green.." Атаки ближнего боя продлевают время действия "..COLORS_KWords_ru.Rampaga_rgb_ru..". Этот эффект ослабевает после "..COLORS_Numbers.n_30_rgb.." секунд.\n"
			-- .."\n"
			-- ..Dot_red.." Режим "..COLORS_KWords_ru.Rampaga_rgb_ru.." изматывает вас и, после выхода из него, вы становитесь уязвимым на "..COLORS_Numbers.n_10_rgb.." секунд.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_combat_ability_stagger_nearby_enemies"] = { -- : , : , s->seconds
		-- en = "Rampage!",
		--[+ СПОСОБНОСТЬ 2 -  +]--
		-- ru = "Буйство!",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 2-1 -  +]--
	-- ["loc_talent__description"] = { -- talent_name: , : , : , +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 2-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 2-2 -  +]--
	-- ["loc_talent__description"] = { -- : , : , : , +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 2-2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 2-3 -  +]--
	-- ["loc_talent__desc"] = { -- talent_name: , : , s->seconds
		-- en = "",
		--[+ СПОСОБНОСТЬ 2-3 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 2-4 -  +]--
	-- ["loc_talent__desc"] = { -- talent_name: , : , : , : , s->seconds, +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 2-4 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 3 - Stimm Supply +]--
	-- ["loc_talent_veteran_invisibility_on_combat_ability_damage_desc"] = { -- : , : , s->seconds, +colors
		-- en = "The "..COLORS_KWords.cls_scm_rgb.." has ‘repurposed’ military gadgets to come up with this customized Medical Crate that can be placed down on the ground. This is a supportive Ability that grants nearby Allies the effects of the "..COLORS_KWords.cls_scm2_rgb.." Cartel Special Stimm.",
		--[+ СПОСОБНОСТЬ 3 - Поставки стимов +]--
		-- ru = COLORS_KWords_ru.cls_scm_rgb_ru.." слегка переделал военные гаджеты, создав этот модифицированный медицинский ящик, который можно разместить на земле. Эта поддерживающая способность наделяет ближайших союзников эффектами Особого стимулятора картеля "..COLORS_KWords_ru.cls_scma_rgb_ru..".",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_invisibility_on_combat_ability"] = { -- : , : , s->seconds, +colors
		-- en = "Stimm Supply",
		--[+ СПОСОБНОСТЬ 3 - Поставки стимов +]--
		-- ru = "Поставки стимов",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 3-1 -  +]--
	-- ["loc__description"] = { -- : , talent_name: , : , : , : , s->seconds, +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 3-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 3-2 -  +]--
	-- ["loc__description"] = { -- talent_name: , : 
		-- en = "",
		--[+ СПОСОБНОСТЬ 3-2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 3-3 -  +]--
	-- ["loc__description"] = { -- talent_name: , : , : , +colors
		-- en = "",
		--[+ СПОСОБНОСТЬ 3-3 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ ABILITY 3-4 -  +]--
	-- ["loc_talent__desc"] = { -- talent_name: 
		-- en = "",
		--[+ СПОСОБНОСТЬ 3-4 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
--[+ +KEYSTONES - КЛЮЧЕВЫЕ+ +]--
	--[+ KEYSTONE 1 - Vulture’s Mark +]--
	-- ["loc_talent_veteran_snipers_focus_duration_desc"] = { -- : , : , : , : , +colors
		-- en = "Killing Specials or Elites with a Ranged Weapon gives you Stacks of "..COLORS_KWords.VultsMark_rgb..".\n"
			-- .." For every Stack you gain:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_2_rgb.." Ranged "..COLORS_KWords.Damage_rgb..",\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_2_rgb.." Movement Speed, and\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_33_rgb.." Ranged "..COLORS_KWords.Crit_chance_r_rgb..".\n"
			-- .."\n"
			-- .." At Max Stacks you also replenish:\n"
			-- ..Dot_green.." "..COLORS_Numbers.pc_10_rgb.." "..COLORS_KWords.Toughness_rgb.." for you and Allies in "..COLORS_KWords.Coherency_rgb.." on Ranged Special and Elite kills.",
		--[+ КЛЮЧЕВОЙ 1 - Метка стервятника +]--
		-- ru = "Убийство элитных врагов или специалистов оружием дальнего боя даёт вам заряды "..COLORS_KWords_ru.VultsiMark_rgb_ru..".\n"
			-- .."За каждый заряд вы получаете:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_2_rgb.." к дальнобойному "..COLORS_KWords_ru.Damage_rgb_ru..",\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_2_rgb.." к скорости передвижения, и\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_33_rgb.." к "..COLORS_KWords_ru.Crt_u_chance_rgb_ru..".\n"
			-- .."\n"
			-- .." При максимуме зарядов вы также восстанавливаете:\n"
			-- ..Dot_green.." "..COLORS_Numbers.pc_10_rgb.." "..COLORS_KWords_ru.Toughness_rgb_ru.." для вас и союзников в "..COLORS_KWords_ru.Coherency_rgb_ru.." при убийствах элитных врагов или специалистов оружием дальнего боя.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 1 - Vulture’s Mark +]--
	-- ["loc_talent_veteran_snipers_focus"] = { -- : , : , : , : , +colors
		-- en = "Vulture’s Mark",
		--[+ КЛЮЧЕВОЙ 1 - Метка стервятника +]--
		-- ru = "Метка стервятника",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 1-1 -  +]--
	-- ["loc_talent__desc"] = { -- :  +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 1-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 1-2 -  +]--
	-- ["loc_talent__desc"] = { -- : , : , s->seconds, +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 1-2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 1-3 -  +]--
	-- ["loc_talent__desc"] = { -- : 
		-- en = "",
		--[+ КЛЮЧЕВОЙ 1-3 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 1-4 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 1-4 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 1-5 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 1-5 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 2 - Adrenaline Frenzy +]--
	-- ["loc_talent_veteran_improved_tag_description"] = { -- : , +colors
		-- en = "Melee hits grant Stacks of "..COLORS_KWords.Adren_rgb..", which are lost over time when not attacking.\n"
			-- .."\n"
			-- .." At Max "..COLORS_Numbers.n_20_rgb.." Stacks you lose all Stacks and gain "..COLORS_KWords.AdrenFr_rgb.." for a "..COLORS_Numbers.n_6_rgb.." seconds which gives you per Stack:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_1_rgb.." Attack Speed and\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_1_rgb.." Melee "..COLORS_KWords.Damage_rgb..".",
		--[+ КЛЮЧЕВОЙ 2 - Адреналиновое безумие +]--
		-- ru =  "Атаки ближнего боя дают вам заряды "..COLORS_KWords_ru.Adren_rgb_ru..", которые расходуются со временем, если вы не атакуете врага.\n"
			-- .."\n"
			-- .."Набрав максимальные "..COLORS_Numbers.n_20_rgb.." зарядов, вы тратите все заряды и получаете "..COLORS_KWords_ru.AdrenFr_rgb_ru.." на "..COLORS_Numbers.n_6_rgb.." секунд, которое даёт вам за заряд:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_1_rgb.." к скорости атаки и\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_1_rgb.." к "..COLORS_KWords_ru.Damage_rgb_ru.." в ближнем бою.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_improved_tag"] = { -- : , +colors
		-- en = "Adrenaline Frenzy",
		--[+ КЛЮЧЕВОЙ 2 - Адреналиновое безумие +]--
		-- ru =  "Адреналиновое безумие",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 2-1 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 2-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 2-2 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 2-2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 2-3 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 2-3 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 2-4 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 2-4 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 3 - Chemical Dependency +]--
	-- ["loc_talent_veteran_weapon_switch_new_description"] = { -- : , +colors
		-- en = "Using a Stimm grants a Stack of "..COLORS_KWords.Depend_rgb.." for "..COLORS_Numbers.n_20_rgb.." seconds. Each Stack grants:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_minus_rgb..COLORS_Numbers.pc_1_rgb.." "..COLORS_KWords.Ability_cd_rgb..", up to "..COLORS_Numbers.n_minus_rgb..COLORS_Numbers.pc_10_rgb..".",
		--[+ КЛЮЧЕВОЙ 3 - Зависимость от химии - Химическая зависимость +]--
		-- ru = "Использование стима даёт заряд "..COLORS_KWords_ru.Depend_rgb_ru.." на "..COLORS_Numbers.n_20_rgb.." секунд. Каждый заряд даёт:\n"
			-- ..Dot_green.." "..COLORS_Numbers.n_minus_rgb..COLORS_Numbers.pc_1_rgb.." "..COLORS_KWords_ru.Ability_cd_rgb_ru..", вплоть до "..COLORS_Numbers.n_minus_rgb..COLORS_Numbers.pc_10_rgb..".",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_weapon_switch"] = { -- : , +colors
		-- en = "Chemical Dependency",
		--[+ КЛЮЧЕВОЙ 3 - Зависимость от химии - Химическая зависимость +]--
		-- ru = "Зависимость от химии",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 3-1 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 3-1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 3-2 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 3-2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 3-3 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 3-3 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ KEYSTONE 3-4 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ КЛЮЧЕВОЙ 3-4 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
--[+ +PASSIVES - ПАССИВНЫЕ+ +]--
	--[+ Passive 1 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ Пассивный 1 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	--[+ Passive 2 -  +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

--[+ Passive  - In Your Face +]--
	-- ["loc_talent_veteran_increased_damage_based_on_range_new_desc"] = { -- : , +colors
		-- en = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_10_rgb.." Ranged "..COLORS_KWords.Damage_rgb.." at a distance within "..COLORS_Numbers.n_12_5_rgb.." meters, which is further increased for a short while after Reloading.",
		--[+ Пассивный 2 - Прямо в харю - Прямо в лицо +]--
		-- ru = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_10_rgb.." к "..COLORS_KWords_ru.Damage_rgb_ru.." в дальнем бою на расстоянии до "..COLORS_Numbers.n_12_5_rgb.." метров. Эффект усиливается на некоторое время после перезарядки.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_increased_damage_based_on_range"] = { -- : , +colors
		-- en = "In Your Face",
		--[+ Пассивный 2 - Прямо в харю - Прямо в лицо +]--
		-- ru = "Прямо в харю",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

--[+ Passive  - Like the Wind +]--
	-- ["loc_talent_veteran_movement_bonus_on_toughness_broken_desc"] = { -- : , +colors
		-- en = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_33_rgb.." Sprint Dodge Angle.\n"
			-- ..Dot_green.." You can Sprint Dodge even without "..COLORS_KWords.Stamina_rgb..".",
		-- [+ Пассивный 2 - Словно ветер +]--
		-- ru = Dot_green.." "..COLORS_Numbers.n_plus_rgb..COLORS_Numbers.pc_33_rgb.." к углу уклонения.\n"
			-- ..Dot_green.." Вы можете уклоняться даже если ваш уровень "..COLORS_KWords_ru.Stamina_rgb_ru.." на нуле.",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },
	-- ["loc_talent_veteran_movement_bonus_on_toughness_broken"] = { -- : , +colors
		-- en = "Like the Wind",
		--[+ Пассивный 2 - Словно ветер +]--
		-- ru = "Словно ветер",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

--[+ Passive  - Nimble +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = Dot_green.." Dodges move farther and last longer.",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

--[+ Passive  - Hyper-Violence +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = Dot_green.." +X% Melee "..COLORS_KWords.Damage_rgb.." based on amount of overkill "..COLORS_KWords.Damage_rgb..", upon Melee kill.",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

--[+ Passive  - Blessed Stimms +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = Dot_green.." While Stimmed, killing blows clear some "..COLORS_KWords.Corruption_rgb..".",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

--[+ Passive  - Targeted Toxin +]--
	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = Dot_green.." -X% "..COLORS_KWords.Damage_rgb.." Dealt by Enemies infected with your Chem Toxin.\n"
			-- ..Dot_green.." Increased effect on Monsters.",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },

	-- ["loc_talent__desc"] = { -- : , +colors
		-- en = "",
		--[+ Пассивный 2 -  +]--
		-- ru = "",
		-- fr = "",
		-- ["zh-tw"] = "",
		-- ["zh-cn"] = "",
		-- de = "",
		-- it = "",
		-- ja = "",
		-- ko = "",
		-- pl = "",
		-- ["pt-br"] = "",
		-- es = "",
	-- },


}

-- mod:notify("TALENTS_Hive_Scum.lua loaded successfully")

return scum_talent_localizations
