local mod = get_mod("HavocQuickplay")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "hq_auto_accept",
				type = "checkbox",
				default_value = true,
				title = "hq_auto_accept",
				tooltip = "hq_auto_accept_desc",
			},
			{
				setting_id = "hq_auto_decline",
				type = "checkbox",
				default_value = true,
				title = "hq_auto_decline",
				tooltip = "hq_auto_decline_desc",
			},
			{
				setting_id = "hq_auto_accept_mission",
				type = "checkbox",
				default_value = false,
				title = "hq_auto_accept_mission",
				tooltip = "hq_auto_accept_mission_desc",
			},
			{
				setting_id = "hq_auto_start",
				type = "checkbox",
				default_value = false,
				title = "hq_auto_start",
				tooltip = "hq_auto_start_desc",
			},
			{
				setting_id = "hq_cancel_keybind",
				type = "keybind",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "cancel_queue_keybind",
				title = "hq_cancel_keybind",
			},
			{
				setting_id = "hq_disable_bl_button",
				type = "checkbox",
				default_value = false,
				title = "hq_disable_bl_button",
				tooltip = "hq_disable_bl_button_desc",
			},
			{
				setting_id = "hq_blacklist_minutes",
				type = "numeric",
				default_value = 5,
				range = { 3, 60 },
				step_size_value = 1,
				decimals_number = 0,
				title = "hq_blacklist_minutes",
			},
			{
				setting_id = "hq_rank_group",
				type = "group",
				title = "hq_rank_group",
				sub_widgets = {
					{
						setting_id = "hq_min_rank",
						type = "numeric",
						default_value = 1,
						range = { 1, 40 },
						step_size_value = 1,
						decimals_number = 0,
						title = "hq_min_rank",
						tooltip = "hq_rank_desc",
					},
					{
						setting_id = "hq_max_rank",
						type = "numeric",
						default_value = 40,
						range = { 1, 40 },
						step_size_value = 1,
						decimals_number = 0,
						title = "hq_max_rank",
						tooltip = "hq_rank_desc",
					},
				},
			},
			{
				setting_id = "hq_refresh_interval",
				type = "numeric",
				default_value = 30,
				range = { 10, 120 },
				step_size_value = 5,
				decimals_number = 0,
				title = "hq_refresh_interval",
				tooltip = "hq_refresh_interval_desc",
			},
			{
				setting_id = "hq_debug",
				type = "checkbox",
				default_value = false,
				title = "hq_debug",
				tooltip = "hq_debug_desc",
			},
		},
	},
}
