local mod = get_mod("NoBrainer")

return {
	mod_name           = { en = "No Brainer" },
	mod_description    = { en = "Automates and enhances all Darktide minigames: Decode Symbols, Decode Search, Expedition Map, Auspex Scan, Train Balance, Tree Drill, and Frequency Matching." },
	enable_debug_messages = { en = "Debug messages" },
	enable_debug_messages_tooltip = { en = "Prints NoBrainer minigame debug messages to chat. Leave disabled unless diagnosing a problem." },

	decode_symbols_group      = { en = "Decode Symbols" },
	enable_decode_highlight   = { en = "Highlight Solution" },
	enable_decode_highlight_tooltip = { en = "Highlights the correct columns for upcoming rows." },
	enable_decode_auto        = { en = "Auto-Solve" },
	enable_decode_auto_tooltip = { en = "Automatically press interact when the cursor is on target. Reliable in testing up to ~265ms ping." },

	matching_group            = { en = "Decode Search (Matching)" },
	enable_matching              = { en = "Highlight Match" },
	enable_matching_tooltip      = { en = "Highlights the region on the board that matches the target pattern." },
	enable_expedition_auto_solve       = { en = "Auto-Solve" },
	enable_expedition_auto_solve_tooltip = { en = "Automatically moves the cursor to the target and submits." },
	expedition_solve_speed             = { en = "Auto-Solve Speed" },
	expedition_solve_speed_tooltip     = { en = "Auto-solve cursor speed (1=slow, 10=instant). At low speeds the cursor takes longer between moves." },

	scan_group                = { en = "Auspex Scan" },
	enable_scan               = { en = "Mark Scannable Objects" },
	enable_scan_tooltip       = { en = "Applies outline and highlight to scannable objects during auspex scanning." },
	enable_auto_scan          = { en = "Auto-Scan" },
	enable_auto_scan_tooltip  = { en = "Automatically holds the scan action when close enough for the 1 second scan." },

	balance_group             = { en = "Train (Balance)" },
	enable_balance            = { en = "Auto-Balance" },
	enable_balance_tooltip    = { en = "Automatically steers the dot toward the center." },
	balance_solve_speed             = { en = "Auto-Balance Speed" },
	balance_solve_speed_tooltip     = { en = "Balance correction speed (1=slow with lag/delays, 10=instant precise corrections)." },

	frequency_group                       = { en = "Frequency Matching" },
	enable_frequency_highlight            = { en = "Show Directional Arrows" },
	enable_frequency_highlight_tooltip    = { en = "Displays orange arrows indicating which direction to push the waveform toward the target." },
	enable_frequency_auto                 = { en = "Auto-Solve" },
	enable_frequency_auto_tooltip         = { en = "Automatically steers the waveform toward the target and submits when aligned." },
	frequency_solve_speed                 = { en = "Auto-Solve Speed" },
	frequency_solve_speed_tooltip         = { en = "Waveform steering speed (1=slow with wobble, 10=instant precise corrections)." },

	drill_group               = { en = "Tree (Drill)" },
	enable_drill              = { en = "Highlight Correct Target" },
	enable_drill_tooltip      = { en = "Shows which node is the correct one by highlighting it white." },
	enable_drill_auto         = { en = "Auto-Solve" },
	enable_drill_auto_tooltip = { en = "Automatically moves to the correct node and submits." },
	drill_solve_speed         = { en = "Auto-Solve Speed" },
	drill_solve_speed_tooltip = { en = "Drill cursor speed (1=slow, 10=instant). At low speeds the cursor takes longer between moves." },

	expedition_group               = { en = "Expedition maps" },
	enable_expedition_automark     = { en = "Automatically mark points of interest (POI)" },
	enable_expedition_automark_tooltip = { en = "Automatically marks the nearest opportunity on the expedition map without needing to pull out the auspex. Manual marking overrides auto-marking." },
	expedition_automark_silent     = { en = "Disable notifications" },
	expedition_automark_silent_tooltip = { en = "Suppress chat messages when a POI is auto-marked." },
	enable_expedition_automark_vault     = { en = "Always mark the Vault automatically when all POI are finished" },
	enable_expedition_automark_vault_tooltip = { en = "When all opportunities are completed, automatically mark the nearest exit/vault." },

	practice_group                    = { en = "Practice Mode" },
	enable_practice                   = { en = "Enable Practice Mode" },
	enable_practice_tooltip           = { en = "Opens a standalone minigame overlay for practice. Only available in the Mourningstar and Psykanium. Auto-solvers are enabled if the corresponding settings are active above." },
	practice_type                     = { en = "Minigame Type" },
	practice_type_tooltip             = { en = "Which minigame to practice." },
	practice_type_decode_symbols      = { en = "Decode Symbols" },
	practice_type_decode_search       = { en = "Decode Search" },
	practice_type_drill               = { en = "Tree Drill" },
	practice_type_frequency           = { en = "Frequency Matching" },
	practice_type_balance             = { en = "Train Balance" },
	practice_toggle_key               = { en = "Toggle Practice" },
	practice_toggle_key_tooltip       = { en = "Hotkey to open/close the practice minigame overlay." },
	practice_opened                   = { en = "Practice mode: %s" },
	practice_completed                = { en = "Practice completed!" },
	practice_not_allowed              = { en = "Practice mode can only be used in the Mourningstar or Psykanium." },

}
