local localization = {
	mod_name = "BetterInventory",
	mod_description = "为《暗潮》提供响应式且完整保留信息的库存布局。",
	automatic_curio_buyer_group = "自动珍品购买器",
	enable_automatic_curio_acquisition = "启用自动获取珍品",
	enable_automatic_curio_acquisition_tooltip = "每次进入符合条件的界面后，对所有角色的军械库交易所执行一次扫描，并自动购买符合物品等级、主要属性数值、类型和目标筛选条件的所有珍品。哀星号使用现有购买器设置；干员选择界面需要单独启用。目标可按职业或单个角色选择。此功能会在没有确认提示的情况下花费审判庭双子币。自动丢弃会先完成，且符合获取规则的珍品会在以后的自动丢弃流程中保持受保护状态。",
	automatic_curio_scan_operative_selection = "从干员选择界面扫描并购买",
	automatic_curio_scan_operative_selection_tooltip = "允许自动珍品购买器在干员选择界面打开时运行。默认关闭。它仍会遵守商店轮换限制，也不需要哀星号中的已选玩家。",
	automatic_curio_once_per_store_rotation = "每次商店轮换最多扫描一次",
	automatic_curio_once_per_store_rotation_tooltip = "启用后，哀星号和干员选择界面共享一个按账户保存的军械库轮换限制。17:06 扫描后，商店在 18:00 刷新后才能再次扫描；这不是滚动 60 分钟计时器。默认关闭。",
	automatic_curio_rescan_on_store_refresh = "闲置时商店刷新后重新扫描",
	automatic_curio_rescan_on_store_refresh_tooltip = "启用后，如果你仍停留在符合条件的界面，军械库商店刷新后会额外执行一次扫描。刷新前刚扫描可能导致刷新后再次扫描。默认关闭，以限制后端请求和短时间内的连续购买。",
	automatic_curio_min_item_level = "获取珍品的最低物品等级",
	automatic_curio_min_item_level_tooltip = "只有显示物品等级达到或超过此值的军械库珍品才符合条件。生命和韧性珍品还必须达到对应的最低主要属性数值。货币充足时，会购买每个已启用目标的所有匹配商品。默认值为 410。",
	automatic_curio_diagnostic_logging = "启用详细诊断日志",
	automatic_curio_diagnostic_logging_tooltip = "在每次哀星号单次扫描期间，将每个角色、每件珍品和重新验证的详细信息写入《暗潮》的共享会话日志。默认关闭以尽量减少磁盘日志增长；错误仍会记录。",
	automatic_curio_disable_no_eligible_notification = "未找到符合条件的珍品时禁用通知",
	automatic_curio_disable_no_eligible_notification_tooltip = "当没有珍品符合当前筛选条件时，隐藏自动珍品购买器通知。购买、资金不足和失败通知不受影响。",
	automatic_curio_types_group = "我们正在寻找的珍品类型：",
	automatic_curio_buy_health = "生命",
	automatic_curio_min_health = "最低生命值 (%%)",
	automatic_curio_min_health_tooltip = "生命珍品必须同时达到此主要属性阈值和最低物品等级。比较包含等于阈值的情况。默认值为 21%%。",
	automatic_curio_buy_toughness = "韧性",
	automatic_curio_min_toughness = "最低韧性值 (%%)",
	automatic_curio_min_toughness_tooltip = "韧性珍品必须同时达到此主要属性阈值和最低物品等级。比较包含等于阈值的情况。默认值为 17%%。",
	automatic_curio_buy_stamina = "体力",
	automatic_curio_buy_wounds = "伤口",
	automatic_curio_classes_group = "要获取珍品的职业：",
	automatic_curio_class_veteran = "老兵",
	automatic_curio_class_zealot = "狂信徒",
	automatic_curio_class_psyker = "灵能者",
	automatic_curio_class_ogryn = "欧格林",
	automatic_curio_class_adamant = "法务官",
	automatic_curio_class_broker = "巢都渣滓",
	automatic_curio_class_cryptic = "护教军",
	option_requires_automatic_curio_acquisition = "需要启用自动获取珍品。",
	option_requires_automatic_curio_classes_mode = "请选择职业作为珍品获取目标模式。",
	option_requires_automatic_curio_characters_mode = "请选择角色作为珍品获取目标模式。",
	option_requires_automatic_curio_health = "需要启用生命珍品。",
	option_requires_automatic_curio_toughness = "需要启用韧性珍品。",
	automatic_curio_buyer_inventory_label = "自动珍品购买器",
	automatic_curio_types_inventory_label = "我们正在寻找的珍品类型：",
	automatic_curio_classes_inventory_label = "要获取珍品的职业：",
	automatic_curio_health = "生命",
	automatic_curio_toughness = "韧性",
	automatic_curio_stamina = "体力",
	automatic_curio_wounds = "伤口",
	automatic_curio_purchased_title = "自动珍品购买器 - 已购买珍品：",
	automatic_curio_insufficient_title = "自动珍品购买器 - 以下珍品的审判庭双子币不足：",
	automatic_curio_currency_spent_label = "已花费：",
	automatic_curio_none_title = "未找到符合条件的珍品",
	automatic_curio_none_description = "哀星号军械库扫描未找到符合当前自动购买筛选条件的珍品。",
	automatic_curio_failed_title = "自动珍品购买器未能完成",
	automatic_curio_failed_description = "无法验证军械库或钱包后端。失败或结果不明确的购买不会被自动重试。",
	automatic_curio_partial_failure = "- 后端验证失败后，剩余购买队列已停止。",
	inventory_slots_group = "适用库存",
	inventory_sorting_group = "库存排序",
	show_inventory_options_widget = "显示库存选项组件",
	show_inventory_options_widget_tooltip = "在近战、远程和珍品库存中显示 BetterInventory 的排序和物品管理组件。关闭后会隐藏可扩展面板及紧凑备用控件，但不会更改已保存的设置。",
	prioritize_equipped_favorites = "已装备和收藏物品置顶",
	prioritize_equipped_favorites_tooltip = "在近战、远程和珍品库存中，将已装备物品置于最前，收藏物品置于其后，同时仍由所选的原生排序方式排列各组。同步开关显示在珍品详情或武器操作按钮下方，并会在游戏会话间保存。",
	prioritize_perfect_roll_weapons = "完美属性武器置顶",
	prioritize_perfect_roll_weapons_tooltip = "将四项属性为 80、第五项为 60 或更高的武器置于普通物品之前。已装备和收藏物品仍拥有更高优先级。库存内的复选框位于可缩放面板中。",
	prioritize_perfect_roll_weapons_inventory_label = "完美属性武器置顶",
	inventory_options_panel_geometry_group = "库存选项面板",
	curio_information_width_percent = "珍品信息窗口宽度(%%)",
	curio_preview_height_percent = "珍品预览区域高度 (%%)",
	curio_preview_height_percent_tooltip = "将上部珍品预览区域及其物品艺术一起缩放以保留原始宽高比。更改后重新打开库存。",
	inventory_options_panel_width = "选项面板宽度 (px)",
	inventory_options_panel_max_height = "选项面板最大高度 (px)",
	inventory_options_panel_row_spacing = "选项面板行距（px）",
	inventory_options_panel_padding_top = "选项面板顶部内边距 (px)",
	inventory_options_panel_padding_bottom = "选项面板底部填充（px）",
	inventory_options_panel_padding_left = "选项面板左内边距 (px)",
	inventory_options_panel_padding_right = "选项面板右内边距 (px)",
	inventory_options_geometry_reopen_tooltip = "库存选项面板几何形状。更改此值后重新打开库存。",
	prioritize_equipped_favorites_inventory_label = "装备和收藏的物品位于顶部",
	inventory_sorting_inventory_label = "排序",
	armoury_native_sorting_header = "Darktide 原生排序",
	inventory_discard_management_inventory_label = "手动/自动物品丢弃管理",
	inventory_manual_discard_management_inventory_label = "手动物品丢弃管理",
	inventory_automated_discard_management_inventory_label = "自动物品丢弃管理",
	experimental_quick_discard_group = "手动/自动物品丢弃管理",
	enable_experimental_quick_discard = "在库存中显示快速丢弃控件",
	enable_experimental_quick_discard_tooltip = "重新打开库存后，在库存排序开关下方添加选择加入丢弃管理控件。手动模式仍为默认模式。",
	quick_discard_mode = "丢弃模式",
	quick_discard_mode_tooltip = "手动模式仅在按下库存按钮并确认后丢弃物品。自动模式会在每次进入哀星号并等待五秒就绪后执行一次受保护的清理。两种模式均保留手动按钮。",
	quick_discard_mode_manual = "手动",
	quick_discard_mode_automatic = "自动",
	quick_discard_skip_automatic_confirmation = "跳过确认提示",
	quick_discard_skip_automatic_confirmation_tooltip = "仅用于自动模式。启用后，每次进入哀星号时的清理会直接永久丢弃当前所有符合条件的物品，不再询问。库存中的手动按钮始终保留确认提示。",
	quick_discard_rarity = "丢弃稀有度阈值",
	quick_discard_rarity_tooltip = "仅考虑此稀有度或以下的物品。库存中的紧凑选择器循环使用相同的保存值。",
	quick_discard_rarity_1 = "亵渎",
	quick_discard_rarity_2 = "救赎",
	quick_discard_rarity_3 = "圣膏",
	quick_discard_rarity_4 = "崇高",
	quick_discard_rarity_5 = "超凡",
	quick_discard_max_item_level = "可丢弃的最高物品等级",
	quick_discard_max_item_level_tooltip = "即使稀有度符合条件，显示物品等级高于此值的物品仍会受到保护。测试此功能时请谨慎设置。",
	quick_discard_protect_above_equipped_level = "不丢弃物品等级高于已装备物品的装备",
	quick_discard_protect_above_equipped_level_tooltip = "如果物品的显示等级高于当前配置及所有已保存配装中同类别已装备物品的最高等级，则保护该物品。近战武器、远程武器和珍品分别比较。",
	quick_discard_include_melee = "允许近战武器",
	quick_discard_include_ranged = "允许远程武器",
	quick_discard_include_curios = "允许珍品",
	quick_discard_protect_perfect_weapons = "不要丢弃完美属性武器",
	quick_discard_protect_perfect_weapons_tooltip = "保护当前已有或经《暗潮》最高专精预览后预计会达到四项显示属性为 80、另一项为 60 或更高的武器。完整的原始 380 点分配可能显示为 381 或 382，因为各项属性会独立取整。",
	quick_discard_protect_high_level_curios = "保留达到最低物品等级的珍品",
	quick_discard_protect_high_level_curios_tooltip = "无论稀有度如何，保护达到或超过所设最低物品等级的已启用珍品类型。若启用生命值或韧性主词条阈值，其对应类型优先按词条判断；伤口和体力珍品仍按物品等级判断。",
	quick_discard_curio_protection_level = "保留珍品的最低物品等级",
	quick_discard_curio_protection_level_tooltip = "当珍品的主要祝福类型在下方启用时，保护显示物品等级达到或超过此值的珍品；已启用主词条阈值的生命值或韧性珍品除外。仅在启用珍品最低等级保护时显示。默认值为 410。",
	quick_discard_keep_health_curios = "保留生命珍品",
	quick_discard_keep_toughness_curios = "保留韧性珍品",
	quick_discard_keep_wound_curios = "保留伤口珍品",
	quick_discard_keep_stamina_curios = "保留体力珍品",
	quick_discard_keep_curio_type_tooltip = "选择可受保护的珍品主词条类型。启用生命值或韧性词条阈值后，其对应类型优先按词条判断；伤口和体力珍品按物品等级判断。所有类型默认启用；词条规则启用时，未知的未来类型会安全地保持受保护状态。",
	quick_discard_show_type_breakdown = "在确认窗口中显示装备类型数量",
	quick_discard_show_type_breakdown_tooltip = "在快速丢弃确认窗口的每个稀有度行中显示近战武器、远程武器和珍品数量。此显示选项仅在模组选项中提供，默认启用。",
	quick_discard_show_summary_notification = "显示自动丢弃通知",
	quick_discard_show_summary_notification_tooltip = "在后端确认自动丢弃后显示原生通知，丢弃的物品数量按稀有度着色。手动丢弃完成仍然属于《暗潮》的原生库存流程。",
	quick_discard_disable_no_eligible_notification = "未找到符合条件的丢弃物品时禁用通知",
	quick_discard_disable_no_eligible_notification_tooltip = "当没有物品符合当前筛选条件时，隐藏哀星号自动丢弃通知。成功丢弃通知不受影响。",
	quick_discard_inventory_prefix = "全部丢弃",
	quick_discard_inventory_mode = "模式",
	quick_discard_inventory_suffix = "及以下",
	quick_discard_inventory_action = "点击丢弃",
	quick_discard_inventory_max_level = "可丢弃的最高物品等级",
	quick_discard_inventory_item_types_label = "要丢弃的物品类型：",
	quick_discard_inventory_melee = "近战",
	quick_discard_inventory_ranged = "远程",
	quick_discard_inventory_curios = "珍品",
	quick_discard_inventory_curio_level = "保留珍品的最低物品等级",
	quick_discard_inventory_protect_above_equipped_level = "不丢弃等级高于已装备物品的装备",
	quick_discard_inventory_keep_curio_types_label = "保留以下类型的珍品：",
	quick_discard_inventory_protect_weapons = "不要丢弃完美属性武器",
	quick_discard_inventory_protect_curios = "保留达到最低物品等级的珍品",
	quick_discard_inventory_keep_health_curios = "生命",
	quick_discard_inventory_keep_toughness_curios = "韧性",
	quick_discard_inventory_keep_wound_curios = "伤口",
	quick_discard_inventory_keep_stamina_curios = "体力",
	quick_discard_automatic_confirmation_title = "确认自动丢弃",
	quick_discard_confirmation_title = "确认快速丢弃",
	quick_discard_confirmation_description = "已启用装备类型中未收藏、未装备的物品将被永久丢弃。受保护物品不会包含在内。",
	quick_discard_summary_melee_singular = "近战武器",
	quick_discard_summary_melee_plural = "近战武器",
	quick_discard_summary_ranged_singular = "远程武器",
	quick_discard_summary_ranged_plural = "远程武器",
	quick_discard_summary_curio_singular = "件珍品",
	quick_discard_summary_curio_plural = "件珍品",
	quick_discard_summary_and = "和",
	quick_discard_confirmation_warning = "此操作无法撤消。",
	quick_discard_confirmation_yes = "是的，丢弃物品",
	quick_discard_confirmation_no = "不，保留物品",
	quick_discard_nothing_title = "没有符合条件的物品",
	quick_discard_nothing_description = "此库存中没有任何物品与当前的快速丢弃过滤器匹配。收藏的、装备的和受保护的物品始终被排除在外。",
	quick_discard_automatic_nothing_description = "自动哀星号扫描已完成，但没有物品与当前丢弃过滤器匹配。收藏的、装备的和受保护的物品始终被排除在外。",
	quick_discard_automatic_nothing_notification_title = "未发现可丢弃的物品",
	quick_discard_automatic_nothing_notification_description = "哀星号自动扫描未发现符合条件的物品。",
	quick_discard_notification_title = "已丢弃物品：",
	quick_discard_notification_items = "件物品",
	quick_discard_close = "关闭",
	enable_melee_inventory = "近战武器",
	enable_ranged_inventory = "远程武器",
	enable_curio_inventory = "珍品",
	additional_views_group = "其他库存视图",
	enable_hadron_entreat_grid = "海德昂：请求海德昂",
	enable_hadron_entreat_grid_tooltip = "通过“请求海德昂”选择物品时使用 BetterInventory 卡片。有效布局最多为三列；海德昂单独的“献祭武器”流程不受影响。",
	enable_armoury_requisition_grid = "军械库：申领武器与珍品",
	enable_armoury_requisition_grid_tooltip = "在“申领武器与珍品”中使用 BetterInventory 卡片。有效布局最多为三列；布伦特军械库和多干员补给不受影响。",
	expand_armoury_requisition_window = "扩展军械库申领窗口",
	expand_armoury_requisition_window_tooltip = "向右加宽征用武器和珍品网格，并安全地重新定位物品详细信息面板和获取按钮。仅当两列布局的卡片比所选目标窄时，两列布局才会展开。",
	armoury_requisition_target_card_width = "军械库目标卡宽度",
	armoury_requisition_target_card_width_tooltip = "扩展军械库网格所需的卡宽度（以像素为单位）。在三列中，默认值 230 像素为《暗潮》的原生网格宽度增加了 114 像素。",
	layout_group = "网格布局",
	quick_look_card_integration_group = "模组集成：Quick Look Card",
	enable_quick_look_card_single_column_integration = "在单列模式中显示武器属性",
	enable_quick_look_card_single_column_integration_tooltip = "无需安装其他模组即可显示武器五项最大潜力属性。安装 Quick Look Card 时，BetterInventory 会复用并规范其绘制项以避免重复。关闭后将保留 Quick Look Card 原生的单列内容。更改后请重新打开库存。",
	quick_look_card_single_column_font_size = "单列属性字号",
	quick_look_card_single_column_font_size_tooltip = "控制单列模式中五项武器属性区块的字号。更改后请重新打开库存。",
	quick_look_card_single_column_label_value_gap = "单列属性标签与数值间距",
	quick_look_card_single_column_label_value_gap_tooltip = "控制单列模式中每项属性标签与数值之间的水平像素间距。调低可使区块更紧凑，调高可增加分隔。更改后请重新打开库存。",
	quick_look_card_single_column_horizontal_position = "单列属性水平位置（%%）",
	quick_look_card_single_column_horizontal_position_tooltip = "在卡片可用宽度内水平移动五项武器属性区块。0 为左边缘，100 为右边缘。更改后请重新打开库存。",
	quick_look_card_single_column_vertical_position = "单列属性垂直位置（%%）",
	quick_look_card_single_column_vertical_position_tooltip = "在卡片可用高度内垂直移动五项武器属性区块。0 为上边缘，100 为下边缘。更改后请重新打开库存。",
	enable_quick_look_card_grid_integration = "在网格模式中显示最低武器属性",
	enable_quick_look_card_grid_integration_tooltip = "无需安装其他模组即可显示每件武器最低的最大潜力属性。并列时使用显示顺序中的第一项。安装 Quick Look Card 时，其重叠的网格绘制项会保持隐藏。更改后请重新打开库存。",
	quick_look_card_grid_stat_position = "最低属性位置",
	quick_look_card_grid_stat_position_tooltip = "将最低武器属性放在武器威力上方或武器名称旁。名称旁的位置会预留卡片宽度；卡片过窄时会自动回退到武器威力上方，以确保名称可读。",
	quick_look_card_grid_stat_position_above_power = "武器威力上方",
	quick_look_card_grid_stat_position_name_right = "武器名称右侧",
	quick_look_card_grid_stat_position_name_left = "武器名称左侧",
	quick_look_card_grid_font_size = "网格最低属性字号",
	quick_look_card_grid_font_size_tooltip = "控制网格中短板属性标签的字号。更改后请重新打开库存。",
	quick_look_card_grid_bottom_padding = "最低属性底部边距",
	quick_look_card_grid_bottom_padding_tooltip = "控制最低属性标签在武器威力上方显示时，与卡片底边之间的像素距离。数值越低，标签越靠近威力值。更改后请重新打开库存。",
	weapon_modifier_lowest_color_preset = "最低属性颜色预设",
	weapon_modifier_lowest_color_preset_tooltip = "设置网格模式中最低属性及单列五项属性区块中高亮缩写所使用的颜色。",
	weapon_modifier_lowest_color_r = "最低属性颜色红色",
	weapon_modifier_lowest_color_g = "最低属性颜色绿色",
	weapon_modifier_lowest_color_b = "最低属性颜色蓝色",
	weapon_modifier_lowest_color_opacity = "最低属性不透明度",
	weapon_modifier_lowest_color_opacity_tooltip = "设置最低属性文字的不透明度：0%% 为完全透明，100%% 为完全不透明。",
	weapon_modifier_melee_damage = "近战",
	weapon_modifier_ammo = "弹药",
	weapon_modifier_penetration = "穿透",
	weapon_modifier_burn = "燃烧",
	weapon_modifier_charge_rate = "充能",
	weapon_modifier_cleave_damage = "劈伤",
	weapon_modifier_cleave_targets = "劈数",
	weapon_modifier_crowd_control = "控场",
	weapon_modifier_collateral = "远控",
	weapon_modifier_critical_bonus = "暴击",
	weapon_modifier_damage = "伤害",
	weapon_modifier_defences = "防御",
	weapon_modifier_blast_penetration = "爆穿",
	weapon_modifier_blast_damage = "爆伤",
	weapon_modifier_blast_radius = "爆距",
	weapon_modifier_finesse = "娴熟",
	weapon_modifier_shredder = "撕裂",
	weapon_modifier_first_target = "首个",
	weapon_modifier_cloud_radius = "火距",
	weapon_modifier_thermal_resistance = "热阻",
	weapon_modifier_mobility = "机动",
	weapon_modifier_power_output = "能量",
	weapon_modifier_stopping_power = "制动",
	weapon_modifier_range = "范围",
	weapon_modifier_reload_speed = "装弹",
	weapon_modifier_stability = "稳定",
	weapon_modifier_quell_speed = "冷却",
	weapon_modifier_warp_resistance = "亚阻",
	weapon_modifier_heat_management = "热管",
	weapon_modifier_arc_efficiency = "电弧",
	weapon_modifier_cleave_efficiency = "劈效",
	single_column_layout_group = "单列布局",
	single_column_weapon_name_font_size = "武器名称字号",
	single_column_weapon_name_font_size_tooltip = "控制单列模式中的武器名称字号。字号增大时，自动卡片尺寸会相应增加高度，避免名称占用下方详情行。更改后请重新打开库存。",
	single_column_blessing_icons_on_right = "在名称旁显示祝福图标",
	single_column_blessing_icons_on_right_tooltip = "在单列文字模式中，将两个完整的带边框祝福图标并排显示在祝福名称右侧的空间中。等级符号仍保持在名称前方。更改后请重新打开库存。",
	enhanced_descriptions_integration_group = "模组集成：Enhanced Descriptions",
	enable_grid_layout = "启用网格布局",
	enable_grid_layout_tooltip = "使用 BetterInventory 的多列卡片。关闭后保留《暗潮》原生单列尺寸，同时继续使用已启用的卡片内容增强功能。",
	columns = "列数",
	columns_tooltip = "每行显示的物品卡片数量。建议从三列开始。",
	expand_inventory_window = "需要时扩大库存窗口",
	expand_inventory_window_tooltip = "扩展库存面板，使较窄的卡片保持在面板范围内。武器宽度阈值和珍品目标宽度设置控制额外扩展。关闭后则缩小卡片。",
	weapon_extra_width_column_threshold = "应用额外武器宽度的列数",
	weapon_extra_width_column_threshold_tooltip = "选择额外的近战和远程库存宽度是适用于四列和五列网格还是仅适用于五列网格。",
	weapon_extra_width_column_threshold_four_plus = "4 列或更多",
	weapon_extra_width_column_threshold_five_only = "仅 5 列",
	five_column_weapon_extra_width = "额外武器库存宽度",
	five_column_weapon_extra_width_tooltip = "达到所设列数阈值时，为近战和远程库存增加指定像素宽度。默认 80 像素会让四列中的每张卡片增加 20 像素，五列中增加 16 像素。扩展会在操作面板触及屏幕边缘前安全限制。",
	expand_curio_inventory_window = "按列数扩展珍品窗口",
	expand_curio_inventory_window_tooltip = "在添加列时使用目标珍品卡宽度来加宽库存面板。三列通常保留原始面板宽度；四列和五列可以使用可用的水平空间。",
	curio_target_card_width = "目标珍品卡片宽度",
	curio_target_card_width_tooltip = "启用列感知珍品扩展时所需的珍品卡宽度（以像素为单位）。最终面板宽度源自该值、列数和网格间距。",
	grid_spacing = "卡片间距",
	card_height = "卡片高度",
	card_height_tooltip = "手动网格卡高度。当自动卡高度启用时，此控件被禁用。",
	automatic_card_height = "自动卡片高度",
	automatic_card_height_tooltip = "当所选文字行和字号需要更多垂直空间时自动增高卡片。单列卡片也会为已启用的 BetterInventory 专长和祝福行预留足够高度。",
	option_requires_grid_layout = "启用网格布局以使用此选项。",
	option_requires_single_column_mode = "关闭网格布局以使用此单列选项。",
	option_requires_ranked_blessing_text = "选择带等级的祝福文本以使用此选项。",
	option_requires_quick_look_card_single_column_integration = "启用单列武器属性以使用此选项。",
	option_requires_quick_look_card_grid_integration = "启用网格武器属性以使用此选项。",
	option_requires_quick_look_card_above_power = "选择“武器威力上方”后才能使用此选项。",
	option_requires_weapon_extra_width_threshold = "将列增加到配置的额外宽度阈值以使用此选项。",
	option_disabled_by_automatic_height = "禁用自动卡高度以设置手动高度。",
	option_requires_window_expansion = "启用库存窗口扩展以使用此选项。",
	option_requires_curio_expansion = "启用列感知珍品扩展以设置目标卡宽度。",
	option_requires_armoury_grid = "启用军械库征用网格以使用此选项。",
	option_requires_armoury_expansion = "启用军械库征用窗口扩展以设置目标卡宽度。",
	option_requires_weapon_perks = "启用武器专长文字后才能使用此选项。",
	option_requires_perk_rank_symbols = "启用专长等级符号后才能设置其大小。",
	option_requires_weapon_blessings = "选择祝福图标后才能使用此选项。",
	option_requires_single_column_blessing_icons = "启用单列祝福图标后，才能在祝福文字模式中使用此选项。",
	option_requires_detailed_curio_profile = "选择珍品“全部四项属性”模式后才能使用此选项。",
	option_requires_experimental_quick_discard = "启用实验性库存快速丢弃控件以使用此选项。",
	option_requires_automatic_discard_mode = "选择自动丢弃模式以使用此选项。",
	option_requires_curio_discard_protection = "启用最小物品等级珍品保护以设置其阈值。",
	icon_darkness = "图标暗度(%%)",
	card_content_group = "卡片内容",
	append_mark_to_name = "将型号附加到武器名称",
	append_mark_to_name_tooltip = "将武器标题格式化为“Combat Blade Mk VI”一类的形式，并让次要行仅显示武器型号系列。标题过窄需要缩写时仍会保留 Mk 型号。",
	force_weapon_name_single_line = "强制武器名称显示为单行",
	force_weapon_name_single_line_tooltip = "武器标题始终保持单行。长标题会先缩小到设定的最小物品名称字号，再以省略号缩短，同时保留附加的 Mk 型号。",
	show_pattern_mark = "显示武器型号行",
	show_pattern_mark_tooltip = "显示《暗潮》武器卡片的次要名称。启用“将型号附加到武器名称”后，此行仅显示武器型号系列；否则同时显示系列和 Mk 型号。",
	show_rarity_name = "显示武器品质文字",
	show_rarity_tag = "显示稀有度颜色条",
	weapon_blessing_display_mode = "武器祝福显示",
	weapon_blessing_display_mode_tooltip = "选择完整祝福图标、带罗马数字等级的紧凑名称、带原生等级符号的名称，或隐藏祝福内容。自动卡片高度会预留所需空间。",
	weapon_blessing_display_mode_icons = "图标",
	weapon_blessing_display_mode_text = "文字行",
	weapon_blessing_display_mode_ranked_text = "等级符号 + 文字",
	weapon_blessing_display_mode_off = "关闭",
	blessing_text_item_level_separation = "分开显示祝福文字和物品等级",
	blessing_text_item_level_separation_tooltip = "选择何时将两个祝福名称置于独立的物品等级行上方。默认在较窄的四列和五列库存网格中使用这种更安全、更宽松的布局。",
	blessing_text_item_level_separation_always = "始终",
	blessing_text_item_level_separation_four_plus = "4 列或更多",
	blessing_text_item_level_separation_five_only = "仅 5 列",
	blessing_text_item_level_separation_never = "从不",
	auto_fit_long_blessing_names = "自动适配过长的祝福名称",
	auto_fit_long_blessing_names_tooltip = "仅缩小超出可用宽度的祝福文字，直到其能在物品等级旁完整显示。默认启用。",
	truncate_long_blessing_names = "截断过长的祝福名称",
	truncate_long_blessing_names_tooltip = "强制祝福名称单行显示。如果在可选的自动缩小后仍然过长，会在物品等级区域前用 ... 替换名称末尾。",
	blessing_icon_size = "祝福图标大小",
	option_requires_weapon_blessing_text = "选择祝福文字模式后才能使用此选项。",
	weapon_blessing_text_vertical_spacing = "祝福文字垂直间距",
	weapon_blessing_text_vertical_spacing_tooltip = "设置两行武器祝福文字之间的垂直像素间距。自动卡片高度会预留新增空间。",
	weapon_blessing_text_bottom_padding = "祝福文字底部边距",
	weapon_blessing_text_bottom_padding_tooltip = "设置第二行祝福文字下方的像素间距。预留物品等级行或军械库页脚时，边距会应用在该区域上方。自动卡片高度会预留此空间。",
	weapon_blessing_text_color_preset = "武器祝福文字颜色预设",
	weapon_blessing_text_color_r = "武器祝福文字颜色红色",
	weapon_blessing_text_color_g = "武器祝福文字颜色绿色",
	weapon_blessing_text_color_b = "武器祝福文字颜色蓝色",
	weapon_blessing_text_opacity = "武器祝福文字不透明度",
	weapon_blessing_text_opacity_tooltip = "设置祝福文字不透明度：0%% 为完全透明，100%% 为完全不透明。等级符号保持原生外观。",
	blessing_icon_size_tooltip = "设置每个武器祝福符号的宽度和高度（以像素为单位）。当较大的符号需要更多空间时，卡片高度会自动增加。",
	show_weapon_perks = "显示武器专长文字",
	show_weapon_perks_tooltip = "将两项武器专长分别显示为单独的一行。默认启用；自动卡片高度会预留所需空间，过长文字会先缩小，再以省略号截断。",
	weapon_perk_compression = "武器专长文字压缩",
	weapon_perk_compression_tooltip = "高度压缩为默认设置，适合较窄卡片；普通压缩使用较温和的缩写。未知专长标识符会保留《暗潮》的原始本地化文字。",
	weapon_perk_compression_none = "不压缩",
	weapon_perk_compression_standard = "压缩",
	weapon_perk_compression_heavy = "高度压缩",
	show_weapon_perk_rank_symbols = "显示专长等级符号",
	show_weapon_perk_rank_symbols_tooltip = "在每个可见武器专长行左侧显示《暗潮》的原生专长等级符号。默认启用。",
	weapon_perk_rank_icon_size = "等级符号大小",
	weapon_perk_rank_icon_size_tooltip = "设置武器专长和等级符号+文本祝福使用的原生等级符号的宽度和高度。当较大的符号需要更多空间时，卡片高度会自动增加。",
	option_requires_rank_symbols = "启用专长等级符号或选择“等级符号 + 文字”祝福模式后才能使用此选项。",
	remove_weapon_perk_plus_signs = "移除武器专长文字中的 +",
	remove_weapon_perk_plus_signs_tooltip = "仅移除每个可见武器专长行开头的加号；其他位置的数值和符号保持不变。",
	weapon_perk_text_color_preset = "武器专长文字颜色预设",
	weapon_perk_text_color_r = "武器专长文字颜色预设红色",
	weapon_perk_text_color_g = "武器专长文字颜色预设绿色",
	weapon_perk_text_color_b = "武器专长文字颜色预设蓝色",
	weapon_perk_text_opacity = "武器专长文字不透明度",
	weapon_perk_text_opacity_tooltip = "设置武器专长文字不透明度：0%% 为完全透明，100%% 为完全不透明。专长等级符号保持原生外观。",
	weapon_perk_vertical_spacing = "武器专长垂直间距",
	weapon_perk_vertical_spacing_tooltip = "设置两行武器专长之间的垂直像素间距。自动卡片高度会预留新增空间。",
	weapon_perk_blessing_spacing = "专长与祝福区域间距",
	weapon_perk_blessing_spacing_tooltip = "当武器专长和祝福区域同时可见时，设置两者之间的垂直像素边距。边距超过默认值时，卡片高度会自动增加。",
	option_requires_perk_and_blessing_sections = "同时显示武器专长和武器祝福后才能使用此选项。",
	blessing_icon_spacing = "祝福图标水平间距",
	blessing_icon_spacing_tooltip = "设置武器祝福图标之间的水平像素间距。",
	highlight_equipped_items = "高亮模式",
	highlight_equipped_items_tooltip = "选择已装备物品卡片的突出显示方式，同时保留《暗潮》的原生装备符号。脉冲动画虚线会从透明缓慢淡入到不透明，再淡出。",
	compact_favorite_marker = "使用紧凑收藏标记",
	favorite_marker_position = "收藏标记位置",
	favorite_marker_position_tooltip = "将收藏标记放在物品威力上方的右上区域或左下角。已装备物品会将右上标记下移，以避开装备徽章。",
	favorite_marker_position_above_rating = "右上角，武器威力上方",
	favorite_marker_position_bottom_left = "左下角",
	item_name_font_size = "物品名称字号",
	minimum_item_name_font_size = "最小物品名称字号",
	minimum_item_name_font_size_tooltip = "长名称会先缩小到此字号，再以省略号截断。名称绝不会换行到系列或型号行。",
	secondary_text_font_size = "型号和稀有度字号",
	expertise_font_size = "专精等级字号",
	show_item_level_icon = "显示物品威力图标",
	show_item_level_icon_tooltip = "在物品威力数字左侧显示《暗潮》的威力图标。默认关闭；数字威力值始终保留。",
	curio_content_group = "珍品内容",
	curio_display_profile = "珍品显示模式",
	curio_display_profile_tooltip = "“全部四项属性”为默认模式，显示主要属性及三项专长。“主要属性”模式保留珍品名称和威力，仅额外显示其主要属性。",
	curio_display_profile_primary = "主要属性",
	curio_display_profile_detailed = "全部四项属性",
	show_curio_item_level = "显示珍品基础等级",
	show_curio_item_level_tooltip = "在两种显示模式的右下角显示珍品的标准化基础等级。默认启用，便于识别 400–430 级珍品。",
	curio_primary_stat_font_size = "珍品主要属性字号",
	curio_primary_stat_font_size_tooltip = "设置两种显示模式中珍品主要生命、韧性、伤口或体力属性行的字号。",
	curio_secondary_stat_font_size = "珍品次要属性字号",
	curio_secondary_stat_font_size_tooltip = "设置“全部四项属性”模式中三行珍品次要专长的字号。",
	curio_primary_secondary_spacing = "珍品主要与次要属性间距",
	curio_primary_secondary_spacing_tooltip = "设置“全部四项属性”模式中珍品主要属性与第一行次要属性之间的垂直像素间距。",
	show_curio_quality = "显示珍品品质文字",
	show_curio_quality_tooltip = "在“主要属性”模式中显示珍品品质行。默认关闭，因为卡片颜色已经表示品质。",
	curio_stat_compression = "珍品属性文字压缩",
	curio_stat_compression_tooltip = "高度压缩为默认设置，使用“减伤、恢复、格挡、疾跑”等紧凑标签；普通压缩使用较温和的缩写。未知描述会保留《暗潮》的原始本地化文字。",
	curio_stat_compression_none = "不压缩",
	curio_stat_compression_standard = "压缩",
	curio_stat_compression_heavy = "高度压缩",
	simplify_curio_primary_stat_text = "简化珍品属性行",
	simplify_curio_primary_stat_text_tooltip = "开启：BetterInventory 会精简受支持的珍品主要和次要属性行。关闭：完整保留《暗潮》或 Enhanced Descriptions 提供的原始措辞。",
	remove_curio_stat_plus_signs = "移除珍品属性行中的 +",
	remove_curio_stat_plus_signs_tooltip = "移除 BetterInventory 珍品卡片中每个属性行开头的 + 号。默认关闭。",
	curio_secondary_color_mode = "次要珍品属性颜色模式",
	curio_secondary_color_mode_tooltip = "按专长类别着色（默认）：将相关的次要珍品专长分组，每组可自定义颜色。单一颜色：所有次要属性行使用同一种颜色。未来未知专长使用单一颜色作为后备。",
	curio_secondary_color_mode_category = "按专长类别着色",
	curio_secondary_color_mode_single = "单一颜色",
	curio_secondary_text_color_group = "珍品次要属性行颜色",
	curio_secondary_text_color_preset = "预设",
	curio_secondary_text_color_r = "红色",
	curio_secondary_text_color_g = "绿色",
	curio_secondary_text_color_b = "蓝色",
	curio_health_color_group = "最大生命属性行颜色",
	curio_health_color_preset = "预设",
	curio_health_color_r = "红色",
	curio_health_color_g = "绿色",
	curio_health_color_b = "蓝色",
	curio_toughness_color_group = "最大韧性属性行颜色",
	curio_toughness_color_preset = "预设",
	curio_toughness_color_r = "红色",
	curio_toughness_color_g = "绿色",
	curio_toughness_color_b = "蓝色",
	curio_wound_color_group = "伤口属性行颜色",
	curio_wound_color_preset = "预设",
	curio_wound_color_r = "红色",
	curio_wound_color_g = "绿色",
	curio_wound_color_b = "蓝色",
	curio_stamina_color_group = "最大体力属性行颜色",
	curio_stamina_color_preset = "预设",
	curio_stamina_color_r = "红色",
	curio_stamina_color_g = "绿色",
	curio_stamina_color_b = "蓝色",
	curio_enemy_resistance_color_group = "敌人伤害抗性属性行颜色",
	curio_enemy_resistance_color_preset = "预设",
	curio_enemy_resistance_color_r = "红色",
	curio_enemy_resistance_color_g = "绿色",
	curio_enemy_resistance_color_b = "蓝色",
	curio_corruption_resistance_color_group = "腐化抗性属性行颜色",
	curio_corruption_resistance_color_preset = "预设",
	curio_corruption_resistance_color_r = "红色",
	curio_corruption_resistance_color_g = "绿色",
	curio_corruption_resistance_color_b = "蓝色",
	curio_ability_regeneration_color_group = "技能恢复属性行颜色",
	curio_ability_regeneration_color_preset = "预设",
	curio_ability_regeneration_color_r = "红色",
	curio_ability_regeneration_color_g = "绿色",
	curio_ability_regeneration_color_b = "蓝色",
	curio_mission_rewards_color_group = "任务奖励属性行颜色",
	curio_mission_rewards_color_preset = "预设",
	curio_mission_rewards_color_r = "红色",
	curio_mission_rewards_color_g = "绿色",
	curio_mission_rewards_color_b = "蓝色",
	curio_revive_speed_color_group = "救援速度属性行颜色",
	curio_revive_speed_color_preset = "预设",
	curio_revive_speed_color_r = "红色",
	curio_revive_speed_color_g = "绿色",
	curio_revive_speed_color_b = "蓝色",
	color_preset_red = "红色",
	color_preset_light_blue = "浅蓝色",
	color_preset_sky_blue = "天蓝色",
	color_preset_purple = "紫色",
	color_preset_pink = "粉色",
	color_preset_orange = "橙色",
	color_preset_yellow = "黄色",
	color_preset_green = "绿色",
	color_preset_light_green = "浅绿色",
	color_preset_terminal_green = "终端绿色",
	color_preset_neutral = "中性色",
	color_preset_custom = "自定义颜色",
	curio_resistance_flamers = "火焰兵抗性",
	curio_resistance_snipers = "狙击手抗性",
	curio_resistance_grenadiers = "轰炸者抗性",
	curio_resistance_hounds = "瘟疫猎犬抗性",
	curio_resistance_mutants = "变种人抗性",
	curio_resistance_gunners = "炮手抗性",
	curio_resistance_bombers = "瘟疫爆者抗性",
	curio_resistance_grimoires = "魔法书腐化抗性",
	curio_reward_chance = "珍品任务奖励概率",
	curio_toughness_regeneration = "韧性恢复",
	curio_ordo_dockets = "审判庭双子币",
	curio_revive_speed = "复活速度",
	curio_dr_flamers = "火焰兵减伤",
	curio_dr_snipers = "狙击手减伤",
	curio_dr_grenadiers = "轰炸者减伤",
	curio_dr_hounds = "瘟疫猎犬减伤",
	curio_dr_mutants = "变种人减伤",
	curio_dr_gunners = "炮手减伤",
	curio_dr_bombers = "瘟疫爆者减伤",
	curio_dr_grimoires = "魔法书腐化减伤",
	curio_heavy_ability_regen = "技能恢复",
	curio_heavy_toughness_regen = "韧性恢复",
	curio_heavy_corruption_dr = "腐化减伤",
	curio_heavy_block = "格挡",
	curio_heavy_sprint = "疾跑",
	curio_heavy_stamina_regen = "体力恢复",
	weapon_perk_unarmoured_damage = "无甲伤害",
	weapon_perk_unarmoured_damage_heavy = "无甲伤害",
	weapon_perk_flak_damage = "防弹装甲伤害",
	weapon_perk_flak_damage_heavy = "防弹伤害",
	weapon_perk_unyielding_damage = "不屈伤害",
	weapon_perk_unyielding_damage_heavy = "不屈伤害",
	weapon_perk_maniacs_damage = "狂人伤害",
	weapon_perk_maniacs_damage_heavy = "狂人伤害",
	weapon_perk_carapace_damage = "硬壳装甲伤害",
	weapon_perk_carapace_damage_heavy = "硬壳伤害",
	weapon_perk_infested_damage = "感染伤害",
	weapon_perk_infested_damage_heavy = "感染伤害",
	weapon_perk_melee_crit_chance = "近战暴击率",
	weapon_perk_melee_crit_chance_heavy = "近战暴击",
	weapon_perk_melee_crit_damage = "近战暴击伤害",
	weapon_perk_melee_crit_damage_heavy = "暴击伤害",
	weapon_perk_horde_melee_damage = "群怪近战伤害",
	weapon_perk_horde_melee_damage_heavy = "群怪伤害",
	weapon_perk_elites_melee_damage = "精英近战伤害",
	weapon_perk_elites_melee_damage_heavy = "精英伤害",
	weapon_perk_specialist_melee_damage = "专家近战伤害",
	weapon_perk_specialist_melee_damage_heavy = "专家伤害",
	weapon_perk_melee_weakspot_damage = "近战弱点伤害",
	weapon_perk_melee_weakspot_damage_heavy = "弱点伤害",
	weapon_perk_ranged_crit_chance = "远程暴击率",
	weapon_perk_ranged_crit_chance_heavy = "远程暴击",
	weapon_perk_ranged_crit_damage = "远程暴击伤害",
	weapon_perk_ranged_crit_damage_heavy = "暴击伤害",
	weapon_perk_horde_ranged_damage = "群怪远程伤害",
	weapon_perk_horde_ranged_damage_heavy = "群怪伤害",
	weapon_perk_elites_ranged_damage = "精英远程伤害",
	weapon_perk_elites_ranged_damage_heavy = "精英伤害",
	weapon_perk_specialist_ranged_damage = "专家远程伤害",
	weapon_perk_specialist_ranged_damage_heavy = "专家伤害",
	weapon_perk_ranged_weakspot_damage = "远程弱点伤害",
	weapon_perk_ranged_weakspot_damage_heavy = "弱点伤害",
	weapon_perk_stamina = "体力",
	weapon_perk_melee_damage = "近战伤害",
	weapon_perk_melee_damage_heavy = "近战伤害",
	weapon_perk_ranged_damage = "远程伤害",
	weapon_perk_ranged_damage_heavy = "远程伤害",
	weapon_perk_melee_finesse = "近战娴熟",
	weapon_perk_ranged_finesse = "远程娴熟",
	weapon_perk_finesse_heavy = "娴熟",
	weapon_perk_melee_power = "近战威力",
	weapon_perk_ranged_power = "远程威力",
	weapon_perk_power_heavy = "威力",
	weapon_perk_melee_impact = "近战冲击",
	weapon_perk_impact_heavy = "冲击",
	weapon_perk_block_efficiency = "格挡效率",
	weapon_perk_block_heavy = "格挡",
	weapon_perk_sprint_efficiency = "疾跑效率",
	weapon_perk_sprint_heavy = "疾跑",
	weapon_perk_reload_speed = "装填速度",
	weapon_perk_reload_heavy = "装填",
}

localization.automatic_curio_target_mode = "珍品获取目标"
localization.automatic_curio_target_mode_tooltip = "角色模式为默认选项，可分别启用每个已发现的角色。职业模式会将每个职业复选框应用于该职业的所有角色。新角色会自动启用；若确认扫描不到可用角色，则会安全回退到职业模式。"
localization.automatic_curio_target_mode_classes = "职业"
localization.automatic_curio_target_mode_characters = "角色"
localization.automatic_curio_target_mode_inventory_suffix = "获取珍品："
localization.automatic_curio_characters_group = "要获取珍品的角色："
localization.automatic_curio_characters_inventory_label = "要获取珍品的角色："
localization.automatic_curio_characters_discovering = "正在发现角色……请稍后重新打开模组选项，或使用库存选项面板。"
localization.automatic_curio_characters_discovering_inventory = "正在发现角色..."
localization.automatic_curio_character_options_placeholder = "正在发现角色……"
localization.automatic_curio_character_slot_placeholder = "角色"
localization.automatic_curio_character_slot_unavailable = "（当前未找到）"
localization.automatic_curio_character_slot_empty_reason = "当前没有角色分配到此栏位。BetterInventory 会在进入哀星号后刷新角色列表，并在枢纽中定期刷新。"
localization.enable_automatic_curio_acquisition_tooltip = "每次进入符合条件的界面后，对所有角色的军械库交易所执行一次扫描，并自动购买符合物品等级、主要属性数值、类型和目标筛选条件的所有珍品。哀星号使用现有购买器设置；干员选择界面需要单独启用。目标可按职业或单个角色选择。此功能会在没有确认提示的情况下花费审判庭双子币。自动丢弃会先完成，且符合获取规则的珍品会在以后的自动丢弃流程中保持受保护状态。"
localization.automatic_curio_min_item_level_tooltip = "只有显示物品等级达到或超过此值的军械库珍品才符合条件。生命和韧性珍品还必须达到对应的最低主要属性数值。货币充足时，会购买每个已启用目标的所有匹配商品。默认值为 410。"

localization.enable_armoury_requisition_sorting_panel = "显示军械库排序组件"
localization.enable_armoury_requisition_sorting_panel_tooltip = "在申领武器与珍品中添加可折叠的 BetterInventory 排序组件。需要开启军械库网格，默认开启。"
localization.brighten_armoury_item_levels = "提亮军械库物品等级"
localization.brighten_armoury_item_levels_tooltip = "使用更明亮的文字显示军械库交易所卡片中的物品等级，避免被底部价格区域遮暗。默认开启。"
localization.three_column_weapon_name_font_size = "军械库武器名称字号"
localization.three_column_weapon_name_font_size_tooltip = "控制军械库卡片中的武器名称字号。调低数值可帮助较长名称保持在一行，同时不影响库存卡片。"
localization.hadron_additional_views_group = "海德昂"
localization.armoury_exchange_views_group = "军械库交易所"
localization.global_store_integration_group = "Mod 集成：GlobalStore"
localization.enable_global_store_integration = "启用 GlobalStore 集成"
localization.enable_global_store_integration_tooltip = "为多干员补给启用 BetterInventory 的 GlobalStore 集成。关闭后将保持 GlobalStore 的原生卡片和排序。"
localization.enable_global_store_grid = "使用 BetterInventory 网格卡片"
localization.enable_global_store_grid_tooltip = "在 GlobalStore 的多干员补给中使用 BetterInventory 响应式网格卡片。该视图最多三列；近战、远程和珍品列数设置仅适用于库存标签页。三列会增加角色信息行，但不会拉伸武器图像。"
localization.enable_global_store_sorting_panel = "显示 GlobalStore 排序组件"
localization.enable_global_store_sorting_panel_tooltip = "在 GlobalStore 的多干员补给中添加可折叠的 BetterInventory 排序和暗潮原生排序组件。需要开启 GlobalStore 网格，默认开启。"
localization.global_store_character_photo_size_percent = "GlobalStore 角色头像大小（%%）"
localization.global_store_character_photo_size_percent_tooltip = "控制二至三列卡片中的 GlobalStore 角色头像大小（50-125%%，默认110%%）。角色信息行位于价格和物品等级行下方，预留高度保持不变，因此调整此值不会改变卡片尺寸或使价格移动。"
localization.global_store_price_row_padding = "GlobalStore 价格/物品等级行内边距"
localization.global_store_price_row_padding_tooltip = "控制 GlobalStore 角色信息行上方的垂直内边距。增加此值会让奥多点券和物品等级行远离角色头像，而不会改变头像大小。"
localization.global_store_character_info_gap = "GlobalStore 角色信息水平间距"
localization.global_store_character_info_gap_tooltip = "控制 GlobalStore 角色头像与职业图标/名称之间的水平间距。单位为像素，适用于二至三列卡片。"
localization.global_store_character_class_icon_size = "GlobalStore 职业图标大小"
localization.global_store_character_class_icon_size_tooltip = "控制二至三列卡片中的 GlobalStore 职业图标字号（8-24像素，默认16）。角色信息行和卡片尺寸保持不变。"
localization.global_store_character_name_font_size = "GlobalStore 角色名称字号"
localization.global_store_character_name_font_size_tooltip = "控制二至三列卡片中的 GlobalStore 角色名称字号（8-20像素，默认16）。角色信息行和卡片尺寸保持不变。"
localization.global_store_compact_character_names = "在4-5列中压缩 GlobalStore 角色名称"
localization.global_store_compact_character_names_tooltip = "为兼容旧配置而保留。GlobalStore 最多三列，因此不会使用四列和五列窄卡片行为。默认开启。"
localization.option_requires_global_store_grid = "启用 GlobalStore 网格后才能使用此选项。"
localization.option_requires_global_store_integration = "启用 GlobalStore 集成后才能使用此选项。"

localization.global_store_single_column_modifier_horizontal_position = "GlobalStore 单列属性水平位置（%%）"
localization.global_store_single_column_modifier_horizontal_position_tooltip = "水平移动 GlobalStore 原生单列武器属性。0 为最左，100 为最右。更改后请重新打开 GlobalStore。"
localization.global_store_single_column_modifier_vertical_position = "GlobalStore 单列属性垂直位置（%%）"
localization.global_store_single_column_modifier_vertical_position_tooltip = "垂直移动 GlobalStore 原生单列武器属性。0 为顶部，100 为底部。更改后请重新打开 GlobalStore。"
localization.melee_columns = "近战武器列数"
localization.melee_columns_tooltip = "库存每行显示的近战武器卡片数量。默认为三。"
localization.ranged_columns = "远程武器列数"
localization.ranged_columns_tooltip = "库存每行显示的远程武器卡片数量。默认为三。"
localization.curio_columns = "珍品列数"
localization.curio_columns_tooltip = "库存每行显示的珍品卡片数量。默认为三。"

localization.enable_hadron_single_column_mirror = "镜像库存单列格式"
localization.enable_hadron_single_column_mirror_tooltip = "关闭网格布局时，在“请求海德昂”中使用详细的 BetterInventory 单列卡片格式。默认启用。"
localization.enable_armoury_single_column_mirror = "为单列启用自定义详细卡片"
localization.enable_armoury_single_column_mirror_tooltip = "关闭网格布局时，在“申领武器与珍品”中使用 BetterInventory 的自定义详细卡片。默认启用。"
localization.custom_item_name_and_colors_group = "自定义物品名称和颜色"
localization.enable_custom_item_name_and_colors = "启用自定义物品名称和颜色"
localization.enable_custom_item_name_and_colors_tooltip = "启用 BetterInventory 独立的全物品名称、名称颜色和背景颜色编辑器。无需 Name It。"
localization.custom_item_name_keybind = "更改名称快捷键"
localization.custom_item_name_keybind_tooltip = "直接打开名称编辑器。默认使用 I / View / Touchpad，以避免《暗潮》控制器的收藏操作。启用此编辑器后，BetterInventory 会替换 Name It 重复的库存操作。"
localization.custom_item_name_color_keybind = "名称颜色快捷键"
localization.custom_item_name_color_keybind_tooltip = "直接打开物品名称 RGB 选择器。"
localization.custom_item_background_color_keybind = "背景颜色快捷键"
localization.custom_item_background_color_keybind_tooltip = "直接打开物品背景 RGB 选择器。"
localization.custom_item_editor_keybind_i_view = "[I / View / Touchpad]"
localization.custom_item_editor_keybind_e = "[E]"
localization.custom_item_editor_keybind_q = "[Q]"
localization.custom_item_editor_keybind_v = "[V]"
localization.custom_item_editor_keybind_r = "[R]"
localization.custom_item_editor_keybind_lt = "[A / LT]"
localization.custom_item_editor_keybind_off = "Off"
localization.custom_item_skip_confirmation_prompts = "跳过确认提示"
localization.custom_item_skip_confirmation_prompts_tooltip = "立即应用重置操作，不再询问确认。默认启用。"
localization.custom_item_preserve_card_shading = "保留《暗潮》装备卡片阴影"
localization.custom_item_preserve_card_shading_tooltip = "在自定义背景颜色下方使用《暗潮》的深色底层。关闭后会用所选颜色完整绘制整张卡片。每个已绘制的物品都会保留其确认的选择。"
localization.custom_item_override_weapon_information_color = "将自定义颜色应用到武器信息"
localization.custom_item_override_weapon_information_color_tooltip = "在武器信息标题中使用物品的自定义背景颜色。该面板中始终保留《暗潮》原生的深色底层和渐变阴影。"
localization.custom_item_override_weapon_rarity_keyword_color = "将自定义颜色应用到稀有度关键词"
localization.custom_item_override_weapon_rarity_keyword_color_tooltip = "在武器信息面板中，使用物品的自定义背景颜色显示其稀有度关键词。"
localization.custom_item_override_weapon_information_name_color = "将自定义名称颜色应用到武器信息"
localization.custom_item_override_weapon_information_name_color_tooltip = "在武器信息面板中，使用物品的自定义名称颜色显示其名称。"
localization.option_requires_custom_item_name_and_colors = "启用自定义物品名称和颜色后才能使用此选项。"
localization.name_it_force_curio_name_in_detailed_mode = "在详细模式中显示珍品名称与全四项属性"
localization.name_it_force_curio_name_in_detailed_mode_tooltip = "在角色总览及受支持的物品视图中，于四行属性上方显示两行珍品名称。有无 Name It 均可使用。"
localization.curio_content_name_it_curio_name = "在详细模式中显示珍品名称与全四项属性"
localization.curio_content_name_it_curio_name_tooltip = "在角色总览及受支持的物品视图中，于四行属性上方显示两行珍品名称。有无 Name It 均可使用。"
localization.character_overview_group = "角色总览"
localization.enable_character_overview_melee_mirror = "镜像库存近战武器单列格式"
localization.enable_character_overview_melee_mirror_tooltip = "在角色总览界面中，使用详细的 BetterInventory 单列卡片显示已装备的近战武器。默认启用。"
localization.character_overview_show_melee_rarity_strip = "显示近战武器颜色条"
localization.character_overview_show_melee_rarity_strip_tooltip = "在镜像的近战武器卡片上绘制左侧稀有度颜色条。默认启用。"
localization.enable_character_overview_ranged_mirror = "镜像库存远程武器单列格式"
localization.enable_character_overview_ranged_mirror_tooltip = "在角色总览界面中，使用详细的 BetterInventory 单列卡片显示已装备的远程武器。默认启用。"
localization.character_overview_show_ranged_rarity_strip = "显示远程武器颜色条"
localization.character_overview_show_ranged_rarity_strip_tooltip = "在镜像的远程武器卡片上绘制左侧稀有度颜色条。默认启用。"
localization.character_overview_show_only_dump_stat = "仅显示武器低项属性"
localization.character_overview_show_only_dump_stat_tooltip = "将镜像角色总览武器卡片上的五行最大潜力属性行替换为仅显示物品威力上方的单项最低属性。默认关闭。"
localization.option_requires_character_overview_weapon_mirror = "需要镜像的角色总览武器卡片和单列武器属性。"
localization.character_overview_dump_stat_horizontal_offset = "低项属性水平偏移"
localization.character_overview_dump_stat_horizontal_offset_tooltip = "将角色总览低项属性标签水平移动 -300 到 300 像素。负值向左移动，正值向右移动。"
localization.character_overview_dump_stat_font_scale_percent = "低项属性字号缩放（%%）"
localization.character_overview_dump_stat_font_scale_percent_tooltip = "将角色总览低项属性标签从 50%% 缩放到 200%%，不影响其他卡片文字。"
localization.character_overview_dump_stat_color_preset = "低项属性字体颜色预设"
localization.character_overview_dump_stat_color_preset_tooltip = "设置角色总览低项属性标签颜色。编辑任一 RGB 通道会选择自定义。"
localization.character_overview_dump_stat_color_r = "低项属性字体颜色红色"
localization.character_overview_dump_stat_color_g = "低项属性字体颜色绿色"
localization.character_overview_dump_stat_color_b = "低项属性字体颜色蓝色"
localization.option_requires_character_overview_dump_stat_only = "需要启用“仅显示武器低项属性”。"
localization.enable_character_overview_curio_details = "在角色总览中显示详细珍品卡片"
localization.enable_character_overview_curio_details_tooltip = "在角色总览界面中，以紧凑的 BetterInventory 卡片显示已装备珍品的主要和次要属性。默认启用。"
localization.character_overview_show_curio_rarity_strip = "显示珍品颜色条"
localization.character_overview_show_curio_rarity_strip_tooltip = "在详细珍品卡片上绘制左侧稀有度颜色条。默认启用。"
localization.character_overview_use_native_curio_overlay = "使用原生珍品叠层"
localization.character_overview_use_native_curio_overlay_tooltip = "在详细的角色总览珍品上使用《暗潮》华丽的珍品边框和肖像布局，同时保留 BetterInventory 的标题和属性行。默认关闭。"
localization.item_sorting_mod_header = "ItemSorting 模组"
localization.character_overview_curio_name_mode = "珍品标题模式"
localization.character_overview_curio_name_mode_tooltip = "隐藏珍品标题，或在角色总览的四行属性上方将其限制在一行或两行内显示。"
localization.character_overview_curio_name_mode_none = "无标题"
localization.character_overview_curio_name_mode_one_line = "单行标题"
localization.character_overview_curio_name_mode_two_lines = "双行标题"
localization.character_overview_curio_font_size_percent = "角色总览珍品字号（%%）"
localization.character_overview_curio_font_size_percent_tooltip = "缩放角色总览中详细珍品卡片的所有文字（50-150%%，默认 110%%）。不影响库存和商店中的珍品卡片。"
localization.option_requires_character_overview_curio_details = "需要角色总览中的详细珍品卡片。"
localization.myfavorites_integration_group = "模组集成：MyFavorites"
localization.lantern_integration_group = "模组集成：Lantern of the Omnissiah"
localization.enable_lantern_inventory_section = "在库存面板中显示 Lantern of the Omnissiah 推荐"
localization.enable_lantern_inventory_section_tooltip = "安装 Lantern of the Omnissiah 后，将其推荐窗口放置在 BetterInventory 可缩放库存选项面板的顶部区域，并隐藏该模组重复的浮动武器面板。珍品推荐默认保持独立。"
localization.keep_lantern_curio_panel_separate = "保持 Lantern of the Omnissiah 珍品面板独立"
localization.keep_lantern_curio_panel_separate_tooltip = "将 Lantern of the Omnissiah 的“推荐珍品”窗口保留在其原生的独立位置，而不是托管在 BetterInventory 的库存选项面板内。默认启用，因为其珍品布局已能并排放在 BetterInventory 面板旁。"
localization.option_requires_lantern_of_the_omnissiah = "需要安装 Lantern of the Omnissiah。"
localization.inventory_options_controller_focus_keybind = "物品 / 组件焦点快捷键"
localization.inventory_options_controller_focus_keybind_tooltip = "在库存物品网格和 BetterInventory 选项组件之间切换控制器焦点。RT 未被《暗潮》原生的近战、远程和珍品库存控件使用。"
localization.inventory_options_controller_focus_keybind_rt = "[D / RT]"
localization.inventory_options_controller_focus_legend = "物品 / 组件焦点"
localization.myfavorites_show_favorite_letter = "在收藏图标下方显示 F"
localization.myfavorites_show_favorite_letter_tooltip = "在彩色 MyFavorites 图标下方添加一个紧凑的 F。默认关闭。"
localization.debug_group = "调试（仅测试用）"
localization.debug_enable_hot_path_diagnostics = "启用热路径诊断"
localization.debug_enable_hot_path_diagnostics_tooltip = "选择加入的采样计数器，覆盖 UI 重建、对齐/枢轴写入、活动读取承诺、操作年龄和 Lua 内存。默认关闭；仅在收集基线时启用。"
localization.debug_weapon_options_button_count = "武器操作测试按钮数量"
localization.debug_weapon_options_button_count_tooltip = "通过在真实操作之后添加仅展示用的空操作按钮，将操作总行数设为 5、10 或 20。面板扩展到七行后开始滚动，且不会在框架外绘制溢出内容。更改此值后请重新打开库存。"
localization.debug_weapon_options_button_count_off = "关闭"
localization.debug_weapon_options_button_count_5 = "5 个按钮"
localization.debug_weapon_options_button_count_10 = "10 个按钮"
localization.debug_weapon_options_button_count_20 = "20 个按钮"
localization.debug_weapon_kill_counter_kills = "武器击杀计数器测试击杀数"
localization.debug_weapon_kill_counter_kills_tooltip = "仅展示用。安装 Weapon Kill Counter 并启用其卡片叠层后，会在每张武器卡上显示 1000 次击杀，而不改变该模组已保存的统计数据。"
localization.debug_weapon_kill_counter_kills_off = "关闭"
localization.debug_weapon_kill_counter_kills_1000 = "1000 击杀"
localization.debug_expand_armoury_requisition_window_30_percent = "增加军械库交易所商店宽度"
localization.debug_expand_armoury_requisition_window_30_percent_tooltip = "调试几何压力测试。仅在“申领武器与珍品”中，按下方百分比增加正常解析的商店网格宽度，并按比例重排其装备卡片。更改此设置后请重新打开军械库交易所。"
localization.debug_armoury_requisition_window_increase_percent = "商店宽度增加量（%%）"
localization.debug_armoury_requisition_window_increase_percent_tooltip = "将军械库交易所商店宽度的人为增加量设为 10%% 到 100%%。默认压力测试增加量为 30%%。"
localization.debug_adjust_inventory_window_width = "调整库存窗口宽度"
localization.debug_adjust_inventory_window_width_tooltip = "近战、远程和珍品库存的调试几何压力测试。按下方带符号的百分比调整正常解析的网格宽度，并按比例重排其装备卡片。更改此设置后请重新打开库存。"
localization.debug_inventory_window_width_adjustment_percent = "库存宽度调整（%%）"
localization.debug_inventory_window_width_adjustment_percent_tooltip = "将解析后的库存宽度从 -50%% 缩小到 +100%% 放大。默认压力测试调整量为 +30%%。"
localization.debug_adjust_global_store_window_width = "调整 GlobalStore 窗口宽度"
localization.debug_adjust_global_store_window_width_tooltip = "GlobalStore 多干员补给网格的调试几何压力测试。按下方带符号的百分比调整正常解析的网格宽度，并按比例重排其装备卡片。更改此设置后请重新打开 GlobalStore。"
localization.debug_global_store_window_width_adjustment_percent = "GlobalStore 宽度调整（%%）"
localization.debug_global_store_window_width_adjustment_percent_tooltip = "将解析后的 GlobalStore 宽度从 -50%% 缩小到 +100%% 放大。默认压力测试调整量为 +30%%。"

localization.auto_crafter_group = "自动制作助手"
localization.auto_crafter_enable = "启用自动制作助手探测"
localization.auto_crafter_enable_tooltip = "打开布伦特军械库自动制作助手面板。账户修改仍需单独显式启用。"
localization.auto_crafter_read_only_probe = "运行只读布伦特探测"
localization.auto_crafter_read_only_probe_tooltip = "进入军械库后读取当前布伦特商品、钱包和装备一次。禁用自动制作助手后会自动停用。"
localization.auto_crafter_show_probe_notifications = "显示自动制作助手探测通知"
localization.auto_crafter_show_probe_notifications_tooltip = "默认启用。探测、计划、购买搜索和精通同步状态会显示原生通知。通知错误不会影响游戏数据。"
localization.auto_crafter_notification_title = "自动制作助手"
localization.auto_crafter_probe_started = "只读布伦特探测已开始。"
localization.auto_crafter_probe_failed = "只读布伦特探测失败"
localization.auto_crafter_panel_title = "自动制作助手"
localization.auto_crafter_panel_read_only = "只读"
localization.auto_crafter_panel_status = "状态"
localization.auto_crafter_panel_offers = "商品"
localization.auto_crafter_panel_wallet = "资源"
localization.auto_crafter_panel_gear = "装备"
localization.auto_crafter_panel_inventory = "库存"
localization.auto_crafter_panel_target = "目标"
localization.auto_crafter_panel_no_target = "未选择目标"
localization.auto_crafter_panel_offer_list = "武器选择"
localization.auto_crafter_panel_selected_weapon = "已选武器"
localization.auto_crafter_panel_select_weapon = "请在布伦特军械库列表中选择武器。"
localization.auto_crafter_panel_no_offers = "暂无可用武器商品。"
localization.auto_crafter_panel_more = "还有更多商品"
localization.auto_crafter_target_dump_stat = "自动制作目标低项属性"
localization.auto_crafter_target_dump_stat_tooltip = "从当前武器的索引基础属性中手动选择低项属性。切换武器时选择器会重置到索引 0。"
localization.auto_crafter_dump_stat_damage = "伤害"
localization.auto_crafter_dump_stat_mobility = "机动性"
localization.auto_crafter_dump_stat_finesse = "精巧"
localization.auto_crafter_dump_stat_penetration = "穿透"
localization.auto_crafter_dump_stat_first_target = "首个目标"
localization.auto_crafter_dump_stat_defenses = "防御"
localization.auto_crafter_dump_stat_target = "低项属性目标"
localization.auto_crafter_dump_stat_target_tooltip = "串行购买搜索使用的目标低项属性百分比。无法识别属性结构时会安全停止。"
localization.auto_crafter_custom_stats = "自定义属性"
localization.auto_crafter_custom_stats_tooltip = "使用精确的五项属性分配替代单一低项属性目标。每项限制为 60-80，且总和必须正好为 380 才能开始制作。"
localization.auto_crafter_custom_stat_1 = "自定义属性 1"
localization.auto_crafter_custom_stat_2 = "自定义属性 2"
localization.auto_crafter_custom_stat_3 = "自定义属性 3"
localization.auto_crafter_custom_stat_4 = "自定义属性 4"
localization.auto_crafter_custom_stat_5 = "自定义属性 5"
localization.auto_crafter_custom_stat_value_tooltip = "保存当前武器对应属性的目标值。游戏内自动制作面板会显示具体属性名称和受保护的调整箭头。"
localization.auto_crafter_cap_by_dockets = "按奥多券限制完美属性武器获取"
localization.auto_crafter_cap_by_dockets_tooltip = "启用完美属性武器获取的奥多券上限。关闭时仍会保存数值上限。"
localization.auto_crafter_docket_cap = "奥多券上限"
localization.auto_crafter_docket_cap_tooltip = "串行购买搜索可消费的奥多券上限。超过上限的下一次购买不会发送。"
localization.auto_crafter_cap_by_max_purchases = "按最大购买次数限制完美属性武器获取"
localization.auto_crafter_cap_by_max_purchases_tooltip = "启用完美属性武器获取的最大购买次数上限。关闭时仍会保存数值上限。"
localization.auto_crafter_max_purchases = "自动制作最大购买次数"
localization.auto_crafter_max_purchases_tooltip = "串行购买搜索硬上限。达到次数后不会发送下一次购买。"
localization.auto_crafter_best_candidate_fallback = "未找到精确属性时使用最接近的候选武器"
localization.auto_crafter_best_candidate_fallback_tooltip = "达到上限仍未找到精确武器时，使用五项目标属性绝对差之和最小的候选武器。距离相同时保留最早购买的武器。"
localization.auto_crafter_request_mode = "自动制作请求模式"
localization.auto_crafter_request_mode_tooltip = "串行是默认且最安全的模式。并行读取是未来实验选项；并行修改在后端行为确认前保持禁用。"
localization.auto_crafter_request_mode_sequential = "串行（推荐）"
localization.auto_crafter_request_mode_parallel_reads = "并行读取"
localization.auto_crafter_request_mode_experimental = "实验性并行修改"
localization.auto_crafter_workflow_group = "制作流程"
localization.auto_crafter_resuming_group = "继续制作物品选项"
localization.auto_crafter_buy_until_target = "基础武器获取"
localization.auto_crafter_buy_until_target_tooltip = "禁用自动获取、购买第一把武器后继续，或搜索到满足目标属性。旧版开关会安全迁移：开启对应目标搜索，关闭对应禁用。"
localization.auto_crafter_level_mastery_20 = "自动将武器精通提升至 20 级"
localization.auto_crafter_level_mastery_20_tooltip = "运行受保护的串行购买、升级、牺牲、领取和同步流程，直到权威精通达到 20 级；同时解锁 IV 级专长规划。"
localization.auto_crafter_defer_bad_weapon_processing = "仅在找到完美武器后处理不合格武器"
localization.auto_crafter_defer_bad_weapon_processing_tooltip = "在确认精确目标前保留所有购买失败品。之后将其用于提升精通，并在精通达到 20 级后丢弃剩余武器。需要启用精通 20 级。"
localization.auto_crafter_allocate_mastery_points = "自动分配精通点数"
localization.auto_crafter_allocate_mastery_points_tooltip = "武器精通达到 20 级后，自动分配所选制作目标所需的精通点数。"
localization.auto_crafter_consecrate_transcendent = "自动将武器祝圣为超凡"
localization.auto_crafter_consecrate_transcendent_tooltip = "仅补齐缺少的稀有度阶段，将最终候选自动祝圣至超凡。"
localization.auto_crafter_upgrade_expertise_500 = "自动将武器物品等级提升至 500"
localization.auto_crafter_upgrade_expertise_500_tooltip = "所需精通奖励可用后，自动将最终候选的武器物品等级提升至 500。"
localization.auto_crafter_change_perks = "更改专长"
localization.auto_crafter_change_perks_tooltip = "需要武器精通达到 20 级以解锁 IV 级专长，然后安全应用所选兼容专长目标。"
localization.auto_crafter_change_blessings = "更改祝福"
localization.auto_crafter_change_blessings_tooltip = "需要武器精通达到 20 级并分配必要点数，然后安全应用所选兼容祝福目标。"
localization.auto_crafter_trait_targets_group = "专长和祝福目标"
localization.auto_crafter_perk_1_target = "专长目标 1"
localization.option_requires_auto_crafter_mastery_20 = "启用自动将武器精通提升至 20 级，以解锁 IV 级专长规划。"
localization.option_requires_auto_crafter_change_perks = "启用更改专长。"
localization.option_requires_auto_crafter_blessing_workflow = "启用精通点数分配和更改祝福。"
localization.auto_crafter_perk_2_target = "专长目标 2"
localization.auto_crafter_perk_target_tooltip = "需要精通 20 级和更改专长。请从所选武器目录中选择两个不同且兼容的 IV 级专长。"
localization.auto_crafter_blessing_1_target = "祝福目标 1"
localization.auto_crafter_blessing_2_target = "祝福目标 2"
localization.auto_crafter_blessing_target_tooltip = "请从所选武器系列的祝福目录中选择两个不同且兼容的祝福。"
localization.auto_crafter_target_keep = "保留当前"
localization.auto_crafter_target_auto = "自动选择"
localization.auto_crafter_target_auto_discovered = "自动选择"
localization.auto_crafter_target_auto_pending = "自动选择（等待发现）"
localization.auto_crafter_trait_catalog_ready = "已发现专长和祝福"
localization.auto_crafter_trait_catalog_pending = "正在发现所选武器"
localization.auto_crafter_trait_catalog_failed = "发现不可用"
localization.auto_crafter_show_perk_grid = "显示专长网格"
localization.auto_crafter_show_perk_grid_tooltip = "以四列显示兼容的 IV 级专长。左键设置目标 1（黄色），右键设置目标 2（绿色）；不允许重复。"
localization.auto_crafter_show_blessing_grid = "显示祝福网格"
localization.auto_crafter_show_blessing_grid_tooltip = "以三列图标网格显示兼容祝福。左键设置目标 1（黄色），右键设置目标 2（绿色）；不允许重复。"
localization.auto_crafter_favorite_result = "自动收藏制作完成的武器"
localization.auto_crafter_favorite_result_tooltip = "在权威库存验证确认精确匹配的武器后，将其收藏。"
localization.auto_crafter_panel_planner = "规划器配置"
localization.auto_crafter_panel_planner_target = "规划目标"
localization.auto_crafter_panel_dump_stat = "低项属性"
localization.auto_crafter_panel_dump_target = "低项目标"
localization.auto_crafter_panel_custom_stat_total = "属性总和"
localization.auto_crafter_panel_docket_cap = "奥多券上限"
localization.auto_crafter_panel_max_purchases = "最大购买次数"
localization.auto_crafter_panel_best_fallback = "未找到精确属性时使用最接近的候选武器"
localization.auto_crafter_panel_request_mode = "请求模式"
localization.auto_crafter_panel_estimate = "估算"
localization.auto_crafter_panel_consecrate_cost = "亵渎至超凡"
localization.auto_crafter_panel_mastery_cost = "精通祭品投入"
localization.auto_crafter_panel_total_cost = "已知制作投入"
localization.auto_crafter_panel_current_resources = "当前资源"
localization.auto_crafter_panel_generous_cost = "宽裕成本估算"
localization.auto_crafter_panel_unlucky_cost = "不利成本估算"
localization.auto_crafter_panel_remaining_generous = "预计剩余（宽裕）"
localization.auto_crafter_panel_remaining_unlucky = "预计剩余（不利）"
localization.auto_crafter_panel_disabled = "已禁用"
localization.auto_crafter_panel_preview = "> 点击此处制作 <"
localization.auto_crafter_panel_phase_2 = "升级并牺牲一件"
localization.auto_crafter_panel_phase_2_waiting = "没有已购买候选"
localization.auto_crafter_panel_stop = "> 点击此处停止 / 中断 <"
localization.auto_crafter_panel_waiting = "等待探测"
localization.auto_crafter_panel_ui_plan = "界面计划"
localization.auto_crafter_panel_workflow = "制作流程"
localization.auto_crafter_panel_trait_targets = "专长和祝福目标"
localization.auto_crafter_panel_resuming = "继续制作物品选项"
localization.auto_crafter_panel_option_unavailable = "请启用前置选项"
localization.auto_crafter_panel_advanced = "高级与安全"
localization.auto_crafter_value_on = "开"
localization.auto_crafter_value_off = "关"

-- Counts are composed by the panel so localization values remain valid with
-- the layout verifier and do not require positional string.format arguments.
localization.auto_crafter_target_auto_discovered = "自动选择"
localization.auto_crafter_trait_catalog_ready = "已发现专长和祝福"


localization.auto_crafter_reuse_inventory_base = "从库存中继续匹配低项属性的武器"
localization.auto_crafter_reuse_inventory_base_tooltip = "在购买新武器前，使用一把库存中匹配且未收藏的武器。"
localization.auto_crafter_include_favorite_inventory_bases = "继续制作时包含已收藏的库存武器"
localization.auto_crafter_include_favorite_inventory_bases_tooltip = "允许将已收藏武器作为最终制作基底。"
localization.auto_crafter_craft_duplicate_completed_queued_weapons = "可重复制作已完成的队列武器"
localization.auto_crafter_craft_duplicate_completed_queued_weapons_tooltip = "当没有未完成的武器可继续制作时，制作一把新副本，而不是跳过已完成但同类等效的队列武器。"
localization.auto_crafter_show_status_hud = "显示顶部制作 HUD"
localization.auto_crafter_show_status_hud_tooltip = "在哀星号商店和库存视图中显示制作目标。"
localization.option_requires_auto_crafter_inventory_reuse = "需要启用库存基底复用。"

localization.auto_crafter_panel_marks = "标记"
localization.auto_crafter_panel_estimates = "估算"

localization.weapon_images_size_position_group = "武器图像大小和位置"
localization.curio_images_size_position_group = "珍品图像大小和位置"
localization.image_layout_character_overview = "角色总览"
localization.image_layout_inventory_hadron = "库存和海德昂"
localization.image_layout_armoury_exchange = "军械库交易所商店"
localization.image_layout_global_store = "GlobalStore 商店"
localization.image_layout_grid_profile = "要编辑的网格列配置"
localization.image_layout_grid_profile_tooltip = "选择下方四个控件所编辑的独立列布局。卡片会自动使用与其实际列数匹配的配置。"
localization.image_layout_single_column = "单列（网格模式关闭）"
localization.image_layout_two_columns = "2 列网格模式"
localization.image_layout_three_columns = "3 列网格模式"
localization.image_layout_four_columns = "4 列网格模式"
localization.image_layout_five_columns = "5 列网格模式"
localization.image_layout_x_offset_percent = "图像 X 偏移（%%）"
localization.image_layout_y_offset_percent = "图像 Y 偏移（%%）"
localization.image_layout_width_offset_percent = "图像宽度偏移（%%）"
localization.image_layout_height_offset_percent = "图像高度偏移（%%）"
localization.image_layout_position_tooltip = "在原生图像位置上加上解析后卡片宽度或高度的一定百分比。零保持当前布局。更改后请重新打开相关视图。"
localization.image_layout_size_tooltip = "在解析后的原生图像大小上加上该百分比。零保持当前大小；-50 减半，100 加倍。更改后请重新打开相关视图。"

localization.highlight_equipped_items = "高亮模式"
localization.highlight_equipped_items_tooltip = "选择已装备物品卡片的突出显示方式，同时保留《暗潮》的原生装备符号。脉冲动画虚线会从透明缓慢淡入到不透明，再淡出。"
localization.equipped_highlight_mode_off = "关闭"
localization.equipped_highlight_mode_soft_glow = "柔和光晕"
localization.equipped_highlight_mode_animated_dashes = "动画虚线边框"
localization.equipped_highlight_mode_pulsing_dashes = "脉冲动画虚线边框"
localization.equipped_highlight_mode_solid_border = "实线边框"
localization.equipped_highlight_group = "已装备物品高亮"
localization.equipped_highlight_glow_intensity = "柔和光晕强度（%%）"
localization.equipped_highlight_glow_intensity_tooltip = "控制柔和光晕的不透明度：0%% 完全透明，100%% 达到最大强度。"
localization.equipped_highlight_animated_border_width = "动画虚线边框宽度"
localization.equipped_highlight_animated_border_width_tooltip = "使用 1-5 层有界的同心层加粗任一动画虚线边框模式。仅当重建卡片蓝图时才会创建图层；不保留逐卡动画状态，也没有逐帧分配。"
localization.equipped_highlight_solid_border_width = "实线边框宽度"
localization.equipped_highlight_solid_border_width_tooltip = "使用《暗潮》的原生框架材质和有界同心层，将已装备卡片实线边框宽度设为 1-5。"
localization.equipped_highlight_color_preset = "预设"
localization.equipped_highlight_color_r = "红色"
localization.equipped_highlight_color_g = "绿色"
localization.equipped_highlight_color_b = "蓝色"
localization.option_requires_equipped_highlight = "选择一个已装备物品高亮模式后才能使用这些颜色控件。"
localization.option_requires_equipped_highlight_soft_glow = "选择“柔和光晕”后才能使用此选项。"
localization.option_requires_equipped_highlight_animated_dashes = "选择任一动画虚线边框模式后才能使用此选项。"
localization.option_requires_equipped_highlight_solid_border = "选择“实线边框”后才能使用此选项。"
localization.new_item_highlight_group = "新获得物品高亮"
localization.new_item_highlight_mode = "高亮模式"
localization.new_item_highlight_mode_tooltip = "高亮《暗潮》仍标记为新获得的物品。进阶模式会用整卡效果替换原生小圆点；脉冲动画虚线会缓慢淡入淡出。"
localization.new_item_highlight_mode_native = "仅原生圆点"
localization.new_item_highlight_mode_soft_glow = "柔和光晕"
localization.new_item_highlight_mode_animated_dashes = "动画虚线边框"
localization.new_item_highlight_mode_pulsing_dashes = "脉冲动画虚线边框"
localization.new_item_highlight_mode_solid_border = "实线边框"
localization.new_item_acknowledge_mode = "将物品标记为已查看"
localization.new_item_acknowledge_mode_tooltip = "选中模式仅在卡片被选中后清除新物品状态。悬停模式在鼠标进入卡片或控制器焦点选中时也会清除。两种模式都使用《暗潮》原生的已保存新物品状态。"
localization.new_item_acknowledge_mode_select = "选中时"
localization.new_item_acknowledge_mode_hover = "悬停或控制器焦点时"
localization.new_item_highlight_glow_intensity = "柔和光晕强度（%%）"
localization.new_item_highlight_glow_intensity_tooltip = "控制新获得物品柔和光晕的不透明度：0%% 完全透明，100%% 达到最大强度。"
localization.new_item_highlight_animated_border_width = "动画虚线边框宽度"
localization.new_item_highlight_animated_border_width_tooltip = "使用 1-5 层有界的静态层加厚原生动画虚线材质。脉冲模式使用《暗潮》的全局 UI 时钟，不保留逐卡计时器状态。"
localization.new_item_highlight_solid_border_width = "实线边框宽度"
localization.new_item_highlight_solid_border_width_tooltip = "使用有界的原生框架层，将新获得物品的边框宽度设为 1-5。"
localization.new_item_highlight_color_preset = "预设"
localization.new_item_highlight_color_r = "红色"
localization.new_item_highlight_color_g = "绿色"
localization.new_item_highlight_color_b = "蓝色"
localization.option_requires_new_item_enhanced_highlight = "选择整卡式的新获得物品高亮模式后才能使用这些颜色控件。"
localization.option_requires_new_item_soft_glow = "选择“柔和光晕”后才能使用此选项。"
localization.option_requires_new_item_animated_dashes = "选择任一动画虚线边框模式后才能使用此选项。"
localization.option_requires_new_item_solid_border = "选择“实线边框”后才能使用此选项。"
localization.color_preset_gold = "金色"
localization.color_preset_white = "白色"
localization.color_preset_mode_default = "模式默认"
localization.quick_discard_protect_health_roll_curios = "仅保留达到此最低生命值词条或更高的珍品"
localization.quick_discard_protect_health_roll_curios_tooltip = "对生命值珍品，此阈值优先于最低物品等级；低于阈值的珍品即使物品等级达标仍可被丢弃。默认关闭。"
localization.quick_discard_curio_health_roll = "最低生命值词条（%%）"
localization.quick_discard_curio_health_roll_tooltip = "保护生命值主词条达到或超过此值的珍品。默认 21%%。"
localization.quick_discard_protect_toughness_roll_curios = "仅保留达到此最低韧性词条或更高的珍品"
localization.quick_discard_protect_toughness_roll_curios_tooltip = "对韧性珍品，此阈值优先于最低物品等级；低于阈值的珍品即使物品等级达标仍可被丢弃。默认关闭。"
localization.quick_discard_curio_toughness_roll = "最低韧性词条（%%）"
localization.quick_discard_curio_toughness_roll_tooltip = "保护韧性主词条达到或超过此值的珍品。默认 17%%。"
localization.quick_discard_inventory_protect_health_roll_curios = "仅保留达到此最低生命值词条或更高的珍品"
localization.quick_discard_inventory_curio_health_roll = "要保留的最低生命值词条"
localization.quick_discard_inventory_protect_toughness_roll_curios = "仅保留达到此最低韧性词条或更高的珍品"
localization.quick_discard_inventory_curio_toughness_roll = "要保留的最低韧性词条"
localization.option_requires_curio_health_roll_protection = "启用最低生命值词条珍品保护以设置阈值。"
localization.option_requires_curio_toughness_roll_protection = "启用最低韧性词条珍品保护以设置阈值。"
localization.automatic_curio_favorite_purchased_curios = "自动收藏购买的珍品"
localization.automatic_curio_favorite_purchased_curios_tooltip = "自动珍品购买器确认购买后收藏珍品。与手动军械库购买分开，默认关闭。"
localization.armoury_auto_favorite_purchased_items = "自动收藏购买的物品"
localization.armoury_auto_favorite_purchased_items_tooltip = "手动军械库交易所购买确认后收藏物品。若安装了 GlobalStore，此选项也适用于军械库的多角色补给。布伦特军械库、自动制作器和自动珍品购买器不受影响。默认关闭。"
localization.melk_views_group = "梅尔克爵士征用处"
localization.melk_auto_favorite_purchased_items = "自动收藏限时购得物品"
localization.melk_auto_favorite_purchased_items_tooltip = "限时购得物品确认购买后自动收藏。若安装了 GlobalStore，此选项也适用于梅尔克爵士的多角色补给。神秘购置由单独选项控制，自动制作器购买不受影响。默认关闭。"
localization.melk_mystery_auto_favorite_purchased_items = "自动收藏神秘购置物品"
localization.melk_mystery_auto_favorite_purchased_items_tooltip = "神秘购置物品确认购买后自动收藏。限时购得物品由单独选项控制，自动制作器购买不受影响。默认关闭。"
localization.auto_crafter_myfavorites_color = "MyFavorites 颜色"
localization.auto_crafter_myfavorites_color_tooltip = "启用自动收藏制作完成的武器后，将收藏分配到 MyFavorites 的五个颜色组之一。每个选项预览当前颜色。"
localization.auto_crafter_myfavorites_color_1 = "颜色 1"
localization.auto_crafter_myfavorites_color_2 = "颜色 2"
localization.auto_crafter_myfavorites_color_3 = "颜色 3"
localization.auto_crafter_myfavorites_color_4 = "颜色 4"
localization.auto_crafter_myfavorites_color_5 = "颜色 5"
localization.option_requires_myfavorites = "需要 MyFavorites 模组"
localization.option_requires_auto_crafter_myfavorites_color = "启用自动收藏制作完成的武器"

localization.auto_crafter_dump_stat_comparison = "低项属性目标比较"
localization.auto_crafter_dump_stat_comparison_tooltip = "精确匹配保留原有行为；低于或等于会接受升至 500 级后低项属性不高于目标的武器。自定义五项属性始终需要精确匹配。"
localization.auto_crafter_dump_stat_comparison_exact = "精确匹配"
localization.auto_crafter_dump_stat_comparison_at_most = "低于或等于"
localization.auto_crafter_acquisition_disabled = "禁用"
localization.auto_crafter_acquisition_first_weapon = "自动购买第一把武器并继续"
localization.auto_crafter_acquisition_target_search = "自动购买，直到找到目标属性武器"

return localization
