local mod = get_mod("ModPerformanceMonitor")

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = {
			{
				setting_id = "display_mode",
				type = "dropdown",
				title = "display_mode",
				tooltip = "display_mode_tooltip",
				default_value = "simplified",
				options = {
					{ text = "display_mode_simplified", value = "simplified" },
					{ text = "display_mode_detailed", value = "detailed" },
				},
			},
			{
				setting_id = "sort_mode",
				type = "dropdown",
				title = "sort_mode",
				tooltip = "sort_mode_tooltip",
				default_value = "self",
				options = {
					{ text = "sort_self", value = "self" },
					{ text = "sort_peak", value = "peak" },
					{ text = "sort_spikes", value = "spikes" },
					{ text = "sort_load", value = "load" },
					{ text = "sort_incl", value = "incl" },
					{ text = "sort_calls", value = "calls" },
					{ text = "sort_mem", value = "mem" },
					{ text = "sort_total", value = "total" },
				},
			},
			{
				setting_id = "smoothing",
				type = "dropdown",
				title = "smoothing",
				tooltip = "smoothing_tooltip",
				default_value = "smooth",
				options = {
					{ text = "smoothing_smooth", value = "smooth" },
					{ text = "smoothing_balanced", value = "balanced" },
					{ text = "smoothing_responsive", value = "responsive" },
				},
			},
			{
				setting_id = "show_graph",
				type = "checkbox",
				title = "show_graph",
				tooltip = "show_graph_tooltip",
				default_value = true,
			},
			{
				setting_id = "safe_mode",
				type = "checkbox",
				title = "safe_mode",
				tooltip = "safe_mode_tooltip",
				default_value = false,
			},
			{
				setting_id = "subtract_overhead",
				type = "checkbox",
				title = "subtract_overhead",
				tooltip = "subtract_overhead_tooltip",
				default_value = true,
			},
			{
				setting_id = "enabled_profiling",
				type = "checkbox",
				title = "enabled_profiling",
				tooltip = "enabled_profiling_tooltip",
				default_value = true,
			},
			{
				setting_id = "track_memory",
				type = "checkbox",
				title = "track_memory",
				tooltip = "track_memory_tooltip",
				default_value = false,
			},
			{
				setting_id = "max_rows",
				type = "numeric",
				title = "max_rows",
				tooltip = "max_rows_tooltip",
				default_value = 12,
				range = { 3, 40 },
			},
			{
				setting_id = "overlay_font_size",
				type = "numeric",
				title = "overlay_font_size",
				tooltip = "overlay_font_size_tooltip",
				default_value = 18,
				range = { 8, 48 },
			},
			{
				setting_id = "panel_width",
				type = "numeric",
				title = "panel_width",
				tooltip = "panel_width_tooltip",
				default_value = 560,
				range = { 320, 1000 },
			},
			{
				setting_id = "refresh_hz",
				type = "numeric",
				title = "refresh_hz",
				tooltip = "refresh_hz_tooltip",
				default_value = 3,
				range = { 1, 30 },
			},
			{
				setting_id = "hitch_ms",
				type = "numeric",
				title = "hitch_ms",
				tooltip = "hitch_ms_tooltip",
				default_value = 28,
				range = { 12, 100 },
			},
			{
				setting_id = "overlay_x",
				type = "numeric",
				title = "overlay_x",
				tooltip = "overlay_x_tooltip",
				default_value = 40,
				range = { 0, 1200 },
			},
			{
				setting_id = "overlay_y",
				type = "numeric",
				title = "overlay_y",
				tooltip = "overlay_y_tooltip",
				default_value = 90,
				range = { 0, 1000 },
			},
			{
				setting_id = "keybind_toggle_overlay",
				type = "keybind",
				title = "keybind_toggle_overlay",
				tooltip = "keybind_toggle_overlay_tooltip",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_overlay",
			},
			{
				setting_id = "keybind_toggle_mode",
				type = "keybind",
				title = "keybind_toggle_mode",
				tooltip = "keybind_toggle_mode_tooltip",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_mode",
			},
							{
					setting_id = "keybind_cycle_tab",
					type = "keybind",
					title = "keybind_cycle_tab",
					tooltip = "keybind_cycle_tab_tooltip",
					default_value = {},
					keybind_trigger = "pressed",
					keybind_type = "function_call",
					function_name = "cycle_tab",
				},
			{
				setting_id = "keybind_toggle_freeze",
				type = "keybind",
				title = "keybind_toggle_freeze",
				tooltip = "keybind_toggle_freeze_tooltip",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "toggle_freeze",
			},
			{
				setting_id = "keybind_dump_report",
				type = "keybind",
				title = "keybind_dump_report",
				tooltip = "keybind_dump_report_tooltip",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "dump_report",
			},
			{
				setting_id = "keybind_export_report",
				type = "keybind",
				title = "keybind_export_report",
				tooltip = "keybind_export_report_tooltip",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "export_report",
			},
			{
				setting_id = "keybind_reset_stats",
				type = "keybind",
				title = "keybind_reset_stats",
				tooltip = "keybind_reset_stats_tooltip",
				default_value = {},
				keybind_trigger = "pressed",
				keybind_type = "function_call",
				function_name = "reset_stats",
			},
		},
	},
}
