local mod = get_mod("markers_aio")

local apply_color_to_text = function(text, r, g, b)
	return "{#color(" .. r .. "," .. g .. "," .. b .. ")}" .. text .. "{#reset()}"
end

local fonts = mod._get_font_options()

local Gold = mod.lookup_border_color("Gold")
local Silver = mod.lookup_border_color("Silver")
local Steel = mod.lookup_border_color("Steel")
local Tarnished = mod.lookup_border_color("Tarnished")

local border_colours = {
	{
		text = apply_color_to_text(mod:localize("Gold"), Gold[2], Gold[3], Gold[4]),
		value = "Gold",
	},
	{
		text = apply_color_to_text(mod:localize("Silver"), Silver[2], Silver[3], Silver[4]),
		value = "Silver",
	},
	{
		text = apply_color_to_text(mod:localize("Steel"), Steel[2], Steel[3], Steel[4]),
		value = "Steel",
	},
	{
		text = apply_color_to_text(mod:localize("Tarnished"), Tarnished[2], Tarnished[3], Tarnished[4]),
		value = "Tarnished",
	},
}

local chest_icons = {
	{
		text = "Default",
		value = "content/ui/materials/hud/interactions/icons/default",
		icon = "content/ui/materials/hud/interactions/icons/default",
	},
	{
		text = "Video",
		value = "content/ui/materials/icons/system/settings/category_video",
		icon = "content/ui/materials/icons/system/settings/category_video",
	},
	{
		text = "Loot",
		value = "content/ui/materials/icons/generic/loot",
		icon = "content/ui/materials/icons/generic/loot",
	},
}

local luggable_icons = {
	{
		text = "Exclamation",
		value = "content/ui/materials/hud/interactions/icons/environment_alert",
		icon = "content/ui/materials/hud/interactions/icons/environment_alert",
	},
	{
		text = "Hands",
		value = "content/ui/materials/hud/communication_wheel/icons/thanks",
		icon = "content/ui/materials/hud/communication_wheel/icons/thanks",
	},
	{
		text = "Fist",
		value = "content/ui/materials/icons/presets/preset_18",
		icon = "content/ui/materials/icons/presets/preset_18",
	},
	{
		text = "Luggable",
		value = "content/ui/materials/icons/player_states/lugged",
		icon = "content/ui/materials/icons/player_states/lugged",
	},
}

local servo_skull_icons = {
	{
		text = "Terminal",
		value = "content/ui/materials/hud/interactions/icons/objective_side",
		icon = "content/ui/materials/hud/interactions/icons/objective_side",
	},
	{
		text = "Skull",
		value = "content/ui/materials/icons/difficulty/flat/difficulty_skull_malice",
		icon = "content/ui/materials/icons/difficulty/flat/difficulty_skull_malice",
	},
	{
		text = "Scanner",
		value = "content/ui/materials/icons/pocketables/hud/corrupted_auspex_scanner",
		icon = "content/ui/materials/icons/pocketables/hud/corrupted_auspex_scanner",
	},
	{
		text = "ScannerSkull",
		value = "content/ui/materials/backgrounds/scanner/scanner_decoration_skull",
		icon = "content/ui/materials/backgrounds/scanner/scanner_decoration_skull",
	},
}

local decoding_icons = {
	{
		text = "Terminal",
		value = "content/ui/materials/hud/interactions/icons/objective_side",
		icon = "content/ui/materials/hud/interactions/icons/objective_side",
	},

	{
		text = "Scanner",
		value = "content/ui/materials/icons/pocketables/hud/corrupted_auspex_scanner",
		icon = "content/ui/materials/icons/pocketables/hud/corrupted_auspex_scanner",
	},

	{
		text = "Investigation",
		value = "content/ui/materials/icons/mission_types/mission_type_03",
		icon = "content/ui/materials/icons/mission_types/mission_type_03",
	},
}

local background_colours = {
	{
		text = "Black",
		value = "Black",
	},
	{
		text = "Terminal",
		value = "Terminal",
	},
}
local distance_text_positions = {
	{
		text = "Top",
		value = "Top",
	},
	{
		text = "Bottom",
		value = "Bottom",
	},
	{
		text = "Left",
		value = "Left",
	},
	{
		text = "Right",
		value = "Right",
	},
	{
		text = "Center",
		value = "Center",
	},
}
return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = false,
	options = {
		widgets = {

			-- GLOBAL
			{
				setting_id = "aio_settings",
				type = "group",
				tab = "General",
				sub_widgets = {
					{
						setting_id = "mod_name_pizazz_toggle",
						type = "checkbox",
						default_value = true,
						tooltip = "mod_name_pizazz_tooltip",
					},
					{
						setting_id = "los_fade_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "los_fade_enable_tooltip",
					},
					{
						setting_id = "los_opacity",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "los_opacity_tooltip",
					},
					{
						setting_id = "ads_los_opacity",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "ads_los_opacity_tooltip",
					},
					{
						setting_id = "marker_background_colour",
						type = "dropdown",
						options = background_colours,
						default_value = "Terminal",
						tooltip = "marker_background_colour_tooltip",
					},
					{
						setting_id = "font_type",
						type = "dropdown",
						options = fonts,
						default_value = "mono_tide_bold",
						tooltip = "font_type_tooltip",
					},
					{
						setting_id = "distance_text_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "distance_text_enable_tooltip",
					},
					{
						setting_id = "distance_text_position",
						type = "dropdown",
						options = distance_text_positions,
						default_value = "Bottom",
						tooltip = "distance_text_position_tooltip",
					},
					{
						setting_id = "distance_text_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
				},
			},

			-- AMMO / MED
			{

				setting_id = "ammo_med_markers_settings",
				type = "group",
				tab = "Ammo & Med",
				sub_widgets = {
					{
						setting_id = "ammo_med_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "ammo_med_markers_alternate_large_ammo_icon",
						type = "checkbox",
						default_value = true,
						tooltip = "ammo_med_markers_alternate_large_ammo_icon_tooltip",
					},
					{
						setting_id = "ammo_med_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "ammo_med_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "med_station_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "ammo_med_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "ammo_med_toggle_los",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "ammo_med_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "med_station_max_distance",
						type = "numeric",
						default_value = 20,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "ammo_med_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "ammo_med_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "display_ammo_charges",
						type = "checkbox",
						default_value = true,
						tooltip = "display_ammo_charges_tooltip",
					},
					{
						setting_id = "display_med_charges",
						type = "checkbox",
						default_value = true,
						tooltip = "display_med_charges_tooltip",
					},
					{
						setting_id = "change_colour_for_ammo_charges",
						type = "checkbox",
						default_value = true,
						tooltip = "change_colour_for_ammo_charges_tooltip",
					},
					{
						setting_id = "display_field_improv_icon",
						type = "checkbox",
						default_value = true,
						tooltip = "display_field_improv_icon_tooltip",
					},
					{
						setting_id = "display_med_ring",
						type = "checkbox",
						default_value = true,
						tooltip = "display_med_ring_tooltip",
					},
					{
						setting_id = "display_field_improv_colour",
						type = "checkbox",
						default_value = true,
						tooltip = "display_field_improv_colour_tooltip",
					},

					{
						setting_id = "field_improv_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "field_improv_colour_R",
								type = "numeric",
								default_value = 50,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "field_improv_colour_G",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "field_improv_colour_B",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "ammo_small_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "ammo_small_colour_R",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "ammo_small_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "ammo_small_colour_B",
								type = "numeric",
								default_value = 222,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "ammo_small_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "ammo_large_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "ammo_large_colour_R",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "ammo_large_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "ammo_large_colour_B",
								type = "numeric",
								default_value = 222,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "ammo_large_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "ammo_crate_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "ammo_crate_colour_R",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "ammo_crate_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "ammo_crate_colour_B",
								type = "numeric",
								default_value = 222,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "ammo_crate_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "med_crate_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "med_crate_colour_R",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "med_crate_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "med_crate_colour_B",
								type = "numeric",
								default_value = 222,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "med_crate_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "grenade_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "grenade_colour_R",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "grenade_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "grenade_colour_B",
								type = "numeric",
								default_value = 222,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "grenade_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- CHESTS
			{

				setting_id = "chest_markers_settings",
				type = "group",
				tab = "Chests",
				sub_widgets = {
					{
						setting_id = "chest_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "chest_icon",
						type = "dropdown",
						options = chest_icons,
						default_value = "content/ui/materials/icons/system/settings/category_video",
						tooltip = "icon_tooltip",
					},
					{
						setting_id = "chest_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "chest_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "chest_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "chest_toggle_los",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "chest_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "chest_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "chest_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "chest_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "chest_icon_colour_R",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "chest_icon_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "chest_icon_colour_B",
								type = "numeric",
								default_value = 222,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "chest_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- HERETICAL IDOL
			{

				setting_id = "heretical_idol_markers_settings",
				type = "group",
				tab = "Heretical Idol",
				sub_widgets = {
					{
						setting_id = "heretical_idol_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "heretical_idol_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "heretical_idol_require_line_of_sight",
						type = "checkbox",
						default_value = false,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "heretical_idol_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "heretical_idol_toggle_los",
						tooltip = "toggle_los_tooltip",
					},

					{
						setting_id = "heretical_idol_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "heretical_idol_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "heretical_idol_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "icon_colour_R",
								type = "numeric",
								default_value = 132,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "icon_colour_G",
								type = "numeric",
								default_value = 156,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "icon_colour_B",
								type = "numeric",
								default_value = 99,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},

					{
						setting_id = "idol_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Tarnished",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- MATERIALS
			{

				setting_id = "material_markers_settings",
				type = "group",
				tab = "Materials",
				sub_widgets = {
					{
						setting_id = "material_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "material_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "material_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "material_toggle_los",
						type = "keybind",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						function_name = "material_toggle_los",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "material_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "material_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "material_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "marker_toggles",
						type = "group",
						sub_widgets = {
							{
								setting_id = "toggle_large_plasteel",
								type = "checkbox",
								default_value = true,
							},
							{
								setting_id = "toggle_small_plasteel",
								type = "checkbox",
								default_value = true,
							},
							{
								setting_id = "toggle_large_diamantine",
								type = "checkbox",
								default_value = true,
							},
							{
								setting_id = "toggle_small_diamantine",
								type = "checkbox",
								default_value = true,
							},
						},
					},
					{
						setting_id = "material_small_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "material_large_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "plasteel_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "plasteel_icon_colour_R",
								type = "numeric",
								default_value = 243,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "plasteel_icon_colour_G",
								type = "numeric",
								default_value = 115,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "plasteel_icon_colour_B",
								type = "numeric",
								default_value = 85,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "diamantine_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "diamantine_icon_colour_R",
								type = "numeric",
								default_value = 95,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "diamantine_icon_colour_G",
								type = "numeric",
								default_value = 158,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "diamantine_icon_colour_B",
								type = "numeric",
								default_value = 160,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
				},
			},

			-- STIMM
			{

				setting_id = "stimm_markers_settings",
				type = "group",
				tab = "Stimms",
				sub_widgets = {
					{
						setting_id = "stimm_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "recolor_stimm_compat_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "recolor_stimm_compat_enable_tooltip",
					},
					{
						setting_id = "toggle_background_colour",
						type = "checkbox",
						default_value = false,
						tooltip = "toggle_background_colour_tooltip",
					},
					{
						setting_id = "broker_stimm_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "stimm_enable_tooltip",
					},
					{
						setting_id = "stimm_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "boost_stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "boost_stimm_require_line_of_sight_tooltip",
					},
					{
						setting_id = "corruption_stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "corruption_stimm_require_line_of_sight_tooltip",
					},
					{
						setting_id = "power_stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "power_stimm_require_line_of_sight_tooltip",
					},
					{
						setting_id = "speed_stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "speed_stimm_require_line_of_sight_tooltip",
					},
					{
						setting_id = "broker_stimm_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "broker_stimm_require_line_of_sight_tooltip",
					},
					{
						setting_id = "stimm_toggle_los",
						type = "keybind",
						function_name = "stimm_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "stimm_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "stimm_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "stimm_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "boost_stimm_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "boost_stimm_icon_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "boost_stimm_icon_colour_G",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "boost_stimm_icon_colour_B",
								type = "numeric",
								default_value = 30,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "boost_stimm_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "corruption_stimm_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "corruption_stimm_icon_colour_R",
								type = "numeric",
								default_value = 30,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "corruption_stimm_icon_colour_G",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "corruption_stimm_icon_colour_B",
								type = "numeric",
								default_value = 30,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "corruption_stimm_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "power_stimm_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "power_stimm_icon_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "power_stimm_icon_colour_G",
								type = "numeric",
								default_value = 30,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "power_stimm_icon_colour_B",
								type = "numeric",
								default_value = 30,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "power_stimm_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "speed_stimm_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "speed_stimm_icon_colour_R",
								type = "numeric",
								default_value = 30,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "speed_stimm_icon_colour_G",
								type = "numeric",
								default_value = 150,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "speed_stimm_icon_colour_B",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "speed_stimm_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},

					{
						setting_id = "broker_stimm_icon_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "broker_stimm_icon_colour_R",
								type = "numeric",
								default_value = 200,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "broker_stimm_icon_colour_G",
								type = "numeric",
								default_value = 20,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "broker_stimm_icon_colour_B",
								type = "numeric",
								default_value = 200,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "broker_stimm_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- TOMES
			{

				setting_id = "tome_markers_settings",
				type = "group",
				tab = "Tomes",
				sub_widgets = {
					{
						setting_id = "tome_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "tome_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "tome_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "tome_toggle_los",
						type = "keybind",
						function_name = "tome_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "tome_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "tome_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "tome_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "grim_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "grim_colour_R",
								type = "numeric",
								default_value = 150,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "grim_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "grim_colour_B",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "script_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "script_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "script_colour_G",
								type = "numeric",
								default_value = 252,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "script_colour_B",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "tome_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- LUGGABLE
			{

				setting_id = "luggable_markers_settings",
				type = "group",
				tab = "Luggables",
				sub_widgets = {
					{
						setting_id = "luggable_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "luggable_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "luggable_require_line_of_sight",
						type = "checkbox",
						default_value = false,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "luggable_toggle_los",
						type = "keybind",
						function_name = "luggable_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "luggable_icon",
						type = "dropdown",
						options = luggable_icons,
						default_value = "content/ui/materials/icons/player_states/lugged",
						tooltip = "icon_tooltip",
					},
					{
						setting_id = "luggable_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "luggable_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "luggable_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "luggable_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "luggable_colour_R",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "luggable_colour_G",
								type = "numeric",
								default_value = 240,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "luggable_colour_B",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "luggable_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- MARTYR SKULL
			{

				setting_id = "martyrs_skull_markers_settings",
				type = "group",
				tab = "Martyr's Skull",
				sub_widgets = {
					{
						setting_id = "martyrs_skull_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "martyrs_skull_guide_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "martyrs_skull_guide_enable_tooltip",
					},
					{
						setting_id = "martyrs_skull_guide_markers_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "martyrs_skull_guide_markers_enable_tooltip",
					},
					{
						setting_id = "martyrs_skull_guide_disable_if_collected",
						type = "checkbox",
						default_value = true,
						tooltip = "martyrs_skull_guide_disable_if_collected_tooltip",
					},
					{
						setting_id = "martyrs_skull_guide_x_offset",
						type = "numeric",
						default_value = -1400,
						tooltip = "martyrs_skull_guide_x_offset_tooltip",
						range = { -2000, 2000 },
						decimals_number = 0,
					},
					{
						setting_id = "martyrs_skull_guide_y_offset",
						type = "numeric",
						default_value = -90,
						tooltip = "martyrs_skull_guide_y_offset_tooltip",
						range = { -1200, 1200 },
						decimals_number = 0,
					},
					{
						setting_id = "martyrs_skull_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "martyrs_skull_require_line_of_sight",
						type = "checkbox",
						default_value = false,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "martyrs_skull_toggle_los",
						type = "keybind",
						function_name = "martyrs_skull_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "martyrs_skull_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "martyrs_skull_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "martyrs_skull_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "martyrs_skull_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "martyrs_skull_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "martyrs_skull_colour_G",
								type = "numeric",
								default_value = 200,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "martyrs_skull_colour_B",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "martyrs_skull_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},

			-- EXPEDITION
			{

				setting_id = "expedition_markers_settings",
				type = "group",
				tab = "Expedition",
				sub_widgets = {
					{
						setting_id = "expedition_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "expedition_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "expedition_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "expedition_toggle_los",
						type = "keybind",
						function_name = "expedition_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "expedition_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "expedition_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "expedition_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},

					{
						setting_id = "expedition_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_border_colour_1",
						type = "dropdown",
						options = border_colours,
						default_value = "Tarnished",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_border_colour_2",
						type = "dropdown",
						options = border_colours,
						default_value = "Steel",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_border_colour_3",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "expedition_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "expedition_colour_R",
								type = "numeric",
								default_value = 192,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "expedition_colour_G",
								type = "numeric",
								default_value = 194,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "expedition_colour_B",
								type = "numeric",
								default_value = 110,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "expedition_pickups_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "expedition_pickups_colour_R",
								type = "numeric",
								default_value = 223,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "expedition_pickups_colour_G",
								type = "numeric",
								default_value = 108,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "expedition_pickups_colour_B",
								type = "numeric",
								default_value = 110,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "expedition_currency_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "expedition_currency_colour_R",
								type = "numeric",
								default_value = 233,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "expedition_currency_colour_G",
								type = "numeric",
								default_value = 185,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "expedition_currency_colour_B",
								type = "numeric",
								default_value = 110,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "expedition_reliquary_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "expedition_reliquary_colour_R",
								type = "numeric",
								default_value = 108,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "expedition_reliquary_colour_G",
								type = "numeric",
								default_value = 158,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "expedition_reliquary_colour_B",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "expedition_remnants_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "expedition_remnants_colour_R",
								type = "numeric",
								default_value = 137,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "expedition_remnants_colour_G",
								type = "numeric",
								default_value = 206,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "expedition_remnants_colour_B",
								type = "numeric",
								default_value = 125,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "expedition_crate_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "expedition_crate_colour_R",
								type = "numeric",
								default_value = 198,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "expedition_crate_colour_G",
								type = "numeric",
								default_value = 110,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "expedition_crate_colour_B",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
				},
			},
			-- EVENT MARKERS
			{

				setting_id = "event_markers_settings",
				type = "group",
				tab = "Event",
				sub_widgets = {
					{
						setting_id = "event_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "event_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "event_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "event_toggle_los",
						type = "keybind",
						function_name = "event_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "event_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "event_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "event_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "event_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "event_colour_R",
								type = "numeric",
								default_value = 200,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "event_colour_G",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "event_colour_B",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "event_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},
			-- SERVO SKULL MARKERS
			{
				setting_id = "servo_skull_settings",
				type = "group",
				tab = "Servo Skull/Assistance",
				sub_widgets = {
					{
						setting_id = "servo_skull_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "servo_skull_icon",
						type = "dropdown",
						options = servo_skull_icons,
						default_value = "content/ui/materials/backgrounds/scanner/scanner_decoration_skull",
						tooltip = "icon_tooltip",
					},
					{
						setting_id = "decoding_icon",
						type = "dropdown",
						options = decoding_icons,
						default_value = "content/ui/materials/icons/mission_types/mission_type_03",
						tooltip = "icon_tooltip",
					},
					{
						setting_id = "servo_skull_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "servo_skull_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "servo_skull_toggle_los",
						type = "keybind",
						function_name = "servo_skull_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "servo_skull_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "servo_skull_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "servo_skull_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "servo_skull_pulse_when_stalled",
						type = "checkbox",
						default_value = true,
						tooltip = "pulse_when_stalled_tooltip",
					},
					{
						setting_id = "servo_skull_enable_assistance_module",
						type = "checkbox",
						default_value = true,
						tooltip = "servo_skull_enable_assistance_module_tooltip",
					},
					{
						setting_id = "servo_skull_default_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "servo_skull_default_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "servo_skull_default_colour_G",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "servo_skull_default_colour_B",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "servo_skull_stalled_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "servo_skull_stalled_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "servo_skull_stalled_colour_G",
								type = "numeric",
								default_value = 200,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "servo_skull_stalled_colour_B",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "servo_skull_active_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "servo_skull_active_colour_R",
								type = "numeric",
								default_value = 0,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "servo_skull_active_colour_G",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "servo_skull_active_colour_B",
								type = "numeric",
								default_value = 50,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "servo_skull_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Steel",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "servo_skull_stalled_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Tarnished",
						tooltip = "border_colour_tooltip",
					},
					{
						setting_id = "servo_skull_active_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Gold",
						tooltip = "border_colour_tooltip",
					},
				},
			},
			-- UNKNOWN
			{

				setting_id = "unknown_markers_settings",
				type = "group",
				tab = "Unknown",
				sub_widgets = {
					{
						setting_id = "unknown_enable",
						type = "checkbox",
						default_value = true,
						tooltip = "enable_tooltip",
					},
					{
						setting_id = "unknown_markers_extra_allowed",
						type = "checkbox",
						default_value = false,
						tooltip = "unknown_markers_extra_allowed_tooltip",
					},
					{
						setting_id = "unknown_keep_on_screen",
						type = "checkbox",
						default_value = false,
						tooltip = "keep_on_screen_tooltip",
					},
					{
						setting_id = "unknown_require_line_of_sight",
						type = "checkbox",
						default_value = true,
						tooltip = "require_line_of_sight_tooltip",
					},
					{
						setting_id = "unknown_toggle_los",
						type = "keybind",
						function_name = "unknown_toggle_los",
						default_value = {},
						keybind_global = true,
						keybind_trigger = "pressed",
						keybind_type = "function_call",
						tooltip = "toggle_los_tooltip",
					},
					{
						setting_id = "unknown_max_distance",
						type = "numeric",
						default_value = 50,
						range = { 0, 100 },
						step_size_value = 1,
						tooltip = "max_distance_tooltip",
					},
					{
						setting_id = "unknown_scale",
						type = "numeric",
						default_value = 100,
						range = { 50, 150 },
						step_size_value = 1,
						tooltip = "scale_tooltip",
					},
					{
						setting_id = "unknown_alpha",
						type = "numeric",
						default_value = 1,
						range = { 0.1, 1 },
						decimals_number = 2,
						step_size_value = 0.05,
						tooltip = "alpha_tooltip",
					},
					{
						setting_id = "unknown_colour",
						type = "group",
						sub_widgets = {
							{
								setting_id = "unknown_colour_R",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_R_tooltip",
							},
							{
								setting_id = "unknown_colour_G",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_G_tooltip",
							},
							{
								setting_id = "unknown_colour_B",
								type = "numeric",
								default_value = 255,
								range = { 0, 255 },
								step_size_value = 1,
								tooltip = "colour_B_tooltip",
							},
						},
					},
					{
						setting_id = "unknown_border_colour",
						type = "dropdown",
						options = border_colours,
						default_value = "Silver",
						tooltip = "border_colour_tooltip",
					},
				},
			},
		},
	},
}
